### ISSUE TITLE
IE8 gets really slow

### ISSUE THREAD

**Issue by Golodhros** [scottjehl/picturefill#112]
Hi there,

We are developing a site with Bootstrap 3 and we need to give support to IE8. As stated on the Bootstrap documentation, we need Respond.js to support mediaqueries. We are also loading html5shiv.js.

Our problem is that, although picturefill works grabbing just the first data-src on the list of options, it gets slowed down a Lot, and by that I mean around 10 or 15 seconds.

As respond comes with matchMedia.js, I have tried to plug that IE7/8 version I have seen on some of the issues instead of the current one, but no luck with it.

Many thanks for your hard work and this fantastic tool, I have used it on a bunch of projects without any problem (until now).

Bootstrap: http://getbootstrap.com/getting-started/#browsers
IE7/8 supporting matchMedia: https://github.com/benschwarz/matchMedia.js/blob/IE7-8/matchMedia.js

**Comment by DominicTobias** [comment]
Takes about 2-3 seconds per picture for me, on a results page with 20, the browser becomes unresponsive for ~40 seconds just for the pictures (well, images with sizes + srcsset). Using Paul Irish's minimal matchMedia. I haven't identified the actual bottleneck, not sure why it would take that long, just going to fallback to src and not use picturefill for IE8.
