### ISSUE TITLE
refactor: Cache properties on a parsed <picture>

### ISSUE THREAD

**Issue by knightdr** [scottjehl/picturefill#142]
I believe this could save some unnecessary processing and allow programatic access to each of the following properties. Implementing the ```pictureSource``` would be the most important as far as performance goes as I see it. It would contain all the required strings/objects needed to obtain the proper asset's URI. It could be accessed on window resize or by a listener applied to a media query object. I used this technique on the following repo for example using the fallback span syntax: https://github.com/weblinc/picture

```
// Element to receive src updates
pictureImage = <img>;

// Alternative text for the <picture> (used for the <img>'s alt)
pictureAlt = '';

 // Represents the chosen asset's URI
pictureCurrentSrc = 'asset_uri.ext';

// Represents each parsed <source> for a parent <picture>
pictureSource = [ { ... }, ... ];
```

**Comment by mike-engel** [comment]
@aFarkas Correct me if I'm wrong but I think we're doing something similar to this with 2.3/3.0?

**Comment by aFarkas** [comment]
Yes, we do in 3.0
