### ISSUE TITLE
picturefill and retina

### ISSUE THREAD

**Issue by caiotarifa** [scottjehl/picturefill#216]
How can I use `picturefill` to serve retina images?

Currently I'm using the version 2, my HTML code is:

``` html
<img src="http://placehold.it/300x150" srcset="http://placehold.it/600x300 2x" alt="Alternative" />
```

**The problem is:** in all browsers, except Chrome, are getting the "2x" version, but my screen doesn't support retina.

[I think Chrome is working because this feature was recently implemented.](http://caniuse.com/srcset)

What am I doing wrong?

**Comment by tobireif** [comment]
Any news on this?

Related: The readme https://github.com/scottjehl/picturefill recommends to not use the src attribute on the img tag. Also considering the previous comments on this page, is this recommended?

```<img srcset="foo@1x.png 1x, foo@2x.png 2x"/>```
