### ISSUE TITLE
Duplicate Images - Viewport Change

### ISSUE THREAD

**Issue by Ne-Ne** [scottjehl/picturefill#244]
I have noticed that the script visually works well but when the user changes the viewport the same image is download again and again.

Example when changing the width of the demo page by a few pixels:

![screen shot 2014-05-20 at 10 30 14](https://cloud.githubusercontent.com/assets/2177851/3025110/5bf24b72-e001-11e3-9490-cf686b71da9b.png)

I have seen something similar to this but the image was cached. But this is just showing a 304 status of "Not Modified", does this image use bandwidth or am I missing something?

Needless to say Chrome seems to be waiting on the image. I am using the latest version.

![screen shot 2014-05-20 at 10 28 25](https://cloud.githubusercontent.com/assets/2177851/3025084/205bbb7a-e001-11e3-88d4-7116f4890e99.png)

**Comment by aFarkas** [comment]
This one should be fixed with the 2.3 version. @Ne-Ne can you verify and close this one?

**Comment by mike-engel** [comment]
Assuming this has been fixed with 2.3. If not, @Ne-Ne, let us know and we'll reopen this issue.
