### ISSUE TITLE
Picturefill on some CDNs

### ISSUE THREAD

**Issue by marcoscaceres** [scottjehl/picturefill#247]
Would be awesome if we could get PF2 being hosted by some CDNs (if hasn't happened already). Might be worth pinging the RICG mailing list - there are quite a few big CDNs watching that list, so it could be mutually beneficial if a few of them offered to host (maybe something for @Wilto to ask as Chair?).

**Comment by Rycochet** [comment]
Old thread - but would be useful if you linked to these on the github.io site (near the downloads?) - took a google for me to find this and I'm sure I won't be the only one ;-)
