### ISSUE TITLE
IE8 doesn't appear to work

### ISSUE THREAD

**Issue by JohnCashmore** [scottjehl/picturefill#262]
I am having an issue with IE8 were picturefill doesn't appear to be working, I thought it was my code but it also doesn't function as expected on the demo. Is this a known issue?

![image](https://cloud.githubusercontent.com/assets/2050794/3227344/d592b948-f079-11e3-81e6-525344fcfd0e.png)

**Comment by skyyip** [comment]
It is a known MatchMedia issue. Use this version of MatchMedia to resolve it: https://github.com/benschwarz/matchMedia.js/blob/IE7-8/matchMedia.js

**Comment by yakutsa** [comment]
@skyyip , even though I implemented the versionf of MatchMedia you have mentioned, it still doesn't work on IE8 and IE9.

**Comment by aFarkas** [comment]
@yakutsa 

The fact, that it doesn't work in IE9 for you, is very weird. We would need a simplified testcase. You can also try the following [pre-alpha version of picturefill](https://cdn.rawgit.com/scottjehl/picturefill/afarkas-pf3-proposal/dist/picturefill.js), which fixes the IE8 (matchMedia) issues

**Comment by yakutsa** [comment]
@aFarkas ,

This is the code snippet that I have been using: https://jsfiddle.net/k7n9ev3r/

I didn't use the latest version of picturefill. But in some websites, I saw that the code snippet I have sent is working on IE8 and IE9. Maybe I am missing something here, I am not sure.

**Comment by aFarkas** [comment]
Oh, sorry. This was all about picturefill 2.0/3.0. We strongly recommend to update.

**Comment by Wilto** [comment]
This one will be sorted by 3.0.

**Comment by spacedawwwg** [comment]
yey
