### ISSUE TITLE
Lazyloading : how to prevent picturefill 2 execution on DOM ready ?

### ISSUE THREAD

**Issue by Chmood** [scottjehl/picturefill#265]
I'm trying to pair picturefill 2 with lazyloading, which implies that picturefill() must not run on the whole markup when page is loaded, but only be triggered on images that are in the viewport (or near of it).

To do this with picturefill 1.2, you had to : 

- ommit the data-picture attributes of the wrapping spans,
- listen to scroll / resize events,
- do some maths,
- add data-picture attributes where needed,
- run picturefill() manually.

(As explained in [this issue](https://github.com/scottjehl/picturefill/issues/99) and [that codepen](http://codepen.io/jonahx/pen/536957770caa3b5e3deb8d96bd421314)).

What would be the equivalent trick for Picturefill 2 ?

The `elements` option can be used to target a specific image, but how to disable the automatic execution of picturefill() ?

**Comment by mike-engel** [comment]
Looks like we have a solution here, with one other bug still open #239. Closing this one. Thanks everyone.

**Comment by FrancoTanzarella** [comment]
This solution works well but how will you manage thumbnail navigation. Here is a pen I'm testing with.
http://codepen.io/anon/pen/OVveXK

If I don't go through the slides in order the images doesn't load.

**Comment by aFarkas** [comment]
Simply use [lazySizes](https://github.com/aFarkas/lazysizes). Here is a [demo using flexslider](http://codepen.io/aFarkas/pen/OPzEzE).

**Comment by FrancoTanzarella** [comment]
Yes thanks that does work well.

**Comment by iDVB** [comment]
Is there a solution here? I saw about 3 different ones and nothing concretely concluded as the working solution.
