### ISSUE TITLE
Problem with image exclusion

### ISSUE THREAD

**Issue by Jaska** [scottjehl/picturefill#268]
I thought about using picturefill to display an image only on a certain mediaquery -and request nothing otherwise.

Like this:
```
<img 
sizes="(min-width: 768px) 200px"
srcset="../img/sample.svg 200w"
alt="Samplepic"> 
```
But that won't work. The image is still displayed when the viewport is less than 768px.

This issue is similar to https://github.com/scottjehl/picturefill/issues/41. Could it be that Picturefill 2.0 has to always load some image? Or am I just misunderstanding the picturefill syntax?

Btw: I got it working by using a dummy picture:

```
 <img 
sizes="(min-width: 768px) 200px, 1px"                    
srcset="../img/sample.svg 200w, data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== 2w"
alt="Samplepic">
```

**Comment by jaicab** [comment]
Very interested on this. I'll use @Jaska's approach (thanks mate!) for now but it would be interesting to know more about this, I'm sure there's a way to do it without the dummy image. Anybody?

**Comment by aFarkas** [comment]
Do it the picture way:

```html
<picture>
    <source srcset="../img/sample.svg" media="(min-width: 768px)" />
    <img                     
        srcset="data:image/gifbase64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" /
        alt="Samplepic" />
</picture>
```

**Comment by jaicab** [comment]
Actually, now you mention it... this works, and it's supposed to be valid syntax!

```html
<picture>
    <source srcset="../img/sample.svg" media="(min-width: 768px)" />
    <img />
</picture>
```

**Comment by mike-engel** [comment]
Closing this one out as the transparent gif seems to work. Thanks!
