### ISSUE TITLE
Width of viewport or document?

### ISSUE THREAD

**Issue by tbazko** [scottjehl/picturefill#292]
Hi, 
I encountered the problem that my pictures are changed on bigger size of viewport, then my media queries are being changed. For example Chrome, OSX:
Picturefill switch pics on - 1023 body width / 1038 viewport width
Media queries switch styles on - 1008 body width / 1023 viewport width
Similar problem on other browswers, depending on scrollbar width.

In W3C specs it's stated that:
"The ‘width’ media feature describes the width of the targeted display area of the output device. For continuous media, this is the width of the viewport (as described by CSS2, section 9.1.1 [CSS21]) including the size of a rendered scroll bar (if any)."

So is there is some reason behind your solution to make pictures switching depending on document size instead of viewport?

P.S. I fixed that for my needs and it seems to work. On line 131 I'm returning window.outerWidth instead of pf.lengthEl.offsetWidth
But it's hotfix, I'm afraid if it won't crash smth else?

**Comment by mike-engel** [comment]
I'm assuming this should be fixed in 3.0. Closing for now.
