### ISSUE TITLE
Problem with comma in URL in IE 7

### ISSUE THREAD

**Issue by in2isoft** [scottjehl/picturefill#296]
if ...

var last = url[ url.length - 1 ];

...is changed to...

var last = url.substr(url.length-1);

...it will work better in IE7

(Sorry - I have no time to submit this properly at the moment)

**Comment by jegtnes** [comment]
@jonathantneal: Are you able to check whether this has been fixed in Picturefill 3.0 beta?

https://github.com/scottjehl/picturefill/tree/3.0

**Comment by mike-engel** [comment]
@baloneysandwiches this should be fixed now, yeah? Have you tested this yet with your changes?

**Comment by albell** [comment]
Sorry for delay, yes this is fixed in 3.0. Closing.
