### ISSUE TITLE
Examples using <source media> don't use art direction

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#308]
http://scottjehl.github.io/picturefill/ - the `picture` example uses the same assets as the `sizes` example. For people who don't read but just copies examples, this is confusing.

I think the page could do a better job overall by explaining and showcasing the use case and the markup that goes with it instead of having the same image assets for all use cases and sizes="" value that doesn't even reflect the breakpoints in the CSS.

**Comment by Wilto** [comment]
I’ll get this today.
