### ISSUE TITLE
sizes <length> resolving has bugs

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#309]
The getWidthFromLength function has two problems

* It makes the document invalid by inserting a div as child of the root element.
* It doesn't compute the length against the viewport if the root is not position:static and doesn't have the same width as the viewport.

I suggest inserting it in body and use position:fixed instead.

**Comment by mike-engel** [comment]
@aFarkas Another one of your fixes that didn't end up getting merged through the PR. Did this make it into 2.3/2.4/3.0?

**Comment by aFarkas** [comment]
Yes, this is in 3.0

**Comment by mike-engel** [comment]
Is this something we want to add to 2.3/2.4 or just leave it for 3.0?

**Comment by Wilto** [comment]
Closin’ now that we’re doing the beta thing.
