### ISSUE TITLE
getWidthFromLength should evaluate 'em' against the default font size

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#314]
Spec says

> A source size is a <source-size-value>. When a source size has a unit relative to the viewport, it must be interpreted relative to the img element's document's viewport. Other units must be interpreted the same as in Media Queries. [MQ]

and in media queries, `em` is relative to the default font size, not the computed font size of some element in the document.

Ack https://twitter.com/paulozoom/status/500203796140924928

**Comment by mike-engel** [comment]
@aFarkas Did this get into 2.3 or 3.0? I know you had taken care of it in a couple of PRs that didn't make it.

**Comment by aFarkas** [comment]
It's in 3.0 and we wanted it actually in 2.3, but later never didn't happen.
