### ISSUE TITLE
domready updated picturefill update most likely required

### ISSUE THREAD

**Issue by theodoreb** [scottjehl/picturefill#317]
Domready has been updated because there were issues with IE9 triggering the interactive state before DOMContentLoaded. I haven't tested if the issue is present with picturefill on IE9. In any case the comment is now incorrect and need to be updated at least.

See up to date domready code: https://github.com/ded/domready/blob/master/ready.js#L16 

This needs to be changed https://github.com/scottjehl/picturefill/blob/master/src/picturefill.js#L655

Reference: ded/domready#31

**Comment by mike-engel** [comment]
So, this was done previously, but now the line number has changed again. I recommend taking this comment out of the code, or referencing the original PR (ded/domready#31).

**Comment by quoo** [comment]
This was removed in 3.0.
