### ISSUE TITLE
Use MutationObserver to picturefill img elements as they are inserted

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#318]
Instead of running picturefill in a timer, we could use `MutationObserver` (if supported) and picturefill an `img` element when it is inserted to the document. This would maybe have less overhead and less lag, and also work post-onload.

Relatedly, it might be good to implement http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#relevant-mutations which also needs `MutationObserver` (could fall back to mutation events).

**Comment by mike-engel** [comment]
Ping @aFarkas to see if, a) this made it into 3.0 or 2.4, or b) a different approach was decided upon. I didn't see any MutationObserver stuff in 3.0, but I was only skimming.

**Comment by aFarkas** [comment]
It is here:
https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/plugins/mutation/pf.mutation.js

It also adds some IDL attributes and makes fun:

```js
img.srcset = 'data:,a 300w, data:,b 600w';
```
