### ISSUE TITLE
Picturefill doesn't work with device-width

### ISSUE THREAD

**Issue by JimmyLeonardson** [scottjehl/picturefill#321]
If my site's media queries are based on device-width the layout is not impacted on resize of the browser window in desktop, however the Picturefill script listens to the document width rather than the device viewport width.

Is there a way to make picturefill listen to the device-width rather than browser width?

**Comment by mike-engel** [comment]
Going to go with wont-fix for this one @JimmyLeonardson unless you really think we should support device-width.
