### ISSUE TITLE
Sync srcset parser with the current spec

### ISSUE THREAD

**Issue by zcorpan** [scottjehl/picturefill#322]
It looks like there are a few details where the impl doesn't match the spec.

http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#parse-a-srcset-attribute

* It doesn't skip leading "," (step 4). `srcset=",,,,foo 1x, ,,,,,bar 2x"`
* It seems to treat `h` descriptors the same as `w` descriptors but that is not the case in the spec at all.
* It only looks at the last character to determine the descriptor but the spec requires the whole descriptor to be valid to be successfully parsed. (step 13) `srcset="foo 2xxx"`
* It doesn't implement the descriptor tokenizer. (step 8) `srcset="foo (,)"`

(The above is probably not exhaustive.)

**Comment by Wilto** [comment]
We’re usin’ this very parser for 3.0.

**Comment by TxHawks** [comment]
Does this mean that the h descriptor can be used in picturefill 3? How would the sizes attribute be written (when not in `vh` units)?

**Comment by aFarkas** [comment]
This is only for future compat. See http://stackoverflow.com/questions/29778235/can-i-use-picture-for-both-height-and-width-constrained-images and http://stackoverflow.com/questions/31252632/is-it-safe-to-define-multiple-descriptors-in-srcset/31253366#31253366
