### ISSUE TITLE
pf.verifyTypeSupport is run multiple times for one type

### ISSUE THREAD

**Issue by aFarkas** [scottjehl/picturefill#330]
In case you are using webp you are probably using it more than once, but the test function is executed multiple times before the test function is resolved. I solved this by simply adding ``pf.types[ type ] = "pending";`` inside of the testfunction. ([see](https://github.com/aFarkas/picturefill/blob/f2831eba6ecbcc267fc851b6da0982b51101565c/src/picturefill.js#L104-143))

But a small error with your tests let me look a little bit deeper into it. I re-factored the webp test. By splitting it into an image test factory and the concrete webp test:

```js
//test factory:
pf.createImageTest = function( type, src ){
	pf.types[ type ] = function(){
		// based on Modernizr's lossless img-webp test
		// note: asynchronous
		var img = document.createElement( "img" );

		pf.types[ type ] = "pending";

		img.onerror = function() {
			pf.types[ type ] = false;
			picturefill();
		};
		img.onload = function() {
			pf.types[ type ] = img.width === 1;
			picturefill();
		};
		img.src = src;
	};
};
```

And here the concrete webp test:

```js
// test webp support, only when the markup calls for it
pf.createImageTest( "image/webp", "data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=" );
```

As you can see now it's possible to add other tests very quickly. It's even possible to feed ``pf.verifyTypeSupport`` dynamically with tests based on the markup without knowing anything about the concrete type:

```js
pf.verifyTypeSupport = function( source ) {
	var srceset;
	var type = source.getAttribute( "type" );
	if( type ){
		if( !(type in pf.types) && (srcset = source.getAttribute( "srcset" )) ){
			pf.createImageTest(type, srcset );
		}
		if( typeof( pf.types[ type ] ) === "function" ){
			pf.types[ type ]();
		}
		return pf.types[ type ];
	} else {
		return true;
	}
};
```

Of course you can still retrun ``undefined`` if you don't trust your users (or don't want to adjust your tests or performance...):

```js
pf.verifyTypeSupport = function( source ) {
	var type = source.getAttribute( "type" );
	if( type ){
		if( typeof( pf.types[ type ] ) === "function" ){
			pf.types[ type ]();
		}
		return pf.types[ type ];
	} else {
		return true;
	}
};
```

see also: https://github.com/aFarkas/picturefill/blob/master/src/picturefill.js#L120-166

**Comment by Wilto** [comment]
This is squared, yeah?

**Comment by aFarkas** [comment]
Yes.
