### ISSUE TITLE
Cache + minimized repaints in ``pf.getWidthFromLength``

### ISSUE THREAD

**Issue by aFarkas** [scottjehl/picturefill#331]
I have added a simple cache + I only change the needed style poperty (i.e.: left) and not the hole inline style.

Additionally, I'm detaching ``pf.lengthEl`` as long as it isn't in use.

Here is the code for this change, maybe you want to take some parts:
https://github.com/aFarkas/picturefill/commit/519c647f316975115f84b195b84364ec163f2ad5

**Comment by mike-engel** [comment]
@aFarkas Looks like this is in 3.0 now, yeah?

**Comment by aFarkas** [comment]
Yes, it is.
