### ISSUE TITLE
double shiv?

### ISSUE THREAD

**Issue by albell** [scottjehl/picturefill#352]
The current "Getting Started" docs recommend separately adding the shiv:

````
// Picture element HTML5 shiv
document.createElement( "picture" );
````
but the same code is also run near the top of the actual code. No harm here, but this seems redundant.

Is there a reason (other than the shiv) why the script needs to be linked in the `<head>`? I can't seem to see one. If there's a good reason it should go in the docs. Given that ancient browsers don't support `async`, and that isn't always appropriate, isn't it better to just tell people to include the file anywhere, typically the bottom of the `<body>` , for the usual performance reasons?

so the idea is:

1) Remove the shiv from the code.
2) Add the clarification to the docs that if the author needs `<picture>` elements, and not just `<img srcset>`  , then the author will need a shiv in some form in the `<head>`. (`<img srcset>` is in fact probably the vast majority non-art-direction use case. I wouldn't be surprised if I almost never use `<picture>` in production. So I can typically get away with no shiv at all, even though I'm supporting old browsers.)

**Comment by mike-engel** [comment]
Alright @baloneysandwiches @aFarkas, do we want this to go in for 3.0 or are we ok with a possible double shim?

**Comment by aFarkas** [comment]
I think we have different opinions about moving picturefill to top or to bottom. About IE8/IE9 not supporting ``async``. I don't really feel bad about it. Support the old, optimise for the new

**Comment by baloneysandwiches** [comment]
I'm fine with either. I guess my philosophy is that the polyfill is 99% about supporting the old.

**Comment by mike-engel** [comment]
I guess I don't see a reason to _remove_ it really. For one line of code, it reduces potential complexity from the user having to add a script tag to their `<head>` to cover this. If anyone is strongly objected to keeping it in, reopen this issue. Closing for now.

**Comment by ccraze-matt** [comment]
@mike-engel Your reasoning to leave it in is understood. I agree, but have an additional concern.

The issue of documentation, as mentioned by @albell is still at large. The implementation paragraphs should include the fact that the shiv is unnecessary when using only `<img srcset>`. Additionally, these paragraphs should mention the fact that if you do include the shiv line in the head, then the picturefill js can safely be loaded from the end of the body.

"The polyfill [by definition] is 99% about supporting the old." A great quote I read somewhere.

**Comment by mike-engel** [comment]
Let's clarify the docs a little bit. Can't hurt. Thanks @ccraze-matt

**Comment by mike-engel** [comment]
Looks like this got into the 3.0 docs, so closing!
