### ISSUE TITLE
JS Error in Chrome 38 when using picturefill as named requireJS module

### ISSUE THREAD

**Issue by crohrer** [scottjehl/picturefill#356]
I can reproduce a JS error on the new version of chrome (38) when using picturefill as named requireJS module:
http://codepen.io/crohrer/pen/nxbyI
Open your js-console. In chrome it logs only "this works", the string "this doesn't work" is not logged, because of an error in picturefill. 
In Firefox both strings are logged as expected.

**Comment by mike-engel** [comment]
@crohrer, @eatarandom, @tangst Has this been fixed for you with 2.3/3.0-beta (It should have)?

**Comment by tangst** [comment]
@mike-engel , I'm on picturefill 2.3.1 now, and the error appears to be gone.  I rebuilt my project using the r.js optimizer, and I don't see any more console errors related to this.

**Comment by mike-engel** [comment]
Great, thanks @tangst. Closing the issue. If anyone has any further issues, let us know.
