### ISSUE TITLE
Adding new `type` formats.

### ISSUE THREAD

**Issue by Wilto** [scottjehl/picturefill#372]
cc @zoltan-dulac

We’ve largely given up on making Picturefill itself modular, since we’re going for dead-on spec compliance, but I would like to look into ways we can extend `type` support in a flexible way; see: https://github.com/scottjehl/picturefill/pull/363

Whether or not we want to make JPEG2000 part of the project proper, people should be able to add whatever formats they need without altering Picturefill itself, and I’m totally okay with maintaining a directory of `type` extensions.

**Comment by mike-engel** [comment]
To quote wilto:

> ...that biz is merged and square.
