### ISSUE TITLE
useless image load in Firefox 33.1 Android 4 landscape orientation

### ISSUE THREAD

**Issue by cecorob** [scottjehl/picturefill#386]
Hello,
I tested successfully Picturefill on different browsers including chrome and embedded browser on Android 4.1.2 Galaxy Tab 2 using following code:
```
<picture>
        <!--[if IE 9]><video style="display: none;"><![endif]-->
        <source srcset="images/large.jpg, images/large-highres.jpg 2x" media="(min-width: 1200px)">
        <source srcset="images/medium.jpg, images/medium-highres.jpg 2x" media="(min-width: 992px)">
        <source srcset="images/small.jpg, images/small-highres.jpg 2x" media="(min-width: 768px)">
        <source srcset="images/extra-small.jpg, images/extra-small-highres.jpg 2x" media="(min-width: 300px)">
        <!--[if IE 9]></video><![endif]-->
        <img srcset="" alt="Une bien belle image dans le alt">
</picture>
```

However, checking access Logs, we noticed that "Mozilla/5.0 (Android; Tablet; rv:33.0) Gecko/33.0 Firefox/33.0" (actually FF 33.1) on Android 4 when in landscape orientation mode was loading the small and the large image (in portrait, only small is loaded) 
that's why i tried the ```<img srcset="">``` which seemed to solve the pb but only once

-With picturefill.js 2.0/2.0beta, this happens on first load and refresh
-With picturefill master, this happens only on first load.

Thank you in advance for any help and thank you for this script!

**Comment by cecorob** [comment]
Hello, I just tested with FF 34 on Android 4 with picturefill.2.2.0 and for me, problem is gone
(I had the problem with FF 33)

**Comment by mike-engel** [comment]
Thanks @cecorob! Glad to see it's all better now. @curtisblackwell are you still seeing this with the newer versions of firefox?

**Comment by curtisblackwell** [comment]
@mike-engel Sorry it took so long to get back to you, I must've deleted the notification before checking things out.

No, `dom.image.srcset.enabled` was not set to `true`. I was mistaken about FF's support of `srcset`.

However, I did set it to true and restart the browser (34.0.5, newest). I'm seeing 3 versions of each image loaded now. I also get a javascript error (only in FF):

> TypeError: setting a property that has only a getter `picturefill.min.js:396`

**Comment by giles-v** [comment]
I'm seeing the same issue as @curtisblackwell on FF 35.0.1 on Yosemite: the `src` attribute is loaded first, and then the correct item from `srcset` is loaded and swapped out later on.

I do NOT have `dom.image.srcset.enabled` set to `true`. I'm using picturefill v2.2.0-beta - 2014-11-19.

**Comment by mike-engel** [comment]
@curtisblackwell, sorry it's been a while. If you update to 2.3.1 or 3.0-alpha, is there still the same issue?

**Comment by Wilto** [comment]
Closing this out, but please reopen if the issue persists with 2.3.1/3.0
