### ISSUE TITLE
Version 1.2 and scrollbar size

### ISSUE THREAD

**Issue by jessirwin** [scottjehl/picturefill#392]
Hi,

I have the following markup:

```
<span data-picture data-alt="Image">
	<span data-src="images/banners/banner-01-sml.jpg"></span>
	<span data-src="images/banners/banner-01-med.jpg" data-media="(min-width: 768px)"></span>
	<span data-src="images/banners/banner-01-lrg.jpg" data-media="(min-width: 1024px)"></span>
	<span data-src="images/banners/banner-01-wide.jpg" data-media="(min-width: 1200px)"></span>

	<!--[if (lt IE 9) & (!IEMobile)]>
        <span data-src="images/banners/banner-01-lrg.jpg"></span>
    <![endif]-->

	<!-- Fallback content for non-JS browsers. -->
	<noscript>
		<img alt="Image" src="images/banners/banner-01-sml.jpg">
	</noscript>
</span>
```
The problem I have is catering for the scrollbar size. The above fires correctly on a Mac as it doesn't show scrollbars, but when viewed on Windows with scrollbars it doesn't fire correctly. Using Chrome on both machines.

Is there a way to cater for the scrollbar width?

Thanks,
Jess

**Comment by mike-engel** [comment]
@jessirwin Just checking to see if you are indeed stuck with 1.2, or if you can migrate over to 2.2. Thanks!

**Comment by mike-engel** [comment]
Closing for now since this shouldn't be a problem with 2+. @jessirwin if you still *have* to support 1.2, let us know.
