### ISSUE TITLE
converted 'vw' value should be conditional on "overflow" value for root element

### ISSUE THREAD

**Issue by baloneysandwiches** [scottjehl/picturefill#396]
<a href="http://dev.w3.org/csswg/css-values/#numbers">Spec</a> says:

> The viewport-percentage lengths are relative to the size of the initial containing block. When the height or width of the initial containing block is changed, they are scaled accordingly. However, when the value of overflow on the root element is auto, any scroll bars are assumed not to exist. Note that the initial containing block’s size is affected by the presence of scrollbars on the viewport.

Scrollbars affecting viewport width is a serious gotcha. I don't see this logic currently implemented. Need to match spec here.

**Comment by terryupton** [comment]
+1

**Comment by rubyisapm** [comment]
I don't really understand the effect of the scrollbars of viewport to the initial containing block's size? Anyone could understand it for me? Appreciate your time.

**Comment by mike-engel** [comment]
@aFarkas Correct me if I'm wrong, but this looks like it's probably in 3.0 now?

**Comment by mike-engel** [comment]
Ping @aFarkas To see if this got into 2.3/2.4/3.0.

**Comment by Wilto** [comment]
> @aFarkas Correct me if I'm wrong, but this looks like it's probably in 3.0 now?

Bump; just double-checking this.

**Comment by aFarkas** [comment]
Yes, it is in 3.0
