### ISSUE TITLE
sizes parser

### ISSUE THREAD

**Issue by baloneysandwiches** [scottjehl/picturefill#400]
https://github.com/baloneysandwiches/parse-sizes

It handles input more correctly than the current parser, while staying small (1.1k, 603 bytes gzipped). A bit of the utility code is shared with my srcset parser that @aFarkas has put in the new 3.0 branch, so it could go even smaller.

I think it's especially important to parse CSS comments correctly, because developers are likely to include them in hand-written code as annotations. I also think helpful console logging is probably useful, as the syntax is relatively complex. (As single HTML attributes go, it's possibly at the current apex of complexity.) Lastly, I agree it's not worth tracking down every single edge case, but I also think we should be rigorous in our testing game. If there's a discussion to be had about support vs code weight, let's have it here...

**Comment by mike-engel** [comment]
Looks like this has been merged in, so I'm gonna close this one out. Let me know if it needs to be reopened @baloneysandwiches.
