### ISSUE TITLE
Add matchMedia as a requirement in Bower and documentation

### ISSUE THREAD

**Issue by Moinax** [scottjehl/picturefill#402]
Hi,

Wouldn't it be better to add matchMedia as a requirement in the documentation and as a dependency in the bower.json file instead of including it in your project ? 

Regards,

**Comment by mike-engel** [comment]
I'm inclined to say no, as it could cause unneeded version conflicts with bower. Pinging @wilto to see what he thinks, but I think it may be better just to have the parent project include it if they need it.

**Comment by aFarkas** [comment]
Wiht pf3 this would be fixed, because we don't have a (hard) dependency to ``matchMedia`` anymore.

**Comment by mike-engel** [comment]
Blammo. Closing the issue. For those who will stick with 2.x for now, I think it's best to include matchMedia as needed to avoid any potential version conflicts. If someone feels strongly that we should include matchMedia in 2.x, let us know and we'll reopen the issue.
