### ISSUE TITLE
Does not work with queryLoader2 !

### ISSUE THREAD

**Issue by jimmyphong** [scottjehl/picturefill#408]
how to make it work with query loader2

html makeup

    <picture>
	 
												        
	<source srcset="asset/images/blog/responsive-small.jpg" media="(min-width: 1200px)">
	<source srcset="asset/images/blog/responsive-medium.jpg" media="(min-width: 768px)">
	<source srcset="asset/images/blog/responsive-large.jpg" media="(min-width: 280px)">
	
	 <img srcset="asset/images/blog/responsive-small.jpg" alt="Responsive Image - Resize browser see action">
     </picture>

with queryloader2 (https://github.com/Gaya/queryloader2);

**Comment by mike-engel** [comment]
@jimmyphong I'm going to close this issue as it seems to be a bug with queryLoader2. If you find that it's a picturefill bug, re-open this issue and we'll be happy to help you out!

**Comment by stefanoantonel** [comment]
Make sure that your <img> tag has a "src = ' ' " attribute. I don't know if this script is prepare for scrset
