### ISSUE TITLE
Not up-to-date on Cloudflare

### ISSUE THREAD

**Issue by curtisblackwell** [scottjehl/picturefill#411]
Not sure how things end up on Cloudflare, but Picturefill's still on the 2.2.0 beta on Cloudflare.

**Comment by mike-engel** [comment]
@wilto or @scottjehl do either of you manage picturefill on cloudflare?

**Comment by Wilto** [comment]
Not us. Looks like 2.2.0 stable is up there now, though? I think it just pulls from the repo tags; there must be a delay.
