### ISSUE TITLE
media attribute does not work as expected - responsive layout

### ISSUE THREAD

**Issue by Ninos** [scottjehl/picturefill#416]
Hey there,
I'm using the picturefill 2.2.0 lib with following html5-snippet:
```
<picture>
	<!--[if IE 9]><video style="display: none;"><![endif]-->
	<source 
		media="(max-width: 300px)"
		sizes="100vw"
		srcset="picture-300.jpg,
				picture-450.jpg 1.5x,
				picture-600.jpg 2x" />
	<source 
		media="(min-width: 300px)"
		sizes="100vw"
		srcset="picture-600.jpg,
				picture-900.jpg 1.5x,
				picture-1200.jpg 2x" />
	<source 
		media="(min-width: 600px)"
		sizes="100vw"
		srcset="picture-768.jpg,
				picture-1152.jpg 1.5x,
				picture-1536.jpg 2x" />
	<source 
		media="(min-width: 768px)"
		sizes="33.3vw"
		srcset="picture-330.jpg,
				picture-495.jpg 1.5x,
				picture-660.jpg 2x" />
	<source 
		media="(min-width: 992px)"
		sizes="25vw"
		srcset="picture-300.jpg,
				picture-450.jpg 1.5x,
				picture-600.jpg 2x" />
	<source 
		media="(min-width: 1200px)"
		sizes="33.3vw"
		srcset="picture-600.jpg,
				picture-900.jpg 1.5x,
				picture-1200.jpg 2x" />
	<source 
		media="(min-width: 1800px)"
		sizes="33.3vw"
		srcset="picture-800.jpg,
				picture-1200.jpg 1.5x,
				picture-1600.jpg 2x" />
	<!--[if IE 9]></video><![endif]-->
	<img class="img-responsive" srcset="picture.jpg" />
</picture>
```

The problem is, that I always get the 600px image size, also after resizing the browser window to something smaller than 1200px. Is it because of a coding error in your js-lib or a wrong syntax in my html5-structure?

Thanks

**Comment by yoavweiss** [comment]
Your second source always matches. The source selection algorithm is a
first-match one, so (min-width: 300px) will catch all viewport that are
bigger than 300. (And the first rule would catch anything smaller).

Also, just to make sure, are you doing any art direction? If not, it's
highly recommended that you'd use srcset and sizes. (Which would also
significantly simplify your markup).

**Comment by Ninos** [comment]
Oh I thought all the sources after the min-width get a higher prio than the source before, if it also matches..
I changed it to following (works now):
```
<source 
		media="(max-width: 300px)"
		sizes="100vw"
		srcset="picture-300.jpg,
				picture-450.jpg 1.5x,
				picture-600.jpg 2x" />
	<source 
		media="(min-width: 301px) and (max-width: 600px)"
		sizes="100vw"
		srcset="picture-600.jpg,
				picture-900.jpg 1.5x,
				picture-1200.jpg 2x" />
	<source 
		media="(min-width: 601px) and (max-width: 768px)"
		sizes="100vw"
		srcset="picture-768.jpg,
				picture-1152.jpg 1.5x,
				picture-1536.jpg 2x" />
...
```

What do you mean with following:
> Also, just to make sure, are you doing any art direction? If not, it's highly recommended that you'd > use srcset and sizes. (Which would also significantly simplify your markup).

Big thanks! :)

**Comment by yoavweiss** [comment]
You can simplify it even further:
```   
   <source 
        media="(max-width: 300px)"
        srcset="picture-300.jpg,
                picture-450.jpg 1.5x,
                picture-600.jpg 2x" />
    <source 
        media="(max-width: 600px)"
        srcset="picture-600.jpg,
                picture-900.jpg 1.5x,
                picture-1200.jpg 2x" />
    <source 
        media="(max-width: 768px)"
        srcset="picture-768.jpg,
                picture-1152.jpg 1.5x,
                picture-1536.jpg 2x" />
```

My question was just meant to make sure you are using picture for art-directed images (e.g. serving crops on smaller viewport, using images with different proportions to fit the layout, etc).
If that's not the case, you're better off using srcset's w descriptor and sizes.

**Comment by Ninos** [comment]
No the dimensions of the images are the same, only the size is different. For a device with a size of 600px I don't want to load to original image with a size of 2000px for example. So you mean, that I should move the ```(max-width: *)``` to the ```sizes``` attribute?

Example code:
```
<source 
		sizes="(max-width: 300px) 100vw"
		srcset="picture-300.jpg 300w,
				picture-450.jpg 450w 1.5x,
				picture-600.jpg 600w 2x" />
	<source 
		sizes="(max-width: 600px) 100vw"
		srcset="picture-600.jpg 600w,
				picture-900.jpg 600w 1.5x,
				picture-1200.jpg 600w 2x" />
	<source 
		sizes="(max-width: 992px) 33.3vw"
		srcset="picture-330.jpg 330w,
				picture-495.jpg 330w 1.5x,
				picture-660.jpg 330w 2x" />
...
```

**Comment by aFarkas** [comment]
First of all sizes works with the w descriptor and does not allow to mix it with the x descriptor. In case all images are equal and only have different sizes you can do something like this:

```html
<img sizes="(min-width: 601px) 33vw, 100vw" 
   srcset="picture-300.jpg 300w, 
   picture-450.jpg 450w,
   picture-660.jpg 330w,
   picture-900.jpg 900w,
   picture-1200.jpg 1200w" />
```

Also note: That you must not generate soooo much images (There is no need to create a 330px and a 300px for example.)

**Comment by Ninos** [comment]
Thx, but I think here your example is not retina ready anymore? Also I have the problem, that on mobile devices the width of the image is 100vw and on desktop 1/3 of the viewport (3 columns).

**Comment by aFarkas** [comment]
The *w* descriptor already includes retina support automatically. The different size for desktop and mobile can be expressed using the ``sizes`` attribute: ``sizes="(min-width: 601px) 33vw, 100vw" ``.

**Comment by Ninos** [comment]
Ah ok thank you all for your help!! :-)
