### ISSUE TITLE
Picturefill 2 matchMedia Polyfill conflicting with enquire.js match Media Polyfill (IE9)

### ISSUE THREAD

**Issue by Quirksmode** [scottjehl/picturefill#417]
Hi, 

Unfortunately the Picturefill 2 matchMedia Polyfill is conflicting with enquire.js matchMedia Polyfill (IE9)

I get the following error:
Object doesn't support property or method 'addListener' enquire.js, line 152 character 9

Is there a way to get them to play nice?

**Comment by aFarkas** [comment]
Add this script https://github.com/paulirish/matchMedia.js/blob/master/matchMedia.addListener.js after picturefill and before enquire.js

**Comment by Quirksmode** [comment]
Thank you so much, the addListener worked brilliantly, I was able to remove the other matchMedia.js :-)
