### ISSUE TITLE
Create a 2.3.0 branch and roll back master to match what's on npm

### ISSUE THREAD

**Issue by mike-engel** [scottjehl/picturefill#420]
This would allow us to quickly patch minor bugs like the browserify thing that keeps cropping up without having to include new features. Once 2.3.0 is done, roll it into master.

**Comment by Wilto** [comment]
I like this idea. @scottjehl, wat’chu think?

**Comment by mike-engel** [comment]
Created a 2.3 branch (which can hold patches as well down the line. 2.3.0, 2.3.1, 2.3.2, etc).

Will be making the rollback tonight.

**Comment by mike-engel** [comment]
Made a 2.2 branch for now. At the moment, there are too many pull requests that go to master that need to be closed. We shouldn't accept any new PRs to master for the time being though, so we can finalize this issue.

**Comment by mike-engel** [comment]
Uh, right, this is done.
