### ISSUE TITLE
IE svgs width is changed to 0

### ISSUE THREAD

**Issue by wroughtec** [scottjehl/picturefill#430]
With the latest version 2.2 I have found when you use an svg the svg vanishes looking at the source the width is changed to 0 so nothing displays, works fine in chrome, ff etc.:

http://jsfiddle.net/xj404fo9/9/

Is it something I have done?

**Comment by Wilto** [comment]
We could use a little more information on this one: what version of IE? Also, is there any way you could include the SVG in question, just to make sure something in there isn’t tripping up the part of Picturefill that sets that width?

**Comment by wroughtec** [comment]
IE 11, 10 (maybe 9 but can only check in developer mode) * shows the png so thats not a problem

I have tried several svg and obviously used the app store svg for easy reach:
http://upload.wikimedia.org/wikipedia/commons/0/0f/Available_on_the_App_Store_%28black%29_SVG.svg

This did work on an older version of picture fill so this seems to be something that has been introduced

**Comment by aFarkas** [comment]
Thx, it was not happening in IE9. We can reproduce this now.

**Comment by aFarkas** [comment]
Sorry, I think I forgot to mark this issue as solved. The fix is already in 2.3.1. See: 
https://github.com/scottjehl/picturefill/blob/master/src/picturefill.js#L407-4124

It can be closed.
