### ISSUE TITLE
Examples not working in Chrome?

### ISSUE THREAD

**Issue by trygve-lie** [scottjehl/picturefill#435]
I'm testing out the examples shipped with this module and I'm having some problems getting them to work in latest-ish versions of Chrome.

Ex; this example: http://scottjehl.github.io/picturefill/examples/demo-01.html does not work in Chrome Version 40.0.2214.94. The extraLarge image is constantly loaded and changing the size of the browser does not affect the image.

Works in Chromium Version 39.0.2171.65, FireFox 35.0.1 and Opera 28.0.1750.11 (*nix developer version)

**Comment by aFarkas** [comment]
Are working quite well in Chrome. srcset means the browser chooses what is best. And in case the extra large image is already in cache Chrome won't load a smaller image.

**Comment by greypants** [comment]
Still broken on Chrome 40.0.2214.111 as well

**Comment by aFarkas** [comment]
@greypants 
Why do you think it is broken? Do you read my comment above? Maybe the source selection algorithm by Chrome is now simply so smart, that you can't predict the calculation/selection anymore.

**Comment by quoo** [comment]
I've investigated this as well, it seems on retina monitors Chrome is very aggressively loading the highest resolution image, down to the smallest width chrome will allow you to resize the browser to. If you emulate a smaller, non retina device (for example an iPhone 3GS) it will load the correct image.

**Comment by jegtnes** [comment]
Hey @greypants & @trygve-lie: I did some testing and can confirm what @quoo said—Chrome seems to be pushing high-density images where possible:

* On a 1x device, the small image is loaded at <=424px, the medium between 425 and 607px, and the extra large image is loaded at >=608px.
* On a 2x device, the small image is loaded at <=212px, the medium between 213 and 304px, and the extra large image is loaded at 305px.

The lowest size the native Chrome window will resize to is ~400px, hence you seeing the highest-res image at all times. Can you confirm whether this is the case as well? Chrome's device emulators let you switch density and set any resolution.

(Either way, this isn't a Picturefill bug per se, as Chrome 40 supports `srcset` natively, but maybe the examples could be updated with examples that'll demonstrate responsive images adequately when you just smush your browser with a 2x display.)

**Comment by greypants** [comment]
> srcset means the browser chooses what is best

@aFarkas Ah, yeah, my bad. That makes total sense now. Thanks. It's working exactly as you described. I misunderstood how `srcset` worked. If I start the browser small and do a hard, cache clearing refresh, the small images do load, but once you resize Chrome uses the highest resolution image in the cache after that for any width.

So I guess when I need to specifically load different images ad different breakpoints, the `<picture>` element is with `<source media="">` is the appropriate method here. Thanks.
