### ISSUE TITLE
Safari (8.0.3) briefly shows mobile image before serving correct image for breakpoint

### ISSUE THREAD

**Issue by aaronbushnell** [scottjehl/picturefill#438]
I'm running into an issue with the newest version of Safari (8.0.3). When I refresh the page the mobile image shows briefly, then the correct image loads shortly after.

![glitch](https://cloud.githubusercontent.com/assets/315202/6133823/b361cab8-b12a-11e4-976b-e32836821c2f.gif)

It doesn't seem to be problematic in Chrome or Firefox.

Using `Picturefill - v2.2.0 - 2014-10-30`
HTML:
```html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Demo Site</title>
  <link rel="stylesheet" href="styles.css">
  <script>
    document.createElement( "picture" );
  </script>
  <script src="/bower_components/picturefill/dist/picturefill.js" async></script>
</head>
<body>

...

<picture>
  <!--[if IE 9]><video style="display: none;"><![endif]-->
  <source srcset="large.jpg" media="(min-width: 1200px)">
  <!--[if IE 9]></video><![endif]-->
  <img class="header-image__img" srcset="small.jpg" alt="Image">
</picture>

...
```

**Comment by aFarkas** [comment]
Try this markup:

```html
<picture>
  <!--[if IE 9]><video style="display: none;"><![endif]-->
  <source srcset="large.jpg" media="(min-width: 1200px)">
  <source srcset="small.jpg" >
  <!--[if IE 9]></video><![endif]-->
  <img class="header-image__img" alt="Image">
</picture>

**Comment by aaronbushnell** [comment]
Works perfectly! Anything I should be concerned about if I make that my default Picturefill setup?

**Comment by aFarkas** [comment]
From behavior it is what you need and this syntax is futureproof .

The only thing you should know, that in a perfect world (1-2 years), you would write it differently:

```html
<picture>
  <!--[if IE 9]><video style="display: none;"><![endif]-->
  <source srcset="large.jpg" media="(min-width: 1200px)">
  <!--[if IE 9]></video><![endif]-->
  <img src="small.jpg" class="header-image__img" alt="Image">
</picture>
```

**Comment by aaronbushnell** [comment]
Understandable. Thanks for the quick help with this!

**Comment by baloneysandwiches** [comment]
So, in summary, it looks like the srcset needs to be removed from the fallback img in order to prevent a flash in current Safari. So should we change the docs to reflect this as best practice? I.E. all the actual images as `<source>`s with the `<img>` just doing duty as alt text, no `src` or `srcset` @aFarkas ?

**Comment by aFarkas** [comment]
+1 for this and I call it the mutilated img pattern.

**Comment by baloneysandwiches** [comment]
SGTM. It's totally invalid of course. But the FOWI™ (Flash of Wrong Image) is pretty unacceptable. Should we get this in sooner rather than later?

**Comment by aFarkas** [comment]
I think this should be documented. Additionally it should be also documented, that this pattern can also be used to prevent double downloads on iOS devices if normally only ``img[srcset][sizes]`` would be used.

Here is the pattern:
```html
<picture>
  <!--[if IE 9]><video style="display: none;"><![endif]-->
  <source srcset="large.jpg 1440w, small.jpg 960w" sizes="(max-width: 1280px) 100vw, 1280px">
  <!--[if IE 9]></video><![endif]-->
  <img alt="Pictured img without art direction">
</picture>
```

**Comment by baloneysandwiches** [comment]
Yep, but one issue with this pattern is that it causes no image to display to display in Android 2.3. It seems like there's no one markup pattern that covers all possible support scenarios. Meh. At the same time, the docs are already a bit verbose. It would be great to reduce the recommended markup patterns to a small numbered handful that we all agree on, write unit tests to match, and then make a simple chart with checkmarks so devs can see the pros and cons of each, and choose quickly.

**Comment by Wilto** [comment]
> It would be great to reduce the recommended markup patterns to a small numbered handful that we all agree on, write unit tests to match, and then make a simple chart with checkmarks so devs can see the pros and cons of each, and choose quickly.

_Nice_. Closing in favor of #536.
