### ISSUE TITLE
Post 2.2.1 to bower?

### ISSUE THREAD

**Issue by josephdburdick** [scottjehl/picturefill#441]
Hi, I understand that 2.2.1 has been pushed to NPM but what's holding it back from being pushed to Bower as well?

**Comment by aFarkas** [comment]
Actually we need to create a 2.2.1 tag for bower. But I invite you to work and test 2.3.0-beta which is coming soon (3,2,1...).

**Comment by josephdburdick** [comment]
Will do, thanks!
