### ISSUE TITLE
Running picturefill after pageload in ie8

### ISSUE THREAD

**Issue by badtant** [scottjehl/picturefill#443]
So, I have version 2.2.0 working good in every browser except ie8. In ie8 it picks the wrong image (which I can live with). Though I'm lazy loading images and when I run picturefill on those images later after pageload I get nothing.

window.picturefill({elements: $addedElement.find('.picturefill')});

**Comment by aFarkas** [comment]
Are you using the ``picture`` element?

**Comment by aFarkas** [comment]
In short: if yes try html5shiv.

**Comment by badtant** [comment]
yes, I'm using the picture element. I already have the html5shiv (v3.7 included in modernizr)

**Comment by badtant** [comment]
turns out that shiv is old and doesn't include the picture element. now loading 3.7.2 (but not from modernizr) and it does work. thanks for pointing in the right direction!
