### ISSUE TITLE
Feature Request: imitating Chrome behaviour for img with srcset

### ISSUE THREAD

**Issue by sven-tappert** [scottjehl/picturefill#444]
As mentioned before, the native implementation of image srcsets in Chrome does not switch back to low resolution sources on resizing, but always uses the highest resolution source that is available in cache. 

This behaviour is confusing at first, but seems to be really useful to save bandwidth. 

Would it be possible to imitate this behaviour in picturefill to prevent unnecessary loading of images on page load and while downsizing the browser window? Would be great if you could add this as an option (at least for testing and demo purposes it would be nice to be able to use current bevaviour).

**Comment by aFarkas** [comment]
We can't know for sure whether an image is already in cache. This information isn't available in JS/DOM. We could only make assumptions. But we will definitely add the feature, that we don't load lower resolution candidates on resize. Hopefully this might come in 2.4, but for sure it will come with 3.0.

**Comment by sven-tappert** [comment]
Thank you, this would be great and probably not too complex. I realised this behaviour in 2.2.0 with some changes in pf.applyBestCandidate(). A drawback is, that in some browsers some images render ugly if they are scaled down too much by css. So, as mentioned above, it could be helpful to provide user options to picturefill to disable this feature for testing or for other reasons. There might be other useful options then, e.g. to define maximum shrink rate, so low res images could be loaded if high res image is scaled down too much.

**Comment by mike-engel** [comment]
Just checking @aFarkas to make sure this got into 3.0 and _maybe_ 2.4.

**Comment by Wilto** [comment]
This squared away in 3.0, as it stands now?

**Comment by aFarkas** [comment]
Yes, it's done
