### ISSUE TITLE
RequireJS error in Safari and Firefox

### ISSUE THREAD

**Issue by mattkersley** [scottjehl/picturefill#446]
Hi, I've been sent here from https://wordpress.org/support/topic/error-in-safari-when-using-requirejs?replies=3#post-6641502.

I've run into an error when loading require.js in the `<head>` and picturefill just before the `</body>`.

The error (below) stops JS running in Safari, and shows an error in Firefox (but doesn't block it from running).

Is this something that can be resolved?

```
[Error] Error: Mismatched anonymous define() module: function () {return d;}
http://requirejs.org/docs/errors.html#mismatch
ca (require.js, line 8)
w (require.js, line 12)
J (require.js, line 15)
(anonymous function) (require.js, line 26)
```

**Comment by aFarkas** [comment]
Can you try the [2.3 beta version](https://github.com/scottjehl/picturefill/releases/tag/2.3.0-beta)?

**Comment by mattkersley** [comment]
no joy, now getting this:

```
[Error] Error: Mismatched anonymous define() module: function () { return picturefill; }
http://requirejs.org/docs/errors.html#mismatch
	ca (require.js, line 8)
	w (require.js, line 12)
	J (require.js, line 15)
	(anonymous function) (require.js, line 26)
```

**Comment by aFarkas** [comment]
Just looked into it, there was a merge error in 2.3. Will fix it.

**Comment by aFarkas** [comment]
Can you try the following version: https://rawgit.com/scottjehl/picturefill/2.3/dist/picturefill.js

**Comment by mattkersley** [comment]
We're back to the first error message in Safari I'm afraid :(
```
[Error] Error: Mismatched anonymous define() module: function () {return d;}
http://requirejs.org/docs/errors.html#mismatch
	ca (require.js, line 8)
	w (require.js, line 12)
	J (require.js, line 15)
	(anonymous function) (require.js, line 26)
```

Firefox is slightly different however:
```
Error: Mismatched anonymous define() module: function (){
"use strict";
return d}
http://requirejs.org/docs/errors.html#mismatch
```

**Comment by aFarkas** [comment]
@mattkersley 

Are you sure you have tested with the new version? Because in 2.3 picturefill is named (not anonymouse) and the [script](https://rawgit.com/scttjehl/picturefill/2.3/dist/picturefill.js), uses picturefill not d as variable.

**Comment by mattkersley** [comment]
![Image of facepalm](http://media.giphy.com/media/lmmPhmwEELuPC/giphy.gif)

My bad. All fixed.
