### ISSUE TITLE
Picturefill fails silently in FF 38

### ISSUE THREAD

**Issue by tessalt** [scottjehl/picturefill#447]
`<picture>` elements in Firefox 38 (nightly or developer edition) with multiple paths in image srcset don't seem to be showing up at all (displaying alt text). No JS errors. 

Tested with v2.2.0 and v2.3.0-beta

This could be a FF bug, as native picture/srcset support supposedly shipped with 38, so I guess picturefill isn't kicking in. I've yet to see evidence of this native support however :unamused: 

[picturefill demo-03](http://scottjehl.github.io/picturefill/examples/demo-03.html)
![screen shot 2015-03-04 at 12 30 00 pm](https://cloud.githubusercontent.com/assets/1789029/6489166/41715576-c26a-11e4-8910-78e54374fd20.png)

[shopify.com](http://www.shopify.com/)
![screen shot 2015-03-04 at 12 31 20 pm](https://cloud.githubusercontent.com/assets/1789029/6489197/7b8e6104-c26a-11e4-9e89-f0f91ef46021.png)

Other uses (`img` with `srcset`, `picture` with single path in `srcset`) are not updating on screen resize: 

[picturefill demo-01](http://scottjehl.github.io/picturefill/examples/demo-01.html)
![screen shot 2015-03-04 at 12 34 25 pm](https://cloud.githubusercontent.com/assets/1789029/6489242/d2a287c2-c26a-11e4-8a76-8f6b60b84171.png)

**Comment by scottjehl** [comment]
Thanks @tessalt

First thing I'd want to check is whether the result is any different when picturefill is not included in the page. If it's the same result, and another browser shows a better result with picturefill excluded, we could probably call it a Firefox bug.

**Comment by Wilto** [comment]
The lack of updating on screen resize is a known issue (this is an especially timely bug, in fact): https://bugzilla.mozilla.org/show_bug.cgi?id=1135812#c4

We’ll look into this right away!

**Comment by aFarkas** [comment]
@tessalt 
First about your shopify issue:
This is a FF bug. You can fix this by declaring the 1x descriptor in your srcset explicitly.

From spec a source candidate gets an implicit density of 1x if width and density descriptors are missing. FF seems to treat the hole list candidates as invalid as soon as you utilize this feature.

This means you can fix this by altering your code from:

```html
<img srcset="image-1x.jpg, image-2x.jpg 2x" />
```

To:

```html
<img srcset="image-1x.jpg 1x, image-2x.jpg 2x" />
```

But I hope this bug will be fixed before FF 38 becomes stable.

**Comment by tessalt** [comment]
@aFarkas big thanks! I'll keep an eye on the issue but that fix is :+1: :smile_cat:

**Comment by zcorpan** [comment]
What actually happens is that Firefox goes on to tokenize descriptors when the url ends in a comma.
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3438

Spec https://html.spec.whatwg.org/multipage/embedded-content.html#parse-a-srcset-attribute (step 8)

**Comment by Wilto** [comment]
Alright, we’ve filed some issues with Moz:

https://bugzilla.mozilla.org/show_bug.cgi?id=1139554
https://bugzilla.mozilla.org/show_bug.cgi?id=1139560

Thanks so much for reporting. Hopefully we can get this sorted out before `srcset` ships.
