### ISSUE TITLE
Errors in demo 1 documentation and code

### ISSUE THREAD

**Issue by bruceontheloose** [scottjehl/picturefill#448]
Thanks for all the great and ongoing work on Picturefill.

I noticed the "An img with 'srcset' and 'sizes' attributes" example on http://scottjehl.github.io/picturefill/ has an error in both the documented code (i.e., what's shown to readers) and the actual code (i.e., if you view source). Both list medium.jpg twice and omit at least extralarge.jpg:

```srcset="examples/images/medium.jpg 375w, examples/images/medium.jpg 480w, examples/images/large.jpg 768w"```

I believe the intention was for it to be:

```srcset="examples/images/medium.jpg 375w, examples/images/large.jpg 480w, examples/images/extralarge.jpg 768w"```

This matches the right resources with the corresponding `w` descriptors. (It also assumes, perhaps incorrectly, that you don't want to use small.jpg and change `375w` to `180w`, or include small.jpg in addition to the others.)

The standalone page (http://scottjehl.github.io/picturefill/examples/demo-01.html) for that same example appears to have a different error. The actual code used (if you view source) is:

```srcset="../examples/images/small.jpg 375w, ../examples/images/large.jpg 480w, ../examples/images/extralarge.jpg 768w"```

Replacing small.jpg with medium.jpg would make it match the `375w` value, and make it consistent with both the documented code on that page and the other changes I suggested.

Before I submit a PR for these, could you please confirm that the example should use medium.jpg, large.jpg, and extralarge.jpg, and not a different combination? (Such as using small.jpg instead of one of those or in addition to them.)

Thanks a lot.

**Comment by jegtnes** [comment]
Hey @bruceontheloose,

Thanks for reporting this! Very good spot. These examples are just that, examples—I don't think we necessarily need a small.jpg in all of them. I think all your suggestions make sense, and a PR would be greatly appreciated. :+1:

**Comment by bruceontheloose** [comment]
Hi @jegtnes,

You're welcome! Thanks for the note. I'll submit a PR that makes the corrections while omitting small.jpg.

- Bruce

**Comment by bruceontheloose** [comment]
Hi, @jegtnes (and other maintainers). Just a quick note that you may want to go ahead and close this since it was addressed in my PR (https://github.com/scottjehl/picturefill/pull/449), which has been merged. Thanks a lot.

**Comment by mike-engel** [comment]
Closing as this was merged in with #449. Thanks @bruceontheloose
