### ISSUE TITLE
IE11 adds width="0" on certain images on first page load

### ISSUE THREAD

**Issue by Chrisriis** [scottjehl/picturefill#453]
This thread should provide a good description of the problem: https://wordpress.org/support/topic/images-sometimes-not-loading-in-ie11

The thread's title is a bit misleading though, because the images are loaded, but width="0" makes the images not showing.

Note that it's working with v2.1.0 but not 2.2.0.

The little joker screws up again >.>
I just tested adding width="0" on an image in Chrome, and it didn't hide it so it's smarter than IE as expected…

**Comment by mike-engel** [comment]
@Chrisriis Just to be sure, have you tried this with the 2.3.0 beta? You can grab the files from the master branch of this repo.

**Comment by Chrisriis** [comment]
@mike-engel Unfortunately, I used a trial version of BrowserStack to test it yesterday and now it's expired (Mac user).
However, I'll probably test 2.3.0 tomorrow with Bootcamp and let you know!

**Comment by Wilto** [comment]
Hey @Chrisriis, any luck retesting? Looks like we have a fix in, so I’m gonna close for the time being—if you’re still having trouble with the latest on master, we’ll reopen.

**Comment by Chrisriis** [comment]
Hi @Wilto, sorry for the insane delay, but v. 2.3.0 works! Thanks :)
