### ISSUE TITLE
IE8+IE7 race condition leads to error when checking for webp support

### ISSUE THREAD

**Issue by antigirl** [scottjehl/picturefill#457]
The newest version of the code errors on older IE browsers.

If a browser doesn't have webp support the picturefill method is called too soon (it's triggered from detectTypeSupport when onerror is triggered creating the image). Error message is 

"Object doesn't support this property or method"

because getAllElements is not yet attached to the pf object.

We were further confused because the version number of the latest code is the same as working example found here...  http://scottjehl.github.io/picturefill/dist/picturefill.js

**Comment by christopherdarling** [comment]
We had the same issue with getAllElements and <= IE8, there's an issue here for it #450 with link to a fork that I created as a workaround
