### ISSUE TITLE
Images Not Displaying in IE

### ISSUE THREAD

**Issue by amykirst** [scottjehl/picturefill#458]
I've used picturefill to load a couple of images on my web page. They display correctly in Chrome but don't display at all in Internet Explorer 8.

Here is a sample of my code:

    <picture class="logo">
        
        <source srcset="images/logo.png" media="(min-width: 750px)">
        
        <img srcset="images/logo-small.png" alt="Baseball for Busy People">
    </picture> 

I can view the demo in IE 8: http://scottjehl.github.io/picturefill/examples/demo-02.html. But the images on my page aren't working.

Here is what I tried:

- I copied and pasted the code from the demo into my page (changing the image paths to absolute).
- I added script to create a element (just in case, but modernizr should cover it).
- I added a src path to the img tag, which worked, but I read that picturefill doesn't recommend this.

**Comment by mike-engel** [comment]
@amykirst Are there any page errors being reported from IE, or does the image just not show up?

**Comment by amykirst** [comment]
No errors. Only the alt text shows.

**Comment by amykirst** [comment]
It works if I replace the srcset in the fallback option with src. This also enables the HTML to validate. Is this a reasonable option or should I not do that?

    <picture class="logo">
        
        <source srcset="images/logo.png" media="(min-width: 750px)" >
        
        <img src="images/logo-small.png" alt="Baseball for Busy People">
    </picture>

**Comment by amykirst** [comment]
Changing srcset to IE is making the images load but now IE is only displaying the fallback image. Right now, I'm looking at IE 11.

**Comment by bruceontheloose** [comment]
Hi, @amykirst. Any chance your path to picturefill.min.js (or whichever file you're using) is incorrect? It works in Chrome because Chrome supports picture natively, as you may know. Is Picturefill working in Firefox?

Bruce

**Comment by amykirst** [comment]
Actually I had forgotten that Chrome supports it.

It isn't working in firefox either. I'm linking to picturefill.min.js. The file path matches my other files that are in the same folder.

When I open the site in Chrome, I do see an error in the console: 

![picturefill error](https://cloud.githubusercontent.com/assets/7563642/6701182/913077f6-ccef-11e4-9087-33180c47ddc0.png)

**Comment by bruceontheloose** [comment]
I think you might have the wrong code in picturefill.min.js. Does it work if you replace its contents with the JS shown at this URL?
https://raw.githubusercontent.com/scottjehl/picturefill/2.2.0/dist/picturefill.min.js

**Comment by amykirst** [comment]
When I open my file, it's an HTML document and not the js file. I had right-clicked the link and did a save-as instead of following the link to the code. Good catch. :)

It does work in Firefox now. My images still don't display in IE but that includes an image that doesn't use picturefill, so I think it's an IE issue. Maybe because I'm working off of a local file?

**Comment by sandeepPVV** [comment]
If images saved with .png extension are not displaying in IE. Then download the particular images which are displaying in chrome and convert the images to .jpeg using MS-paint and again convert the same images to .png using MS-paint. And now upload the images and then check.. It will work.
