### ISSUE TITLE
Srcset example not working?

### ISSUE THREAD

**Issue by XaviGIT** [scottjehl/picturefill#465]
Maybe I'm testing this the wrong way but it seems that srcset example is not working.
I'm on Chrome 41.0.2272.101 m for Windows 7.

Bellow what I'm seeing (notice I'm testing it for Nexus 4 and getting extra large version of the image):
![bug](https://cloud.githubusercontent.com/assets/370672/6783576/5ac29e88-d172-11e4-8028-3ec3e9b274db.jpg)

I tested for multiple devices and orientations and I'm always getting the same image (extra large).

**Comment by quoo** [comment]
This is Chrome's default behavior which supports srcset natively. If a larger image is cached, it will use that one instead of the image that is specified for that image size, especially if you are on a retina display.

**Comment by bruceontheloose** [comment]
@XaviGIT, as you may know, you can disable the cache in Chrome for testing by having Dev Tools open with "Disable cache" checked.

![chrome-devtools-disable-cache](https://cloud.githubusercontent.com/assets/1419972/6876203/6e94a7cc-d482-11e4-9924-83b1b9a43a10.jpg)

However, when using `srcset` like in that demo page, even with "Disable cache" set, Chrome will always use the image it loaded with the page load, no matter how narrow you make the browser after that. That's to prevent an unnecessary request for a smaller image. If you refresh the page with the browser still narrower, it'll load the image it deems appropriate, as expected.

Sorry if you know all this already. At the least, I thought it might be helpful to others who don't.

**Comment by zabatonni** [comment]
and thats why it didnt work for me :)
but in normal use-case its safe nobody has cached larger images on small screens.

**Comment by aFarkas** [comment]
@zabatonni 
And if it is cached, you don't want to download a non-cached lower image. Or do you?

**Comment by zabatonni** [comment]
@aFarkas nope, this behaviour is ok. No extra request to server.

**Comment by XaviGIT** [comment]
just as an update, it was cache "problems". thank you for the explanations @quoo and @bruceontheloose.
