### ISSUE TITLE
Having issues with picturefill and isotope…

### ISSUE THREAD

**Issue by albi** [scottjehl/picturefill#467]
Hi scottjehl,

having an issue with the method picturefill and Isotope (latest). Picturefill is running in the ``head`` and Isotope at the end (combined with other scripts). Even wrapping document ready around isotope won't layout all tiles properly. Some of them are displayed above others. Mostly at the end of the site.

Is there any callback to start the isotope layout after picturefill is done?

Example: … (removed)
Kind regards
Alex

**Comment by aFarkas** [comment]
I assume you are using imagesLoaded? In general imagesLoaded does not support responsive images. We have [multiple issues about this](https://github.com/scottjehl/picturefill/search?q=imagesLoaded&type=Issues&utf8=%E2%9C%93). 

Here is a simple [imagesLoaded jQuery plugin, that actually works with responsive images](https://gist.github.com/aFarkas/15de1cea3acd6602a71e).

But I would strongly discourage from actually using it. Waiting until all images are loaded until doing layout is so out of time (It is really bad practice!).

The best thing you can do is to use the CSS intrinsic pattern to solve your problem. Also picturefill does not need a ready event here. There is the browsers own event called ``onload``. To make things short, here is a similar question and the answer providing 3 solutions in [another repo, but heavily related to picturefill](https://github.com/aFarkas/lazysizes/issues/83#issuecomment-85628715).

**Comment by albi** [comment]
Hi aFarkas,

you are right. I will go with the intrinsic pattern! That should solve my problems and is a modern approach.

Kind regards
Alex
