### ISSUE TITLE
Adding additional type tests fails on picture-supporting browsers

### ISSUE THREAD

**Issue by luzat** [scottjehl/picturefill#486]
Currently support for additional image formats is added like:

    var pf = w.picturefill;
    pf._.types[ "…" ] = pf._.detectTypeSupport(…);

This fails if the browser supports the `picture` element, because in that case `pf._` is not defined (`w.picturefill` is just `function () { }` in that case). An easy fix is preceding those lines with

    if (pf._)

This avoids any additional work.

**Comment by aFarkas** [comment]
You are absolutely right, thanks.

**Comment by aFarkas** [comment]
This is fixed in 3.0.
