### ISSUE TITLE
iOS safari sporadically removes retina images

### ISSUE THREAD

**Issue by LucAwater** [scottjehl/picturefill#488]
I'm using the picturefill method with the wp retina plugin. Often in iOS safari, one or more images do not get displayed. Instead, there will be a blank white box with a grey border. It happens sporadically and only in iOS safari. I've tested in chrome on iOS and that worked perfectly! Does anyone have any idea what it could be?

Thanks!

**Comment by aFarkas** [comment]
We would need a testlink.

**Comment by LucAwater** [comment]
http://parfumsparen.woc-dev.nl

**Comment by aFarkas** [comment]
You are not using picturefill on this site. You are using the following script: http://parfumsparen.woc-dev.nl/content/plugins/wp-retina-2x/js/retina.min.js?ver=1.3.0

**Comment by LucAwater** [comment]
Yes, that is the plugin i'm using. This plugin is using the picturefill method

**Comment by aFarkas** [comment]
No, not really. wp-retina comes with different optional scripts, one of them is picturefill, in your case, it does not load picturefill, but it loads *retina.js*. Check your wp retina options. If picturefill is checked and not retina.js, then report back to the wp-plugin author with the informations here. He will understand.

**Comment by LucAwater** [comment]
That is some weird shit. I had picturefill enabled. I have re-saved it now and it seems to be working. Could you check again which method it loads? How do you check that?

**Comment by aFarkas** [comment]
You can check your own: Open your dev tools and enter ``picturefill`` into your console. If it is there you are lucky.
