### ISSUE TITLE
Picturefill 3.0.0 Alpha

### ISSUE THREAD

**Issue by Wilto** [scottjehl/picturefill#492]
What do we think?

**Comment by jefflembeck** [comment]
From what I understand:

better tests, better perf, much closer to native

That sounds like a big :+1:

**Comment by Wilto** [comment]
The short version is: major performance improvements (@afarkas, you have some test results here, yeah?), way closer to native behavior (use largest image in cache instead of requesting smaller sources with `srcset`, for example), better parsers, and better test coverage.

**Comment by jefflembeck** [comment]
Faster, more accurate, and better tested? Into it.

**Comment by aFarkas** [comment]
This would be so awesome. I just re-added the umd pattern and the git ignored compiled files. So everything should be good to go from my view. Should I [remove the debug code](https://github.com/scottjehl/picturefill/issues/491) before we tag/release the alpha?

**Comment by aFarkas** [comment]
About the performance thing, for runtime: it's mainly about scalability. In case of a website with a few DOM elements and very few respimages, you won't see much impact. In case of either complex CSS/DOM or a lot of responsive images, you will see a big performance improvement, due to reduced layout trashing and some sizes memoization and other things. 

There are also some network things.

**Comment by yoshuawuyts** [comment]
Neat! Not sure if this project is following [semver](http://semver.org/), but if it is: are there any breaking changes that warrant a major version bump?

**Comment by aFarkas** [comment]
@yoshuawuyts 
https://github.com/scottjehl/picturefill/blob/master/CONTRIBUTING.md#versioning

**Comment by Wilto** [comment]
Yeah; I figure our semver rules are a little different. If we had a major breaking change in a polyfill, something has gone horribly wrong somewhere.

**Comment by Wilto** [comment]
@aFarkas I’d scratch the debug code first, if we can easily move it to a plugin.

**Comment by yoshuawuyts** [comment]
@Wilto Ideally that'd be true, however the webcomponent spec has had at least [one major change](https://github.com/requireio/custom-element/commit/03156f29d083c7ac37815083b377ce15faab04ce) (`document.register -> document.registerElement`) so it's not unheard of specs changing.

**Comment by Wilto** [comment]
Yeah, but we’ve been keeping up with spec-and-real-implementation changes on the fly so far. I mean, we kinda get to cheat there, where we’re _extremely_ tuned-in to changes in native implementations. I wouldn’t want to hold for a major release process if we’re addressing a bug that keeps Picturefill in sync with reality, y’know?

I do want to keep Picturefill 3 out of the usual upgrade process, though, since it’s a _huge_ code overhaul. The 2.Xes works pretty damn well, so I have no qualms about people staying on there for a while—I think I’d rather have a big change like this be an opt-in.

**Comment by julzmon** [comment]
I'm getting the following error when trying to view in IE8 and IE9 through modern.ie Win7.

    HTML1201: github.io is a website you've added to Compatibility View. 
    picturefill
    SCRIPT438: Object doesn't support property or method 'querySelectorAll' 
    picturefill.js, line 1004 character 3

**Comment by wiesys** [comment]
Should we still use IE 9 workaround with <video> tag in 3.0?

**Comment by aFarkas** [comment]
@wiesys 
There is no way around to use the ``<video style="display: none;">`` workaround to support IE9.

Fun fact: pf 3.0 now also supports the shorter version ``<audio>`` of this workaround.
