### ISSUE TITLE
Error Reports

### ISSUE THREAD

**Issue by di5abled** [scottjehl/picturefill#493]
Hello,

we currently use picturefill in an live project and have error tracking for my JavaScript. We see 2 errors popping up from time to time which I want to share with you. Maybe you are already aware of this errors or know how to tackle them. 

We installed picturefill via Bower using version `^2.3.*`

Only in FF mostly on Windows: `TypeError: a.matchMedia(...) is null`
```
bower_components/picturefill/dist/picturefill.min.js:4:2339g.matchesMedia
bower_components/picturefill/dist/picturefill.min.js:4:7379g.getMatch
bower_components/picturefill/dist/picturefill.min.js:4:1132e
bower_components/picturefill/dist/picturefill.min.js:4:1687f/d<
```

In FF and Chrome on Windows & Mac: `TypeError: setting a property that has only a getter`
```
bower_components/picturefill/dist/picturefill.min.js:4:6424g.applyBestCandidate
bower_components/picturefill/dist/picturefill.min.js:4:1314e
bower_components/picturefill/dist/picturefill.min.js:4:1687f/d<
```

**Comment by jegtnes** [comment]
Hey there @di5abled,

Thank you for reporting this, we appreciate it. Can you provide us with example code that trigger these errors so we can investigate further?

**Comment by aFarkas** [comment]
@di5abled 
Could you also test give us stack traces with unminified files and confirm, that you are using version 2.3.1  (we just fixed an issue with a readonly property in 2.3.1). 

And can you check whether you do create any hidden iframes. (see also https://bugzilla.mozilla.org/show_bug.cgi?id=1011330).

In our 3.0 proposal we have a more [accurate test for this FF quirk](https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/picturefill.js#L974).

**Comment by di5abled** [comment]
Hello,

I saw the version which is installed is `2.3.0`.
I now update to the newest version will include the unminified files to help you debug this issues if they are still there. 

I don't think i have hidden iFrames, this is a really simple micro site.

thanks for your help!

**Comment by di5abled** [comment]
Hy,

one error occured again: `TypeError: a.matchMedia(...) is null`

bower_components/picturefill/dist/picturefill.js:127:2    g.matchesMedia
bower_components/picturefill/dist/picturefill.js:600:11  g.getMatch
bower_components/picturefill/dist/picturefill.js:658:4    picturefill
bower_components/picturefill/dist/picturefill.js:705:3    f/f<

**Comment by aFarkas** [comment]
@di5abled 
Yeah, we only check for ``matchMedia`` existence pf 2.3.x. We have an extended test in [3.0](https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/dist/picturefill.js). Due to the fact, that I can't replicate this issue. I would like to know, whether this error is gone with the 3.0 version???

**Comment by di5abled** [comment]
I can test the 3.0 version if you want. 
Which code should I use for this? The branch that you linked in your reply @aFarkas ?
Or can I install the 3.0 version via bower in any way?

**Comment by aFarkas** [comment]
Currently you need to install it manually. The 3.0 is good but from versioning it is in an alpha state.

**Comment by di5abled** [comment]
I'll test version 3 in our next project and come back to you if the error is still there. 
good to hear that you already aware of this problem!
thanks for your feedback, I'll close this for now

**Comment by aFarkas** [comment]
I really would need a positive confirmation, that it is working.

**Comment by di5abled** [comment]
ok, I'll try your 3.0.0-alpha1 tag on two projects which go live this week :)

**Comment by aFarkas** [comment]
Thanks!!!

**Comment by Wilto** [comment]
Really appreciate that, @di5abled—we need all the testing we can get.

**Comment by di5abled** [comment]
Hello all, 

I haven't one bug report in the new projects until now (1 week) and this new applications have a hight amount of different users due to marketing ;)

I think you can close this issue, if I'll encounter any other problems I'll come back and will share it with you!

Thanks for the great work :+1:

**Comment by jegtnes** [comment]
Glad to see the 3.0 alpha is working well for you, @di5abled :) Thanks a lot for your feedback, we appreciate it a ton. If anything else come up, feel free to raise an issue again!
