### ISSUE TITLE
Tuning up the docs page in time for the Picturefill 3.0.0 pre-pre-pre alpha

### ISSUE THREAD

**Issue by Wilto** [scottjehl/picturefill#495]
I want to do some serious reorganization on this page, but this is the overall vibe. Bunch of stuff missing, which I’ll just kind of wing as I put it together. Image is maybe FPO, but I kinda like the idea of shouting-out the images that’ve been with Picturefill since day one.

![pf3-site](https://cloud.githubusercontent.com/assets/439942/7502151/dd07030e-f407-11e4-919f-383eeccd2989.jpg)

**Comment by Wilto** [comment]
Alternate footer courtesy of @isaacdurazo:

 ![](https://photos-6.dropbox.com/t/2/AAAb360oLiHu8zhVb0Q59GGzF84vFpuLIMT5JN1DFu2h_A/12/4131629/png/1024x768/3/1431018000/0/2/Screenshot%202015-05-07%2008.38.54.png/CK2W_AEgASACIAMgBCAFKAEoAg/pC9HI4G4uyfVu3pXlaFsczvA6GJ78aQDdeGHkeCkj-A)

**Comment by mike-engel** [comment]
How's this goin' @wilto? Need any help with this?

**Comment by Wilto** [comment]
Finally have a chance to dig into it today.
