### ISSUE TITLE
picturefill with slick slider?

### ISSUE THREAD

**Issue by kevadamson** [scottjehl/picturefill#496]
I have a site that is using http://kenwheeler.github.io/slick/

It has a lazyload option where you set <addr>lazyLoad: 'ondemand'</addr> in the JS options and add <addr>data-lazy="whatever.jpg"</addr> instead of <addr>src</addr> on each<addr> img</addr> tag.

picturefill does its thing with the first image, but then the next image that (either auto or by button click) slides into view isn't the correct image based on the <addr>sizes</addr> set. If you resize the window even a tad when a new image is in view picturefill kicks in.

Is there any way of adding some extra JS so that picturefill "has a sniff" when another image is displayed by the slider?

Thanks :)

**Comment by jegtnes** [comment]
Hey @kevadamson,

It looks like Slick has event handlers, so you could for example listen to 'beforeChange' and run the picturefill() function once that happens. For more information on this, check out the docs: 

http://scottjehl.github.io/picturefill/#api

This may be a bit wonky depending on how Slick's lazy loading works, you may have to play around to find the first event handler that runs after the next image has been lazy-loaded.

Hope that helps!

**Comment by kevadamson** [comment]
@jegtnes Excellent many thanks. I owe you a pint. And if it works I owe you several :)

**Comment by kevadamson** [comment]
This is how I sorted it:

<code>$('.your-slick-slider-class').on('afterChange', function(event, slick, currentSlide){

    picturefill({
        reevaluate: true
    });

});</code>

**Comment by jegtnes** [comment]
Glad it worked for you! If you ever find yourself in Bristol, UK, I'll happily accept those beverages. :)
