### ISSUE TITLE
Cleanup source selection for pf 3.0 alpha

### ISSUE THREAD

**Issue by aFarkas** [scottjehl/picturefill#497]
Before we can release pf 3.0-alpha-2, we need to do some cleanup tasks. One thing is the source selection.

I would like to implement a [similar algorithm like this one](http://jsfiddle.net/trixta/9dponzs2/). Or at least something that produces similar results.

As we know using always a mean, can result in bad results especially on low resolution displays. This is also the reason why Chrome dropped the mean approach for devices <= 1x.

I would like to take the chance to not follow Chrome's implementation and experiment by using a different approach.

The algorithm above uses a modified arithmetic mean approach. The modification is mainly based on the density of the lower resolution candidate (as an absolute indicator of image quality) and only slightly on the target resolution of the device. 

I think this best describes, what we see. If the resolution of the lower res image is already "high", it makes sense to go for less data and take this candidate. If the resolution is low it might be better to take the higher candidate.

**Comment by aFarkas** [comment]
ping @Wilto @yoavweiss @zcorpan @baloneysandwiches

**Comment by yoavweiss** [comment]
Depending on where you want picturefill to go, that would be a valid approach (picturefill is an implementor, so it can have leeway here to experiment).

The main questions that I would ask are:
* Do we want picturefill to be an experimentation lab?
* How will we collect results from these experiments?

I'd still love to have some science behind that, so we can quantify the algorithm's quality/bytesize tradeoff, but I guess that's orthogonal.

**Comment by aFarkas** [comment]
> I'd still love to have some science behind that, so we can quantify the algorithm's quality/bytesize tradeoff, but I guess that's orthogonal.

Me, too badly.

> How will we collect results from these experiments?

We all are actually pf users so by using a different algorithm, we all constantly see how the algorithms differ and can judge, wether it is good or bad.

Additionally pf is clearly a quite often used polyfill, as soon as things go wrong people will come here and complain.

The last thing might sound not so big, but I want to remember, that the last change in source selection in chrome had it's [origin from this issue](https://github.com/aFarkas/lazysizes/issues/51#issuecomment-72914248).

Additionally the current situation isn't clear. FF has a different source selection implementation than Chrome. Since September Chrome had at least 2 changes in the source selection. And correct me if I'm wrong, but the [last change](https://codereview.chromium.org/1045353002/patch/1/10001) seemed to be a quick fix with the intent to refactor later as soon as we have more knowledge.

Which source selection should we take at this point? Should we take FF implementations, which is equal to Chrome's first one? Or should we take Chrome's current one, which seems unfinished.

Wouldn't it be good for @yoavweiss to know how this alternative approach is working in the wild and maybe build on the strength or learn from the weakness of it? 

The current situation actually tells me, we need diversity to learn from.

**Comment by aFarkas** [comment]
What about this modification??

```
if (((currentDensity <= 1.25) && (deviceScaleFactor > currentDensity)) || (deviceScaleFactor >= geometricMean))
```

**Comment by aFarkas** [comment]
As from discussion or absent of it. It seems we won't come to an agreement with one source selection.

What about the following compromise:
pf 3.0 has already a small config system.
We could basically implement two or three different source selection algorithms:

1. "default" (which is basically Chrome current implementation)
2. "edge"/"experimental" (the implementation I want to get in)
3. "quality" (the old implementation of pf, just in case someone still wants this (me don't))

This way we ship with the exact same implementation of chrome.

And at least for me it is really important to have the possibility to switch to "edge", because I really believe in its usefulness. And I won't like pf3.0, if it isn't in. (If you guys want we can also rename "edge" into "alex").

So everyone get's what he wants ;-).

So +1 means we add 2 different implementations (defaults to chrome's one) and -1 means only chrome implementation without the possibility to change.

re-ping: @yoavweiss , @Wilto , @zcorpan , @baloneysandwiches , @scottjehl , @jegtnes , @mike-engel , @quoo + the rest of the core team

**Comment by yoavweiss** [comment]
I'm OK with that as long as we'd be careful to ship by default a conservative polyfill, rather than an experimental playground.

**Comment by baloneysandwiches** [comment]
SGTM. Any experimental algo should come with an well-marked option to revert to something like Chrome current. Three options might be cognitive overload. How about two?

Just to summarize, my understanding is that the main scenarios to solve for are:

- Don't waste data downloading massive images on 3 and 4 dppx devices. There's no optical improvement. Weight towards smaller images in these cases.
- Don't select slightly too small images on 1x devices, because they can look awful. Weight the mean towards larger images in these cases.
- Full screen images on large hi dppx monitors still often need to get giant files. This might be a special case. It can *really* depend on the image. This is a tricky one.

Is this a correct summary? If not can you add to this? Design doc? :) If a revised algorithm solves these three scenarios better than other current implementations I am for it. Let's give the options working names. How about "Chromey" and "WeightedArithmetic" or something like that?

**Comment by aFarkas** [comment]
> Three options might be cognitive overload. How about two?
Yep.

> my understanding is that the main scenarios to solve for are

For the first two points yes. The third isn't handled different.
I updated the [source selection demo](http://jsfiddle.net/trixta/9dponzs2/) to also show Chrome's computation.

**Comment by aFarkas** [comment]
I will try to put something together until Sunday.

**Comment by Wilto** [comment]
Alright, cool. I’m good with having an opt-in for the experimental algorithm, so long as we’re defaulting to something close to what Chrome is using right now (or that the majority is using, should things stabilize in some other way).

My only concern now is potential maintenance overhead; additional tests and such.

**Comment by aFarkas** [comment]
@Wilto 
You shouldn't really. the code needed is pretty simple. The final function for both the experimental and the default algorithm could look like this:

```js
function takeLowRes(lowerValue, higherValue, dprValue, isCached){
	var bonusFactor, tooMuch, bonus, meanDensity;

	//experimental
	if(/^edge|experimental$/.test(cfg.algo || '')){
		tooMuch = higherValue - dprValue;
		bonusFactor = Math.pow(lowerValue - 0.6, 1.5);

		bonus = tooMuch * bonusFactor;

		if (isCached) {
			bonus += 0.1 * bonusFactor;
		}

		meanDensity = lowerValue + bonus;
	} else {
		meanDensity = (dprValue > 1) ?
				Math.sqrt(lowerValue * higherValue) :
				lowerValue;
	}

	return meanDensity > dprValue;
}
```

Which also implements the exact current version of Chrome's algorithm. 

I will simply do a PR on this and we will see?

One part that might be already now "changeable" in Chrome is the following line:

```
meanDensity = (dprValue > 1) ?
````

into something like this:

```
meanDensity = (lowerValue > 1.2) ?
```

Reason: This part is not for performance (on 3x and 4x devices), but for more quality on low/middle resolution devices. (So you will not have complains about bad quality and such). Currently the mean algorithm is disabled for 1x (and lower devices), but there is also the possibility, that 1.5x devices could load too bad quality images (i.e.: images below 1.2x). With this change the "mean-modificator" is based on the resolution of the lower image candidate and not the resolution of the device itself. This way it solves the problem of low resolution images on all devices not only on 1x devices.

**Comment by baloneysandwiches** [comment]
I think we need a specific list of named use scenarios to solve for. Agreed that the 1.5 case should be added in to the two above.

Real world visual tests would also go a long way here. We've all seen 300px images stretched over 320px and they look terrible. Switching to the higher src should in general be weighted up. I'm not sure that 1x should be handled as a special case. Another possible strategy: perhaps dppx could just be clamped internally at somewhere around 2, to address the data issue?

**Comment by aFarkas** [comment]
@baloneysandwiches 

> perhaps dppx could just be clamped internally at somewhere around 2, to address the data issue?

While I like this idea: This would basically say, that there is no value to buy a 3x/4x device.

I actually regret that I somehow restarted the discussion again (Reopened pandoras box). Basically we all want the smartest algorithm and we want it to be in the browsers and not just the polyfill. And improving the algorithm without more experience/data won't get us there.

If we would build a tool, that takes a set of images and allows to constrain the resolution so that we can compare the different restricted resolutions with the full resolution image in quality and filesize and then work based on this data would maybe help more. But it might be time for more research. (You can look at this [thing](http://afarkas.github.io/lazysizes/optimumx/), if you want.)

**Comment by baloneysandwiches** [comment]
perhaps dppx could just be clamped internally at somewhere around 2, to address the data issue?

>While I like this idea: This would basically say, that there is no value to buy a 3x/4x device.

Well, 4x buyers still get gorgeous line drawing: thin type, ultra-smooth rounded corners, etc.

**Comment by Wilto** [comment]
Locking things down to 1x/2x has come up a couple times (with Picturefill and with the spec), and I am extremely not into it. I _absolutely_ agree that I’d rather see bandwidth saved over a quality difference that might not even be perceptible to the human eye, but we don’t know how things are gonna play out five years from now. Locking things down to 1x/2x feels a little “640K ought to be enough for anybody.”

Now, I don’t know how things might change to the extent where we’d have to back out that kind of restriction, but that’s sorta why I wouldn’t want it in the first place—we don’t know.

**Comment by mike-engel** [comment]
Linking meta density issue #325.
