### ISSUE TITLE
Images with max-height in vh are stretched in IE and Safari

### ISSUE THREAD

**Issue by FlorianBrinkmann** [scottjehl/picturefill#502]
Hi!

I have the following problem:
I want to display images with a max-height of 80vh and a max-width of 82vw. It works fine in Firefox but in IE and Safari the images are stretched (here a Pen where you can see it: http://codepen.io/anon/pen/oXzOJe). The browsers stretch them over the 82vw.

In Firefox
![firefox](https://cloud.githubusercontent.com/assets/2310924/7793577/e83a54d4-02c0-11e5-81a6-6de6af7f349b.PNG)

In Internex Explorer 11
![internet-explorer](https://cloud.githubusercontent.com/assets/2310924/7793578/e83f3224-02c0-11e5-8df3-fd6c141e6e7c.PNG)

I really want to use Picturefill for this project, because it's a site for a photographer and the images should be really big on large viewports ...
Has anybody an idea why it looks that way in IE and Safari? And is there a fix for that?

Thanks in advance!

**Comment by aFarkas** [comment]
You can fix this by adding the following CSS:

```css
img { width: auto; }
```

But it also means, that your ``sizes`` attribute is wrong, which does not only hurt IE11, but also every browser (Chrome/FF).

There is in general no way to do height based source selection, but in case the height of the image can be approximately expressed in ``vh`` units, there is a possible workaroung. Read more here:
http://stackoverflow.com/questions/29778235/can-i-use-picture-for-both-height-and-width-constrained-images

(In case you use a 100% right sizes attribute, you won't need to add the CSS.)

**Comment by FlorianBrinkmann** [comment]
width:auto – that was easy :D Thanks a lot for your quick reply!

**Comment by dineshvg** [comment]
width auto still keeps it big ??

**Comment by FlorianBrinkmann** [comment]
Safari on Windows 10? It‘s not the same bug, but it looks strange ...

**Comment by SystemDZ** [comment]
Try this:
Parent has display:flex
Child has align-self:center
**Solution: https://codepen.io/SystemDZ/pen/WNGMaQV**
