### ISSUE TITLE
firefox 38 breaks demo

### ISSUE THREAD

**Issue by joernroeder** [scottjehl/picturefill#505]
The following demo doesn't work in my latest firefox 38.0.1. I know that firefox supports the `<picture>` element natively, so maybe it's a markup issue.

https://scottjehl.github.io/picturefill/examples/demo-02.html

**Comment by joernroeder** [comment]
see #447 and https://bugzilla.mozilla.org/show_bug.cgi?id=1135812

**Comment by mike-engel** [comment]
@joernroeder, if this is about the picture not resizing, I'm going to close with one out as a dup of #447, which was also closed. It seems like, according to @aFarkas, that the solution is pretty simple:

```
About your shopify issue:
This is a FF bug. You can fix this by declaring the 1x descriptor in your srcset explicitly.

From spec a source candidate gets an implicit density of 1x if width and density descriptors are missing. FF seems to treat the hole list candidates as invalid as soon as you utilize this feature.  

This means you can fix this by altering your code from:
<img srcset="image-1x.jpg, image-2x.jpg 2x" /> 

To:
<img srcset="image-1x.jpg 1x, image-2x.jpg 2x" />

But I hope this bug will be fixed before FF 38 becomes stable.
```

If you're trying to reference another issue with the demo, please let us know.
