### ISSUE TITLE
Responsive behaviors no longer working on AJAX content in browsers that support <picture>

### ISSUE THREAD

**Issue by amaschas** [scottjehl/picturefill#506]
Browsers that support that `picture` element do not appear to support the responsive behaviors in AJAX content natively. Manually invoking "picturefill();" post-AJAX load does nothing, because picturefill detects browser support and exits.

**Comment by mike-engel** [comment]
@amaschas Just co clarify, when you say responsive behaviors in AJAX content, do you mean images loaded with a single page application and are styled responsively with CSS?

**Comment by amaschas** [comment]
@mike-engel I just figured out that the responsive behaviors were failing because the <img> tag was being placed first inside the <picture> element, rather than last, which was invalid markup, so this is actually working as expected. Sorry for bugging you, and thanks for your prompt reply (and all your work on picturefill).
