### ISSUE TITLE
Mac Safari and Chrome Not Rendering Specific Image on Viewport Resize

### ISSUE THREAD

**Issue by andrewlawton** [scottjehl/picturefill#507]
Replicating Chris Coyier's code pen (http://codepen.io/chriscoyier/pen/reFLJ) using version 2.3.1 I experience the following issues. See code pen below:

Issues:
Using Safari the small image is only rendered on viewport resize. Using Chrome the large image is only rendered on viewport resize.

Configuration
MacBook Pro
Safari: 8.0.3 (10600.3.18)
Chrome: 43.0.2357.81 (64-bit)

Code Pen Example
http://codepen.io/andrewlawton/pen/wagLbz

**Comment by mike-engel** [comment]
@andrewlawton I'm guessing this is a codepen issue, since picturefill doesn't even run on chrome since it supports the `picture` element natively. Is this the only place you see this issue?

**Comment by aFarkas** [comment]
Safari:
Picturefill isn't added right:
**[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (picturefill.min.js", line 0)**

Chrome:
The ``sizes`` attribute is invalid. It therefore defaults to ``100vw``. Additionally as soon as the large image is in cache, Chrome will never waste/load another resource.

Everything looks as expected.

**Comment by mike-engel** [comment]
Closing this issue as the codepen is demonstrating proper behavior. Thanks @aFarkas and @andrewlawton

**Comment by andrewlawton** [comment]
I just wanted to say thank you very much @mike-engel and @aFarkas and for checking into my non-issue. Sorry to have wasted your time! I am new to using picturefill and wasn’t aware of code pens limitations with respect to Chrome. I have the latest version working locally now : ) Keep up the great work!

**Comment by aFarkas** [comment]
@andrewlawton 
absolutely no problem. in case this is famous pen, you could ping chris for us :-).
