### ISSUE TITLE
Picturefill does nothing in Firefox 38, even if srcset support is deactived in about:config

### ISSUE THREAD

**Issue by JostBaron** [scottjehl/picturefill#509]
Srcset support is now activated by default in FF 38. Switching that support off does not trigger picturefill to do the work, fallback images are shown instead.

**Comment by Wilto** [comment]
_That’s_ interesting. The support test passes—I mean, it is supported—but then `srcset` doesn’t work.

I wonder if we _should_ be working around this, though? If `srcset` is deliberately deactivated by the user, we might not want Picturefill to kick in.

**Comment by mike-engel** [comment]
I'm gonna side with @wilto here. @JostBaron is there a good use case for turning off support for srcset through the firefox config?

**Comment by aFarkas** [comment]
Additionally, why do you turn ``srcset`` off and let ``picture`` enabled? I don't think we should support this. (We should support it the other way around ``picture`` disabled and ``srcset`` enabled, but I think we already do).

**Comment by thisispete** [comment]
in FF38 I see the image load at the wrong dimensions, then after a second it re-sizes. I haven't noticed this in other browsers. Any ideas if this is related to the changes in v38?

**Comment by TrialsmanDMTB** [comment]
I think JostBaron means that picturefill does not work in FF 38.  And then JostBaron tried turning off srcset to see if that would help, and it didn't.  Picturefill does not work on my computer with FF 38.  Works fine in other browsers.

**Comment by TrialsmanDMTB** [comment]
Update:
In IE, the act of resizing the browser reloads the image being viewed.  Drag the browser window to a new size, pause, and the image reloads.  In FF 38, resizing the browser has no affect... UNTIL you reload the page manually.  Then a different image size will load.
Ultimately, this is likely the intended function of the script.  Upon loading, screen size determines the image loaded.
Thank you!  This is the solution I was looking for!

**Comment by JostBaron** [comment]
@TrialsmanDMTB Actually, the Firefox behavior is a bug: The image must be reloaded on resize. Here's the bugreport: https://bugzilla.mozilla.org/show_bug.cgi?id=1166138

**Comment by aFarkas** [comment]
@JostBaron 

But you have still picture enabled, right?

``picturefill`` does work with ``picture`` disabled and ``srcset`` disabled as also with both disabled, but setting ``srcset`` disabled and not having ``picture`` disabled, doesn't make sense.

Picture is an "extension" to ``srcset``.

**Comment by JostBaron** [comment]
@aFarkas Exactly, I had `picture` still enabled.

But why doesn't it make sense to have `srcset` disabled, but `picture` enabled? If the latter is an extension of the first, shouldn't it be considered deactivated, too? Even if it is not done explicitely.

The other thing is that I didn't know that there are two settings.

**Comment by aFarkas** [comment]
> why doesn't it make sense to have srcset disabled, but picture enabled

The picture element is only a wrapper element to control and associate multiple ``source`` elements with the ``img`` element. These ``source`` elements use the ``srcset`` attribute.

As you see as soon as ``srcset``does not work ``picture`` can't work either.

Changing the config in FF can always cause errors. You need to know what you are doing.

> shouldn't it be considered deactivated, too? Even if it is not done explicitely.

This you should ask Mozilla.

**Comment by aFarkas** [comment]
I think we can close this, we do fix the static handling of ``picture`` and ``srcset`` in FF 38+ with pf 3.0 and we support FF with ``picture`` disabled or with ``picture`` and ``srcset`` disabled.
