### ISSUE TITLE
Images aren't switched on resize in Firefox 38.0.5

### ISSUE THREAD

**Issue by sgromskiy** [scottjehl/picturefill#513]
[live demo] (http://scottjehl.github.io/picturefill/examples/demo-04.html)
or is it FF's issues?

**Comment by jegtnes** [comment]
Hey @sgromskiy,

Thanks for reporting this—and it's indeed the Firefox bug. See https://github.com/scottjehl/picturefill/issues/512#issuecomment-109796715 for more info.
