### ISSUE TITLE
optimize debounce pattern in pf 3.0

### ISSUE THREAD

**Issue by aFarkas** [scottjehl/picturefill#514]
See discussion [here](https://github.com/scottjehl/picturefill/issues/512#issuecomment-110435195)

**Comment by aFarkas** [comment]
@baloneysandwiches 
Do you want to take this?

**Comment by baloneysandwiches** [comment]
Yes. I would prefer to localize all debouncing logic in a single function and not have timer stuff sprinkled all around, if possible. I would like to get rid of `resizeThrottle` if we can. Looking at:

https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/src/picturefill.js#L1324-L1327

is there a reason we need this? Is resize ever going to happen before `setupRun`?

**Comment by aFarkas** [comment]
This line is a micro optimization. If a developer calls the API while we wait for a debounced call, we abort the debounced call. Due to the fact that this won't happen so often... you are free to remove it.

**Comment by baloneysandwiches** [comment]
I took a quick stab at this but it's failing a handful of functional tests. I suspect this has to do with the async tests not playing well with the debounce timer. I hesitate to go build delays into the tests to make them pass. Can you take a look?

https://github.com/baloneysandwiches/picturefill/commit/292537822fd64a05705d709b957c6fc62b7c4af6
