### ISSUE TITLE
Add the composer webhook

### ISSUE THREAD

**Issue by mike-engel** [scottjehl/picturefill#515]
Per #500, a webhook needs to be added for composer support.

**Comment by mike-engel** [comment]
Pinging @wilto or @scottjehl to add this in.

**Comment by Wilto** [comment]
I think @scottjehl has to grab this one; only the owner of the repo can set up webhooks.

**Comment by mike-engel** [comment]
Another ping to @scottjehl

**Comment by scottjehl** [comment]
woops hi

**Comment by Wilto** [comment]
Okay; set up an account at packagist.org. I think we just need a `composer.php` before we can register the repo?
![image](https://cloud.githubusercontent.com/assets/439942/10079457/26b31064-62b8-11e5-9f8c-272be388f60f.png)

**Comment by mike-engel** [comment]
We've got the composer.json in the `3.0` branch. Once stable has been released and master is up to date with 3.0, we can move right along with this. Until then, we wait.

**Comment by mike-engel** [comment]
Ok, pf has been submitted to packagist. @scottjehl, when you get a moment, can you try again to add the composer/packagist webhook?

https://packagist.org/packages/scottjehl/picturefill

**Comment by mike-engel** [comment]
Sorry, but ping to @scottjehl again.

**Comment by mike-engel** [comment]
One last try to get @scottjehl to add the webhook.

**Comment by scottjehl** [comment]
oh hi. let's see here...

**Comment by mike-engel** [comment]
Webhook has been added. Thanks Scott!
