### ISSUE TITLE
Window Resize doesn't work

### ISSUE THREAD

**Issue by kuborgh-xalejado** [scottjehl/picturefill#517]
http://scottjehl.github.io/picturefill/examples/demo-01.html
If you resize the Browser, the image doesn't change. Only on refresh.

**Comment by Wilto** [comment]
Please keep in mind that Chrome, which has native support for `picture`, will always use the largest image available in the cache. If you start with a small viewport, clear your cache, then resize your viewport to larger, you should see the behavior as expected. Picturefill 3.0 will be mimicking this behavior as well.

If you’re using Firefox 38/39, this is also an issue with native implementation, and we’re offering a stand-alone fix (which will also be available as an extension to Picturefill 3.0): https://github.com/scottjehl/picturefill/issues/512#issuecomment-109796715

Feel free to reopen if this doesn’t describe the issues you’re seeing, but please provide us with as much information as possible about the issue you’re experiencing.

**Comment by kuborgh-xalejado** [comment]
Ok Thanks for the detail info :)
