### ISSUE TITLE
Safari 7.1.5 auf OS X 10.9.5 adds width attribute to <img >

### ISSUE THREAD

**Issue by di5abled** [scottjehl/picturefill#532]
I looks like your scripts adds some attributes to the img tag which aren't set in the sourcecode. This attributes break my responsive design for images. I use Version 2.3.1 of Picturefill and tested on Safari 7.1.5 auf OS X 10.9.5. Bellow you can see the rendered html of the safari debugger. The new added attributes are `width` and `style`.

```
<picture>
    <source media="(max-width: 350px)" srcset="/img/header_tiny.jpg, /img/header_tiny@2x.jpg 2x">
    <source media="(max-width: 600px)" srcset="/img/header_mobile.jpg, /img/header_mobile@2x.jpg 2x">
    <img src="/img/header.jpg" srcset="/img/header@2x.jpg 2x" alt="..." 
         width="2000" 
         style=""
    >
</picture>
```

**Comment by aFarkas** [comment]
I really would like to see an example, how this breaks you design. Could you create a test case for us? http://jsbin.com/cacuhoviha/1/edit?html,css,output

In general you can override this by adding ``img { width: auto}``, but I really would like to see how this fails. Are you doing height constrained images?

**Comment by di5abled** [comment]
I set images to `max-width: 100%` globally and when I have images which have detailed infos for width or height I reset this behaivoir to match this spezifix sizes. 

```
img {
    max-width: 100%;
}

img[width],
img[height] {
    max-width: none;
}
```

So I want my image to behave like a "responsive image" but the extra width attribute makes troubles with this aproach, but only in some browsers... So this behaivor adds browser inconsistency between browsers which can't be good in any way.

If you don't know what I mean I also can make a testcase if you prefer?

**Comment by aFarkas** [comment]
You have basically three options:

* use [pf 3.0 alpha](https://github.com/scottjehl/picturefill/tree/afarkas-pf3-proposal/dist) (my favorite)
* change your CSS to ``img[width][height] { max-width: none; }``
* add the following line to your JS (before picture fill) ``window.pfStopIntrinsicSize = true;``

**Comment by di5abled** [comment]
Version 3.0 alpha fixed it, I'll close this thank you!
