### ISSUE TITLE
IE10 crashes when picturefill() is re-intialised

### ISSUE THREAD

**Issue by ritchieanesco** [scottjehl/picturefill#535]
Hey guys,

I'm dynamically adding a list of items with images and have found if I try to re-initialise picturefill (i.e. picturefill(); )  it will crash if that list is 40 or more. Any ideas? We're currently using version 2.3.1

**Comment by aFarkas** [comment]
@ritchieanesco 
I think there is a little more to it than just 40 images. Could you please give us a testcase, so we can reproduce?

And could you please test whether this also happens with [picturefill 3.0 alpha](https://github.com/scottjehl/picturefill/tree/afarkas-pf3-proposal/dist)?

**Comment by ritchieanesco** [comment]
I'll see if I can replicate the page. Unfortunately its on our development environment unavailable to public. I think its also risky if we try to use PF3 when it's still alpha for a large corporate website.

**Comment by aFarkas** [comment]
pf 3.0 is - from a technic perspective - more like a good beta or even RC. We only want to have a longer testing phase for several reasons. Additionally it is important for us, that you at least check whether it crashes with 3.0. If it doesn't, you see it's pretty stable ;-).

@Wilto 
Maybe jump right into beta status with pf 3.0?

**Comment by ritchieanesco** [comment]
sweet. thanks, i'll give it a shot, and get back to you.

**Comment by ritchieanesco** [comment]
FYI, after more research found that Microsoft introduced a bug that slowed down innerHTML. See  https://social.msdn.microsoft.com/Forums/en-US/0b1cd4c5-1b3c-4816-8c43-5a3d6d287679/kb3038314-performance-issue-when-i-use-innerhtml?forum=iewebdevelopment

They recently released a patch for it, see above link.

**Comment by baloneysandwiches** [comment]
innerHTML might be slow on IE 10, but it's still synchronous. Meaning it *shouldn't* matter to PF if the reinit is called afterwards. If you have more info please let us know.

**Comment by ritchieanesco** [comment]
Thanks @baloneysandwiches, @aFarkas, @Wilto,

I swapped over to picturefill 3 alpha, and looks to have worked! We'll do some more testing to ensure it hasn't broken anything.

Can you guys tell me what the main difference between beta and alpha? And how close is v3 for release?

**Comment by baloneysandwiches** [comment]
Glad to hear it. About PF3, A general summary is at:

http://scottjehl.github.io/picturefill/

PF3 is really almost an RC at this point, over a year in the making. There have been a few minor bugfixes. And now we package a module that handles resize in Firefox, which is broken in their initial implementation. So stay tuned for any final tweaks, but you should be able to use it with confidence.

**Comment by Wilto** [comment]
Yeah; the beta/RC process at this point is just to get more eyes on it for the sake of testing. So far, things are feeling stable.

**Comment by ritchieanesco** [comment]
Closing this issue, will create new issues if anything arise with PF 3 alpha
