### ISSUE TITLE
Using `data-pfsrcset` attribute instead of `srcset` for img tags that have a picture parent

### ISSUE THREAD

**Issue by AdamMerrifield** [scottjehl/picturefill#539]
In the documentation there are two caveats that are semi conflicting; Temporary extra HTTP Requests for picture usage in some browsers, and Source element limitations.

To remedy both of these couldn't `img` elements that have a `picture` parent use `data-pfsrcset` (an attribute we are already adding for the method `dodgeSrcset`) instead of `srcset`? Obviously this would break native implementation of `srcset` (which is kind of the point since it's a fallback anyway) but since it has `source` siblings it should be using them anyway. This way `img` elements won't incur the extra HTTP request from the browser's preparser and picturefill will still be able to get the srcset to polyfill Android 2.3.

Does anyone see a problem with this?

**Comment by mike-engel** [comment]
At a first glance, I want to say we shouldn't do this. PF is meant to be a 1:1 match with the spec, and adding this new attribute would diverge from said spec. The issue of the extra download will eventually subside and more people upgrade their browsers. The goal of this polyfill is to be irrelevant one day, and I think adding this attribute would deter from this goal. 

As always though, I'd like to get @wilto, @aFarkas, or @baloneysandwiches' opinions on the matter.

**Comment by baloneysandwiches** [comment]
The data attribute is an idea we've entertained before. The problem is that for almost all setups, revisiting markup on the server is much harder than modifying (or removing) a polyfill. Building the polyfill around the limitations of early Android seem ultimately wrongheaded. That said, I see why this could be a useful "transitional" pattern. Seems like something for a fork.

**Comment by AdamMerrifield** [comment]
Both those points make sense to me, thanks guys.
