### ISSUE TITLE
Picturefill v3 alpha reinitialising not working on dynamically generated image

### ISSUE THREAD

**Issue by ritchieanesco** [scottjehl/picturefill#541]
Hi guys,

I've written a simple gallery that has a group of thumbnails and large image. On click of thumbnail, the large image is replaced by the thumbnail. I do this by grabbing the srcset of the thumbnail and overriding the main image srcset.  Here is the code:

var GalleryModule = (function (urlHelper) {

            var galleryClass = 'js-gallery',
            mainImgClass = 'js-gallery-main',
            thumbImgClass = 'js-gallery-thumb',
            captionClass = 'js-gallery-caption',
            overlayClass = 'js-gallery-overlay',
            sizes = null,
            spinner = null,

            init = function init() {

                if (!$('.' + galleryClass).length) {
                    return false;
                }

                bindEvents();
            },

            bindEvents = function bindEvents() {

                var that = this;

                $('.' + galleryClass).each(function () {

                    var $el,
                        $main,
                        $thumb,
                        $caption,
                        mainImgSrcSet,
                        srcset;

                    $el = $(this);
                    $main = $('.' + mainImgClass, $el);
                    $caption = $main.parent().next('.' + captionClass);
                    $thumb = $('.' + thumbImgClass, $el);

                    $thumb.first().addClass(stateClasses.active);

                    $thumb.on('click', function (e) {

                        e.preventDefault();

                        var $this = $(this),
                            $img = $this.data('large'),
                            $text = $this.data('caption'),
                            alt = $this.children('img').attr('alt');

                        if ($this.hasClass(stateClasses.active)) {
                            return false;
                        }

                        showSpinner($main);
                        resetGallery($thumb, $caption);
                        setMainImg(alt, $img, $main);
                        setCaption($caption, $text);

                        $this.addClass(stateClasses.active);

                        return false;

                    });

                });
            },

            showSpinner = function showSpinner ($main) {

                var $wrapper = $main.parent();

                $wrapper.append('<div class="gallery__overlay ' + overlayClass + '" />');

                spinner = new Spinner(loaderOpts).spin($('.gallery__overlay', $wrapper)[0]);

            },

            removeSpinner = function removeSpinner ($main) {
                var $wrapper = $main.parent();
                $('.' + overlayClass, $wrapper).remove();
                spinner.stop();
            },

            resetGallery = function resetGallery ($thumb, $caption) {

                $thumb
                    .removeClass(stateClasses.active);

                $caption
                    .removeClass(stateClasses.hidden)
                    .attr('aria-hidden', false)
                    .text('');
            },

            setMainImg = function setMainImg (alt, $img, $main) {

                $main
                    .removeAttr('src')
                    .attr({
                        'alt': alt,
                        'srcset': $img
                    }).parent().imagesLoaded(function () {
                        setTimeout(function () {
                            console.log('set image complete');
                            removeSpinner($main);
                            //force picturefill to reinitialise and
                            //re-evaluate current breakpoint
                            picturefill();
                        }, 1000);
                    });

            },

            setCaption = function setCaption ($caption, $text) {

                if ($text !== '' || $text !== null) {

                    $caption.text($text);

                } else {

                    $caption
                        .attr('aria-hidden', true)
                        .addClass(stateClasses.hidden);
                }
            };

            return {
                init: init
            };

        })(urlHelper);

    return GalleryModule;

});

The image swap happens in the setMainImg function. If i inspect the element, all the changes are there however Picturefill does not reinitialise, and i am stuck with an no image. This is happening on all browsers except Chrome. Thoughts??

**Comment by ritchieanesco** [comment]
So, i resolved this issue by removing the image, and then recreating it with the new attirbutes and finally re-intiialising. So i guess you guys biind something to the image on first initialisation so updating or removing its attributes won't work with re-intiialisation. Is this right?

**Comment by aFarkas** [comment]
There are multiple issue with the code. 

1. the official ``imagesLoaded`` plugin does not work with ``srcset`` (and I would strongly advice to not use it, anymore)
2. waiting for imagesloaded until calling ``picturefill`` is too late
3. and the really important part here. You need to use the ``reevaluate``

So your code should look like this:

```js
$main
	.removeAttr('src')
	.one('load.imagesloaded', function(){
		removeSpinner($main);
	})
	.attr({
		'alt': alt,
		'srcset': $img
	})
	.each(function(){
		picturefill({elements: [this], reevaluate: true});
		if(this.complete){
			$(this).trigger('load.imagesloaded');
		}
	})
;
```

@mike-engel 
I think we should make the documentation more clear, that ``reevaluate`` should be used if someone does relevant respimg mutations. In case ``reevaluate`` is set to ``true``, the ``elements`` option also has to be used, otherwise strange things can happen in Safari. As another alternative people can use the [mutation plugin](https://github.com/scottjehl/picturefill/blob/3.0/dist/plugins/mutation/pf.mutation.js).

**Comment by ritchieanesco** [comment]
thanks @aFarkas will give it a shot today. You recommended not using imagesLoaded. I am using a version written by you https://gist.github.com/aFarkas/15de1cea3acd6602a71e. Would you still recommend not using this? It seems to definitely work on some of the cases we're using it for.

**Comment by aFarkas** [comment]
>Would you still recommend not using this?
Well this version should work with ``srcset`` just fine. In case you are using it for a spinner, it is good to use.
