### ISSUE TITLE
IE8 & IE9 not loading images

### ISSUE THREAD

**Issue by julzmon** [scottjehl/picturefill#548]
![screen shot 2015-07-15 at 11 42 31 pm](https://cloud.githubusercontent.com/assets/46877/8715122/340544f2-2b4b-11e5-9d29-a083c85a28ea.jpg)
I'm getting the following error when trying to view in IE8 and IE9 through modern.ie Win7.

    HTML1201: github.io is a website you've added to Compatibility View. 
    picturefill
    SCRIPT438: Object doesn't support property or method 'querySelectorAll' 
    picturefill.js, line 1004 character 3

**Comment by mike-engel** [comment]
@julzmon Looks like you're running IE8 and IE9 in compatibility mode. Is there a reason for that or was it an accident? If it's on purpose, what version of IE are you running compatibility mode as?

**Comment by baloneysandwiches** [comment]
@mike-engel Should we maybe add:

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

to the `<head>` to ward this off going forward?

**Comment by julzmon** [comment]
@mike-engel Yeah I was testing it both ways. Without compatibility mode I still get this error.

    'picImg' is undefined  picturefill.js, line 1221 character 4

It was a fresh download from modern.ie pictured IE8 7601.17514
![screen shot 2015-07-16 at 6 28 53 am](https://cloud.githubusercontent.com/assets/46877/8720984/7e8c5086-2b84-11e5-8bb0-cd93274f8cc4.jpg)

**Comment by aFarkas** [comment]
It seems this ``picImg`` thing is a merge error. There is no ``picImg`` and no ``setIntrnisicSize`` in 3.0. Somehow it is a mixture between 2.0 and 3.0 version. If you use the real 3.0 (https://cdn.rawgit.com/scottjehl/picturefill/3.0/dist/picturefill.js) you should not get these errors.
