### ISSUE TITLE
Suggestion: Add Impact on SEO to gotchas in README.md

### ISSUE THREAD

**Issue by Undistraction** [scottjehl/picturefill#549]
Currently, probably the biggest gotcha (in many cases) to using Picturefill v2+ is that it renders all images unindexible by Google. For many sites this may have serious SEO implications, so I think this should be clearly stated in the README. This same issue obviously also means anybody with JavaScript disabled will see no images at all, so again, I think this deserves adding.

**Comment by jegtnes** [comment]
Hey there @Undistraction,

Thanks for raising this issue. We do mention in the main docs that browsers that for whatever reason can't render JavaScript and also don't support srcset will fall back to the alt text (as this stands globally, that's about [1.1%](https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/) of [40%](http://caniuse.com/#search=srcset).

The main docs are where the meat of the information about responsive images and Picturefill are, and the short Gotchas section in the README is largely intended to stop common queries being raised as bugs on the Picturefill repository (e.g. the Firefox 38-40 srcset bug resulted in about 10 Picturefill bugs being raised in a short space of time, despite this having nothing to do with Picturefill).

You do raise a good point, and it might well deserve an addition. If you have any more information or research about potential search engine optimisation implications of using responsive images, we'd love to see this in the docs. If you have some time, could you perhaps create a PR?

**Comment by aFarkas** [comment]
> using Picturefill v2+ is that it renders all images unindexible by Google
Simply not true. You can check this yourself with google webmaster tools (Try fetch/render as google).

picturefilled images are indexed by google. There is **no** negative impact.

**Comment by Undistraction** [comment]
@aFarkas Interesting. The last time I checked nothing other than images referenced in the `src` attribute were picked up, and there is at least one issue here with the same findings: #274 If this is the case - that `srcset` images are being indexed by Google, this is great news, and something you (Picturefill) should be making a big noise about as this has probably been keeping people from using the latest version(s).

**Comment by Undistraction** [comment]
@jegtnes Well hopefully this is now moot if Google is indexing `srcset`. In fact if this is true (I can't verify this now as I'm using v1 for everything I have in production), this is fantastic news.

**Comment by Undistraction** [comment]
@aFarkas It would definitely be worth adding your findings to the documentation.

**Comment by jegtnes** [comment]
@Undistraction Ace. 🎉 If you _do_ run into any issues once you migrate to v2/3, let us know. For now, I'll close this.

**Comment by Undistraction** [comment]
@aFarkas @jegtnes Unfortunately my tests show that this is not correct.

I set up a very simple test [here](http://www.undistraction.com/srcset_test.html) with two images:

```
  <img src="test.jpg" alt="Image USing Src">
  <img srcset="test_srcset.jpg" alt="Image Using SrcSet">
```

Using *Fetch As Google* this was my result:

![fetchasgoogle](https://cloud.githubusercontent.com/assets/161489/8761591/c8812bc6-2d50-11e5-9f29-7c8a018f7b70.png)

**Comment by aFarkas** [comment]
@Undistraction 
I don't see picturefill included.

**Comment by Undistraction** [comment]
@aFarkas But surely the Google crawler won't run picturefill?

**Comment by aFarkas** [comment]
google supports some JS. picturefill is supported.

**Comment by Undistraction** [comment]
@aFarkas  Apologies. You are correct. Strange that Google gets the visitor render wrong. And stranger still that it doesn't pick up the srcset image without Picturefill being included.

![fetchasgoogle3](https://cloud.githubusercontent.com/assets/161489/8761632/b34cb49e-2d52-11e5-98cf-32844963c4f4.png)

**Comment by aFarkas** [comment]
I think google uses an old webkit headless browser to render the page and get its content. therefore there is no ``srcset`` support yet, but picturefill will polyfill googlebot the same way, as it polyfills other browsers.

**Comment by Undistraction** [comment]
@aFarkas Thanks for the explanation. I'm very surprised, but obviously in a good way. I'd echo what I said earlier - this would be worth adding to the docs.

**Comment by baloneysandwiches** [comment]
Thanks for confirming this. Personally, I don't think explaining that the Google crawler executes basic javaScript is within scope for the docs.

**Comment by Undistraction** [comment]
> explaining that the Google crawler executes basic javaScript is within scope for the docs.

@baloneysandwiches Given that SEO is such an important consideration of any site, I don't agree.
 
Anyone testing Google's ability to index the `srcset` attribute using Webmaster tools would conclude that it doesn't index images defined there. (I couldn't find any information about this at all online) Picturefill is altering this behaviour. This is a positive side-effect, but it is a side-effect regardless, so it should be documented. You could argue that it is a deliberate feature of Picturefill, but again, if this is the case, it should be documented.

Apart from anything else this is a big win for Picturefill and documenting it will only further encourage people to use it.

**Comment by jesseheap** [comment]
I second including this in the documentation.  A general statement that spiders can still index images without the SRC attribute would be a big win to help encourage use.

Most of the information out there implies Google will not index images using the srcset method and without this thread I would not have moved forward implementing it for myself.

**Comment by Sylvareth** [comment]
I've been looking into this issue lately myself, and for a client's website that has been online for 6 months, with srcset AND picturefill, not a single image could be found in Google Images.

For other clients I have fixed this issue by including both a src and srcset attribute. Google indexed these images a lot faster.

**Comment by Undistraction** [comment]
@Sylvareth This will mean the image declared in the `src` attribute will always be downloaded regardless of the viewport width, meaning clients will download two versions of the same image. 

Have you tried viewing the crawling the site as Google from Webmaster tools. Do the srcset images show?

**Comment by Sylvareth** [comment]
I have just checked with Google Search Console and the srcset-only images are not rendered in the preview. Only when I add a src-attribute, it renders them. I am using Picturefill v.2.3.1.

Also, about the double download. I have checked this across multiple browsers and did not come across any double requests, at least not in any desktop browser.

**Comment by aFarkas** [comment]
@Sylvareth 
Pretty sure you are testing wrong. I have tested it myself with fetch as google as also have sites using it. Here is also an article in german, that tested it and concluded that images are indexed.

www.stefan-weiss.net/responsive-image-seo.htm
