### ISSUE TITLE
Don't set explicit width

### ISSUE THREAD

**Issue by cmeeren** [scottjehl/picturefill#557]
I have an image I would like to fit within a container. I'm doing this with ``max-height: 100%`` and ``max-width: calc(100% - 8em - 10px)``. This works at least in Firefox and Chrome. But in IE, picturefill sets the ``width`` attribute on the ``img`` element explicitly based on the ``sizes`` attribute, which overrides ``max-width`` and ``max-height`` resulting in the image filling the container horizontally and having a (potentially wildly) incorrect aspect ratio.

Firefox and Chrome seems to adhere to ``max-width`` and ``max-height`` when rendering the picture using ``sizes`` and ``srcset``, making sure the aspect ratio is preserved (since no explicit ``width`` or ``height`` is given). Shouldn't picturefill also do this?

**Comment by cmeeren** [comment]
Note that I managed to circumvent the problem by adding ``width: auto;`` alongside ``max-height`` and ``max-width``.

**Comment by aFarkas** [comment]
Please if this answer helps you:
https://github.com/scottjehl/picturefill/issues/532#issuecomment-118958085

**Comment by cmeeren** [comment]
Thanks. Since I already found a workaround, I think I'll stick with that - unless PF3.0 alpha is production ready (I guess not)?

**Comment by mike-engel** [comment]
@cmeeren 3.0 is essentially production ready. We're using it on the picturefill demo site, and the only reason, really, that we've got it labeled as a beta is because it's almost a complete re-write, so we just wanted some extra eyes on it. We haven't seen any major issues come up with 3.0, however.

**Comment by cmeeren** [comment]
So which branch do I use? 3.0 or afarkas-pf3-proposal? Do you know when you'll release the final 3.0?

**Comment by mike-engel** [comment]
@cmeeren You can use the 3.0 branch if you want the code from github. Additionally, you can use the `3.0.0-beta1` from npm if you use that. If you use bower, you can simply use any of the tags from our [tags page](https://github.com/scottjehl/picturefill/tags). Assuming there are no more issues files for 3.0, stable should launch within a month to a couple of weeks we hope.

**Comment by cmeeren** [comment]
Thanks. Problem seems to have been fixed.
