### ISSUE TITLE
Image dimensions issue on high-resolution device

### ISSUE THREAD

**Issue by UnknwnException** [scottjehl/picturefill#561]
Hello,

I'm encountering a strange issue with the picture tag on Firefox and I'm not sure if it's a browser issue or not.

The issue is the following. When I use a picture tag with high-resolution and low-resolution images on a high-resolution device, the container of the picture element has a width equal to two times the width of the low-resolution image instead of having a width equal to the width of the low-resolution image. However the image has correct dimensions.

To test I'm using Picturefill v2.3.1, Chrome v44 (OS X), Firefox v39 (OS X) & Safari 7.1.7 (OS X) on a retina macbook pro.

Here is a reduced test case: http://jsfiddle.net/UnknwnException/7essw986/

Thanks in advance.

**Comment by aFarkas** [comment]
This is a known bug regarding intrinsic sizing. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1149357

I suggest, that you use CSS to style the width of your images and not rely on intrinsic sizing in general.

**Comment by UnknwnException** [comment]
Hi aFarkas,

Thanks for your quick answer.
Do you think it will be a viable solution to set width and height in the image onload function?

**Comment by aFarkas** [comment]
Yes, but it might jump a little bit.

**Comment by UnknwnException** [comment]
Ok thanks a lot aFarkas. I think I don't have any better solution for now.
