### ISSUE TITLE
No Images without img src attribute UC Browser Android

### ISSUE THREAD

**Issue by Mellivora** [scottjehl/picturefill#564]
Many thanks for your work on this plugin.

I am not getting any images displayed in [UC Browser for Android](https://play.google.com/store/apps/details?id=com.UCMobile.intl) unless I put a src attribute in the image tag.

I have the latest UC Browser (v10.6.2.599) and am using an HTC One M7 on Android 5.0.2 with Picturefill 2.3.1. I have also tried  3 beta 1 but have the same problem. This is happening on the Picturefill demo page as well as my development site.

This is not a problem in [UC Browser HD](https://play.google.com/store/apps/details?id=com.uc.browser.hd) which seems to work.

**Comment by aFarkas** [comment]
The UC browser has implented the srcset IDL attribute and the picture element constructor. Which means this browser lies about its responsive image support and picturefill doesn't polyfill the features.

While we could improve our feature detection. The needed code changes would make the test async and more errorprone. It is clearly a UC browser bug. Could you please report them the specific problem? They should be able to fix it much easier without side effects.

**Comment by aFarkas** [comment]
I just checked how we could write a "better" feature detection to detect the fact that UC browser doesn't work correctly. 

From my testing the following check should work:

```js
var img2;
var img = document.createElement('img');

var isSupported = 'srcset' in img;

if(isSupported){
	img2 = document.createElement('img');
	img.srcset = 'data:,a';
	img2.src = 'data:,a';
	isSupported = img.complete == img2.complete;
}

//--------------
alert(isSupported);
```

So question is should we fix this and if yes (I would vote for yes), should we do this for 3.0.0 or should we delay this after the release? (The RC PR isn't merged yet anyway.)

**Comment by Mellivora** [comment]
Hi, many thanks for getting back and sorry for my delay in replying, I have been away with no internet access.

I will submit an error report to UC Browser and a fix sounds good to me.
