### ISSUE TITLE
Append responsive images with Ie9/10/11

### ISSUE THREAD

**Issue by petulla** [scottjehl/picturefill#565]
Hi

I'm trying to use jQuery to add images responsively like so:

```
$('.myclass').html('<img sizes="80vw" srcset="./photos/se/responsive/webp/min/1_1-2000.webp 2000w, ./photos/se/responsive/webp/min/1_1-2500.webp 2500w" class="full-full-width scrollshow-1-1">');
```

This works fine on Chrome/Firefox but doesn't work on any IE browsers. Does the picturefill library need to be loaded after the appends or is there an async issue?

**Comment by petulla** [comment]
So this is quite something, but using:

```
$('.myclass').append('...')
```

Seems to have solved the issue. Go figure. 

Any thoughts?

**Comment by albell** [comment]
Switching to jQuery `append()` isn't going to address what you're experiencing. Both jQuery methods add a new img to the DOM. You're probably experiencing a quirk of your testing setup.

Picturefill automatically evaluates image candidates when the page loads, and also on resize. If the page is already loaded at the time the script executes, then the evaluation will happen immediately. You can think of this as "auto init". If you are dynamically updating the DOM (adding `<img>` with jQuery, etc), you can call `picturefill()` again after the insertion, to evaluate the new images. You can also call:

    picturefill({
      reevaluate: true
    });

to force reevaluation of existing images, in case layout has changed. See the <a href="http://scottjehl.github.io/picturefill/">API</a> in the docs.
