### ISSUE TITLE
Branch purge

### ISSUE THREAD

**Issue by albell** [scottjehl/picturefill#569]
We have a lot of obsolete branches. Can we do a big purge?

Current branches include:

1.2
2.0.0a
2.2
2.2.1-npm
2.3
2.3-doc-fixes
2.4
3.0
3.0-rc-preparation
afrakas-pf3-proposal
alternate-type-support
cache-busters
docs-edits
findimg-issue215
fix-beat-download-links
gh-pages
inherent-width
issue536-pattern-doc-updates
jcutrell-sourcesrc-notification
jonathantneal-test-compatibility
massive-refactor
readme-updates
saveData-cached
srcset-parsing
switch-namespace-pf
user-prefs

Team: please copy this list and put an  :heavy_multiplication_x: to the left of things we can get rid of. Most of these, I would think, including 2.2 & 2.2.1

**Comment by jonathantneal** [comment]
:heavy_multiplication_x: jonathantneal-test-compatibility

**Comment by mike-engel** [comment]
This leaves all major.minor branches, as well as ones with open PRs.

- [ ] 1.2
- [x] 2.0.0a
- [ ] 2.2
- [x] 2.2.1-npm
- [ ] 2.3
- [x] 2.3-doc-fixes
- [ ] 2.4
- [ ] 3.0
- [ ] 3.0-rc-preparation
- [x] afrakas-pf3-proposal
- [x] alternate-type-support
- [x] cache-busters
- [ ] docs-edits
- [x] findimg-issue215
- [x] fix-beat-download-links
- [ ] gh-pages
- [x] inherent-width
- [x] issue536-pattern-doc-updates
- [x] jcutrell-sourcesrc-notification
- [x] jonathantneal-test-compatibility
- [x] massive-refactor
- [x] readme-updates
- [ ] saveData-cached
- [x] srcset-parsing
- [x] switch-namespace-pf
- [x] user-prefs

**Comment by albell** [comment]
LGTM. Should we get rid of 2.2? We actively don't want anyone using anything before 2.3.1

Does serving 2.2 have any historical purpose etc?

**Comment by mike-engel** [comment]
I guess not. Should be okay to remove it.

**Comment by aFarkas** [comment]
+1

**Comment by jegtnes** [comment]
Looks good to me. We've got everything appropriately tagged, so things that aren't under active development are good to go.

**Comment by albell** [comment]
I think I got everything old out. Closing.
