### ISSUE TITLE
img only tag and multiple images

### ISSUE THREAD

**Issue by kibbage** [scottjehl/picturefill#577]
Resizing you demo page I noticed that the extra large image resizes but does not change the image source in some browsers. With Firefox, and Chrome I only get the "extra large" image. With Safari and Edge I see all three images. Is this how it is supposed to work?

**Comment by quoo** [comment]
Which one of the demo pages is this? Is it an image tag using srcset?

**Comment by kibbage** [comment]
Yes, the very first example.

**Comment by danielmag** [comment]
Try disabling the cache.
In [picturefill documentation](http://scottjehl.github.io/picturefill/):

> Modern browsers that support srcset natively may select a cached file that meets the minimum media condition, even if it is “overkill” for the current media condition. For example, a 2x file may be shown on a 1x device, if that 2x file is already in the cache—there’d be no reason to make an additional request when the user will see no discernable difference, after all. This is typically encountered only on sites with multiple versions of the same image displayed in multiple elements at different sizes (like our demo page). The occasional selection of "oversize" resources—depending on the cache—is currently an expected behavior in native implementations and you may encounter it during testing.

**Comment by kibbage** [comment]
Yes it is. The very first demo.

**Comment by kibbage** [comment]
In Firefox I went to Options => Advanced Options, clicked on the Network tab, selected “Override automatic cache management”, set the limit to 0 MB, cleared the Cached Web Content and Offline Web Content, restarted Firefox and there was no difference on my local copy of the demo but the online version did change. Must be cached somewhere in my machine.

**Comment by mike-engel** [comment]
@kibbage What I believe is happening here, is that while you have the cache disabled, the cache for the session is still holding the larger image (for chrome). For firefox, there's currently a bug preventing firefox from changing the source during the resize event. Thus, if you load one image and resize the browser, nothing will change.

**Comment by spencercarnage** [comment]
@mike-engel Is there anyway of forcing the cache to flush for chrome outside of the usual methods that apparently aren't working in this scenario? I'm version 46.0.2490.86 (64-bit). I tried loading chrome with the `--disable-cache` command line flag and it's still loading the `extralarge.jpg` for all browser sizes. Do we know if there's a bug with Chrome's implementation of `sizes` and / or `srcset` for `<img>` tags?

**Comment by mike-engel** [comment]
@spencercarnage The best way we know of to force the cache to be ignored is something @aFarkas calls cache-busting. You can see his comment [here](https://github.com/scottjehl/picturefill/issues/543#issuecomment-121305100). It's actually the intention to use the cached image even if it's overkill since it's already been downloaded.

**Comment by mike-engel** [comment]
@kibbage Did provide a good answer to your question? Do you still have more questions?

**Comment by kibbage** [comment]
Yes, I understand now. Thank you

**Comment by mike-engel** [comment]
Happy to help.
