### ISSUE TITLE
accessory images sample

### ISSUE THREAD

**Issue by robsonsobral** [scottjehl/picturefill#583]
Hi!

I'm working on a project and just noted something. First, tell me if I'm getting it right. The `picture/source` elements list the exceptions the author of the content chose to use, right? It should be the last resource, not the default one. So, this sample is inverted:

```html
<picture>
    <source srcset="../img/sample.svg" media="(min-width: 768px)" />
    <img srcset="data:image/gifbase64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        alt="Sample pic" />
</picture>
```

It should be something like:

```html
<picture>
  <source media="(max-width: 767px)" srcset="data:image/gifbase64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" />
  <img
  srcset="/path/to/image 200w,
          /path/to/image 300w,
          /path/to/image 500w
          " alt="ALT TEXT" />
</picture>
```

Now, the browser can pick the right image size **except** for screens below `768px`.

**Comment by mike-engel** [comment]
Hey @robsonsobral, I'm not sure exactly what your question is, but I'll try and guess.

The `picture` element is mainly used for art directed photos. For example, on smaller screens you want an image cropped in a certain way, but on desktop it should show the full photo. Or, on smaller screens there shouldn't be an image at all while on larger screens, the image should be shown.

In the first example you posted, the browser will _only_ show an image if the window is at least 768px wide. That data url in the `srcset` attribute is a 1px transparent GIF, which will show no image on screens less that 768px wide. This is our recommended markup pattern for scenarios where an image should only show up on certain `media` conditions.

In the second example you posted, the images would only show on smaller screens, and the 1px transparent gif would be displayed on screens larger than 768px wide.

I hope that makes sense. If I didn't answer your question, please let us know.

**Comment by aFarkas** [comment]
My problem understanding you, also has to do with the fact, that one image is using an svg and the other are using multiple images with width descriptors (and no sizes attribute). Is this difference also intentional to the question?

**Comment by robsonsobral** [comment]
Thanks, @mike-engel ! You misread my sample. I used `media="(max-width: 767px)"`.

You're, @aFarkas . I missed one part of the code.

Help me, please. If I have several files of the same image and I want the browser to pick the right one, except on small screen, I need something closer to my sample, right?

The change I'm suggesting on the documentation is only to help keep clear that `srset` on `img` should be the primary choice.

**Comment by aFarkas** [comment]
> The change I'm suggesting on the documentation is only to help keep clear that srset on img should be the primary choice.

Why? First match wins. There is no one forcing you to anything. It is absolutely up to you and your team to decide how to write such a pattern. 

In fact, I personally would write the first one. (Using img[srcset] with a blank image). The reason is quite simple, browser which do not support picture but do support srcset will have a double download. 

See also:
https://github.com/scottjehl/picturefill/issues/536

@mike-engel and me would write something like this:

```html
<picture>
    <source srcset=srcset="/path/to/image 200w, /path/to/image 300w, /path/to/image 500w” sizes=“…" media="(min-width: 768px)" />
    <img srcset="data:image/gifbase64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        alt="Sample pic" />
</picture>
```

**Comment by robsonsobral** [comment]
Thank you so much, guys!

I'm designing a pinterest like interface and it looks like I've a lot to learn.

I'm sorry for bother you both!

**Comment by mike-engel** [comment]
Certainly not a bother @robsonsobral, it's what we're here for! Glad we could help.
