### ISSUE TITLE
Remove FF workaround for resize (May/June 2016)

### ISSUE THREAD

**Issue by aFarkas** [scottjehl/picturefill#584]
This is a future task. We currently fix some special issues with FF 40-. In March 2016 support for this can be dropped from the pf main dist file. These fixes can then be still loaded manually, if needed.

**Comment by mike-engel** [comment]
This was completed in #610

**Comment by aFarkas** [comment]
No, this is about removing the hole FF workaround extension from core. Basically changing this line:
https://github.com/scottjehl/picturefill/blob/master/gruntfile.js#L41

to: 

```js
src: [ "src/picturefill.js" ],
```

This will happen in Mai/June 2016. Then we have the situation that, current, current - 1 and ESR version support this fully.

**Comment by jegtnes** [comment]
@aFarkas According to the [release calendar](https://wiki.mozilla.org/RapidRelease/Calendar), ESR 45 will be out on the 7th March. Is there a reason we shouldn't be removing this fix at that point? Or do ESR users mostly stick to the older ESR version until it's got the 2 stability releases under the belt (6th June, 45.2)? I'm not familiar with the ESR process.

**Comment by aFarkas** [comment]
We can remove it at this point. May/June is only the "save" Date. After Mozilla has released the new ESR, Mozilla will continue to support the old one for 12 weeks, to make the transition between those versions as smooth as possible.

**Comment by jegtnes** [comment]
Cool. Shall we aim to get a 4.0 out for the 7th of March with this, #556, and anything else that crops up?

**Comment by aFarkas** [comment]
Just closing, because now we need this code for Safari to be part of the core.
