### ISSUE TITLE
Safari can't set right image size on retina display

### ISSUE THREAD

**Issue by abozhinov** [scottjehl/picturefill#590]
You can see at: http://mastershop.dsht.in picturefill.js gets actual image size. I try to set size="200" but it doesn't help.

**Comment by mike-engel** [comment]
Hey @abozhinov, couple of questions, and some things I'm noticing.

1. I'm assuming that the image you're referring to is the main image with the macbook?
2. The `sizes` attribute is meant to represent how large the image will be displayed on your page. Your `sizes` attribute doesn't specify a unit of measurement. 200 doesn't mean a lot to the browser. If you mean `px`, it would be apt to change it to `200px`.
3. Just to be sure, your media queries (`min-width: 400px`, and `min-width: 100px`) are the size of the viewport, correct? The `media` attribute works just like CSS media queries.

Unfortunately I don't have a retina screen anymore to test on, but in the meantime, answering those questions or providing a little more context will help.

Thanks!

**Comment by aFarkas** [comment]
Additionally to everything mike-engel already said. `sizes` only makes sense if you use width descriptors (**w**) you use density descriptors (**x**). So you don't need / can use `sizes` at all. You must use the `media` attribute to control everything.

**Comment by abozhinov** [comment]
I set size attr in PX, but it doesn't help.

Safari macbook pro retina:
https://www.dropbox.com/s/gd5e6chni5d28to/Screenshot%202015-10-14%2021.27.19.png?dl=0

Chrome macbook pro retina:
https://www.dropbox.com/s/ioa5kjwy2bx6t6n/Screenshot%202015-10-14%2021.29.23.png?dl=0

In chrome eveything is perfect but Safari ... makes me crazy..

**Comment by abozhinov** [comment]
I use media attribute to control which image to show but the problem is in the size at Safari.

**Comment by aFarkas** [comment]
To me this looks like a styling issue. Have you tried:

```css
img {
    width: 100%;
    height: auto;
    /*max-width: 100%;*
}
```

**Comment by abozhinov** [comment]
No, the problem is that safari ready img tag  and in this image tag picturefill add src @2x image. The size of this image is twice of the normal one and for that reasone safari print it with actual size. 

I should write css rules to fix that but it's not so good solution.

**Comment by aFarkas** [comment]
It is actually a good solution to write this with CSS. But you can try the following plugin:
https://github.com/scottjehl/picturefill/tree/master/dist/plugins/intrinsic-dimension

**Comment by abozhinov** [comment]
Find solution without picturefill 
<img
  src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
  alt="Lenovo"
  srcset="http://mastershop.dsht.in/data/uploads/products/4e0dfd7ecd6505ebb31cba93d05cf9cc/B_14447739578575561d8045d15d3508.jpg 200w, http://mastershop.dsht.in/data/uploads/products/4e0dfd7ecd6505ebb31cba93d05cf9cc/B_14447739578575561d8045d15d3508@2x.jpg 400w,  http://mastershop.dsht.in/data/uploads/products/4e0dfd7ecd6505ebb31cba93d05cf9cc/H_14447739578575561d8045d15d3508.jpg 100w, http://mastershop.dsht.in/data/uploads/products/4e0dfd7ecd6505ebb31cba93d05cf9cc/H_14447739578575561d8045d15d3508@2x.jpg 200w"
     sizes="(min-width: 770px) 200px ,(min-width: 100px) 100px"
     />

**Comment by aFarkas** [comment]
1. You should rewrite your `sizes` to something like this: `sizes="(min-width: 770px) 200px, 100px"`

2. This won't work cross browser:
You are testing this in Safari 9 right?

Any browser that doesn't support `sizes` but runs on a retina will have your initial error. So your problem still happens in Safari 8, IE10/IE11 and older Firefox.

As I said: Using CSS is a good solution to style things in general and it is also a good solution to style the width of a responsive image.

But if you really want to have the same responsive sizing feature responsive images have, use the intrinsic ratio plugin. It's 1.6kb minified and below 0.9kb compressed.

**Comment by stewx** [comment]
I had the same issue on Safari 7 and using that intrinsic plugin did the trick. It seems like something that should work out of the box, though.

**Comment by aFarkas** [comment]
@stewx 

You are the third dev who wants this feature. (see also: https://github.com/scottjehl/picturefill/issues/594)

About one year ago we had a lot of issues, where people saw this as a bug in native implementations (see a recent issue here: https://github.com/scottjehl/picturefill/issues/575). 

My problem with having this in core is pretty simple, that I want to have picturefill lightweight. We already have two modules included which should be optional in my eyes (webp detection and FF respimg workaround), but we have them for backwards compatibility and it's hard to change on this.

At the same time, there are two other "plugins" (image type detection and mutation observer), which also absolutely make sense to include to make picturefill a "full polyfill". Obviously this would go against picturefill being as lightweight as possible and to only include what 80% of all developers need.  Maybe a better possibility would be to  create a download builder, that makes it easy to add/remove plugins. This way also the current plugins are more upfront and people realize that there is more to it than just one core file? And maybe we can add an option to deselect the two plugins I spoke about above.

**Comment by stewx** [comment]
I like the download builder idea--similar to what jQuery UI does.

If it's a bug in native implementations, how are you supposed to specify what size the rendered image should be on the page? Just with CSS?

**Comment by aFarkas** [comment]
> If it's a bug in native implementations, how are you supposed to specify what size the rendered image should be on the page? Just with CSS?

It's not a bug in native implementations. Only a lot people thought it is. And yes, currently we assume that 80% of all developers specify at least one dimension with css (mostly width). If not you need to use the intrinsic sizing plugin.
