### ISSUE TITLE
img with srcset, picture doesn't

### ISSUE THREAD

**Issue by alvipeo** [scottjehl/picturefill#594]
I'm not sure this is an issue but don't know where to ask.

So I have this picture element:
```
<picture class="hidden-m">
    <source srcset="images/icons/320-img-week1to6.png 1x, images/icons/320-img-week1to6@2x.png 2x" />
    <img srcset="images/icons/320-img-week1to6.png" alt="" />
</picture>
```
And on iPhone 6 plus it shows images/icons/320-img-week1to6@2x.png which is right I suppose. But what happens this image shows too wide. Now, if I change it to this:
```
    <img class="m-1" srcset="images/icons/320-img-week1to6.png 1x, images/icons/320-img-week1to6@2x.png 2x" alt="" />
```
everything is fine. Why is the difference?

**Comment by aFarkas** [comment]
The first example is polyfilled by picturefill while the second isn't, it is natively supported. picturefill polyfills it by moving the right image candidate to the `src` of the image. 

In general you can style the width of your images using CSS. If you can't or don't want to, you can include the [intrinsic-dimension plugin](https://github.com/scottjehl/picturefill/tree/master/dist/plugins/intrinsic-dimension).

**Comment by alvipeo** [comment]
Thank you! But shouldn't the one that's polyfilled do this by default? I mean how is it supposed to work by the spec? When we have browsers native support.

**Comment by alvipeo** [comment]
Sorry I accedentaly closed this :(

**Comment by aFarkas** [comment]
99% of all developers do override the width by CSS or by using width/height content attributes. In fact this is also a best practice: Specifying image dimensions makes sure that the browser doesn't need to reflow the page after an image has loaded.

So including this plugin will only serve those developers, who don't use best practices. (This doesn't mean, that I think you are doing it wrong.) But what is wrong to include another script?

In case we would include every tiny detail, that is speced, we would end up with 100kb polyfill script.

**Comment by alvipeo** [comment]
ok, thanks. I do use best practices I just wanted to know why native support is different from polyfill.
