### ISSUE TITLE
Provide / improve documentation on plugins

### ISSUE THREAD

**Issue by rayshan** [scottjehl/picturefill#595]
Hi!

- It's not clear how plugins should be loaded - as a script tag, after loading picturefill? Same for all plugins?
- Should docs be merged from `respimage`? E.g.: https://github.com/aFarkas/respimage/tree/gh-pages/plugins/mutation
- Picturefill socs say ["To use `saveData`, create a `picturefillCFG` array that runs before the main plugin"](https://github.com/scottjehl/picturefill/blob/master/index.html#L256). What is "main plugin", picturefill itself?

**Comment by capaj** [comment]
:+1:

**Comment by mike-engel** [comment]
@rayshan @capaj Does this PR answer your questions? If not, could you add what else you would like to see in that PR? Thanks! https://github.com/scottjehl/picturefill/pull/603

**Comment by rayshan** [comment]
Reviewed, thanks!
