### ISSUE TITLE
Safari 9.0 double download / Flash Of Wrong Image™ ([if IE 9] no longer works?)

### ISSUE THREAD

**Issue by rayshan** [scottjehl/picturefill#597]
Hi, looking at the demo here: https://scottjehl.github.io/picturefill/examples/demo-02.html, which includes the pattern recommended here: https://github.com/scottjehl/picturefill/issues/536.

Safari 9.0 seems to double-download the right size and 1 size down:

![screen shot 2015-10-20 at 12 14 20 am](https://cloud.githubusercontent.com/assets/3760840/10600481/e9861698-76bf-11e5-852b-5d589c7c410c.png)

![screen shot 2015-10-20 at 12 14 54 am](https://cloud.githubusercontent.com/assets/3760840/10600485/edbeac66-76bf-11e5-9aaf-4d802a905966.png)

![screen shot 2015-10-20 at 12 15 27 am](https://cloud.githubusercontent.com/assets/3760840/10600487/f160596e-76bf-11e5-94bd-afc9be63fe91.png)

**Comment by aFarkas** [comment]
@rayshan 
If you read through the #536 you see that we actually discuss another pattern to prevent exactly this.

```html
<picture>
  <!--[if IE 9]><video style="display: none;"><![endif]-->
  <source srcset="large.jpg" media="(min-width: 1200px)">
  <source srcset="small.jpg" >
  <!--[if IE 9]></video><![endif]-->
  <img class="header-image__img" alt="Image">
</picture>
```

The idea is not to add a ``src`` or a ``srcset`` to the image.

**Comment by rayshan** [comment]
Ahh this worked. I tried it but typed `<source src="small.jpg" >` by copying `src` from `img` over, but it has to be `<source srcset="small.jpg" >`, or `small.jpg` won't load. Thanks.
