### ISSUE TITLE
IE10 not consistently triggering image.onload when setting srcset

### ISSUE THREAD

**Issue by brianium** [scottjehl/picturefill#604]
**Using Picturefill 3.0.1**

Given the following code:

```js
var image = new Image();

image.onload = function() {
  console.log('image loaded!');
};

image.srcset = '/img/rainbows-480.png 480w, /img/rainbows-960.png 960w, /img/rainbows-1920.png 1920w';

picturefill({
  reevaluate: true,
  elements: [image]
});
```

IE10 will sometimes trigger the onload behavior, and other times it will not. I have tried multiple times with a cleared cache, and sometimes it works, and other times it does not.

My use case is dynamically added images. I add a new image then call picturefill with that element, and it seems to do the trick just fine in other browsers.

Is this a bug or am I using picturefill incorrectly?

Thanks again for the great tool!

**Comment by brianium** [comment]
*UPDATE* - I was mistakenly requiring 2 versions of picturefill in my test. I had `2.3.1` and `3.0.1` being loaded in script tags containing the `async` attribute.

The reason it worked sometimes is sometimes `2.3.1` finished loading last.

The behavior I attached above works great in `2.3.1`, but not in `3.0.1`

Is this intended? Shouldn't setting `srcset` always trigger an image load?

**Comment by aFarkas** [comment]
Is this also happening in IE9 or IE11?

**Comment by brianium** [comment]
@aFarkas I have not checked, I will do so now :)

**Comment by aFarkas** [comment]
Can you also check with the following code:

```js
var image = new Image();

image.onload = function() {
  console.log('image loaded!');
};

image.setAttribute('srcset', '/img/rainbows-480.png 480w, /img/rainbows-960.png 960w, /img/rainbows-1920.png 1920w');

picturefill({
  reevaluate: true,
  elements: [image]
});
```

**Comment by brianium** [comment]
absolutely

**Comment by aFarkas** [comment]
From looking at the code, it shouldn't work in any version of picturefill.

You are just using the IDL attribute `srcset`. picturefill core only polyfills the content attribute. (Which you can change with `setAttribute`).

In case you want to add support for the IDL attribute you can use the [mutation plugin](https://github.com/scottjehl/picturefill/tree/master/dist/plugins/mutation).

**Comment by brianium** [comment]
odd.. 

IE10 definitely worked with onload when using the `srcset` attribute in 2.3.1. ¯\\\_(ツ)_/¯

Using `setAttribute` fixed the issue in all versions of IE though.

Many thanks!

**Comment by brianium** [comment]
@aFarkas I am going to close this as `setAttribute` fixed my issues. Might be useful to document this somewhere. Do you guys need any help with documentation? If so please point me in the right direction. I would love to help.

Thanks again!

**Comment by aFarkas** [comment]
Help is always welcome. Although I'm not the best in coordinating things. We have currently the following [open documentation issues](https://github.com/scottjehl/picturefill/labels/Documentation) and this [open documentation PR](https://github.com/scottjehl/picturefill/pull/603). The newest version of our documentation can be found in the [3.0 branch](https://github.com/scottjehl/picturefill/tree/3.0).

I in general would like to have a very short documentation.
