### ISSUE TITLE
No image appears in IE7

### ISSUE THREAD

**Issue by henrik23** [scottjehl/picturefill#605]
On the project site on my Windows Vista IE9 in IE7-mode no image appears, just alt text. See screenshot.

![picturefill_ie7_issue](https://cloud.githubusercontent.com/assets/8209524/11170269/60a36bb2-8bcf-11e5-9797-9f375c95206d.PNG)

Is this intended behavior? 
Thanks!

**Comment by aFarkas** [comment]
Yes, this behavior is intended. picturefill can support IE6/7, if you additionally install jQuery and the [oldIE plugin](https://github.com/scottjehl/picturefill/tree/master/dist/plugins/oldie).

Things we don't do in our demo page.

Please also note, that you can't really emulate IE7 with IE9. We only support real IE7.

**Comment by henrik23** [comment]
Thanks for clarifying! I think I 'll rather use Conditional Comments for IE7- since I 've to use them anyway for pictures which have to be lazyloaded with your "lazysizes" in IE8-.

**Comment by peterwilsoncc** [comment]
@aFarkas Possibly slightly off topic, is it worth feature testing `document.querySelector` as pf currently fatals in IE7?

**Comment by aFarkas** [comment]
We could return an empty array, if `context.querySelectorAll` is not available, but this doesn't change the users experience. It only changes his console.
