### ISSUE TITLE
Firefox srcset bug only fixed/released for the picture element

### ISSUE THREAD

**Issue by thasmo** [scottjehl/picturefill#614]
It seems to me that the srcset bug for the `picture` element has been fixed and released in Firefox 41, but the [fix for the `img` element](https://bugzilla.mozilla.org/show_bug.cgi?id=1166138) has not yet been released, but will be with Firefox 45, as I understand.

The README states:
```
Firefox 38 and 39 has some bugs [1] [2] [3] where images won't update on screen resize. These issues are addressed by Picturefill 3.0.0, and was fixed in Firefox 41.
```
This then only refers to the `picture` element, but not the `img` element, I guess.

There's a [fixed bug](https://github.com/scottjehl/picturefill/issues/586) in Picturefill which is also not yet released.

Will this also polyfill/fix the `img` element, until Firefox 45 will be released?

**Comment by mike-engel** [comment]
Yeah, it should @thasmo. The PR in picturefill you linked to has actually been released in 3.x.

It doesn't seem like you're having an issue, but if you are, let me know. Otherwise, I'll close this issue in a couple days.
