### ISSUE TITLE
Firefox dynamic <source>

### ISSUE THREAD

**Issue by filipnathanel** [scottjehl/picturefill#615]
Hi,

I went through majority of closed and active issues to check whether the issue I am experiencing has not been raised already. Looks like it hasn't.

The issue concerns Firefox 43 ( therefore possibly all the FF with picture element 'enabled' ). It doesn't occur on chrome nor any browser that doesnt support picture element.

The issue is as follows:
A picture element with dynamically generated/changed sources will only serve the default image set on <img> additionally it won't react to the viewport changes. I can confirm that for the art direction approach only.

PLNKR:
http://plnkr.co/edit/cDZSjWzGgZEtUl6jeLGD?p=preview

Please help as reverting back to the picturefill 1 seems like a such a bad option.

**Comment by aFarkas** [comment]
@filipnathanel 

Could you please create simplified test case for us. This test case must include picturefill and must not include any other libraries.

Here is a starting point for generating dynamic picture element:
http://plnkr.co/edit/1DdyAPXtYtnnZcGSk2OR?p=preview

Make also sure, that you don't hit this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1170572

Which you can workaround by generating a `source` clone, **after**  changing the `media` attribute. (see also: https://github.com/aFarkas/lazysizes/blob/master/lazysizes.js#L329-L332)

**Comment by filipnathanel** [comment]
@aFarkas 

Thank you very much for a quick answer and a pointer to how workaround it.

The bug you have mentioned is exactly the bug I am hitting. I didn't find it previously on bugzilla.

If it still needed, the reduced test case is here: 
http://plnkr.co/edit/htsdgpe9BpusqcyBAcbW?p=preview

**Comment by aFarkas** [comment]
@filipnathanel 

So you are able to workaround this bug?

Do we need to address this?

Only way I can think of, is by adding the workaround to the mutation plugin and having an opt-in for this workaround.

**Comment by filipnathanel** [comment]
@aFarkas 

I have simply made all the media attributes in my application static. As much as it's optimal solution it works.

In terms of addressing this issue I would suggest to add a note to the 'gotchas' section.

Thank you.
