### ISSUE TITLE
Picturefill 3.0.1 + Safari 9.0.2 + with HiDPI display loads incorrect image size

### ISSUE THREAD

**Issue by NathanKleekamp** [scottjehl/picturefill#616]
When I use Picturefill 3.0.1 with Safari 9.0.2 on a non-HiDPI display, it works as expected at each of my breakpoints with Safari 9.0.2. However, on my MacBook Pro + Retina display, it loads a larger size. Here are a couple screenshots illustrating the issue:
- [HiDPI](https://www.dropbox.com/s/q5xktb2ydwcwnv6/Screenshot%202015-12-31%2008.50.14.png?dl=0)
- [non-HiDPI](https://www.dropbox.com/s/h21m9bvi0k8bd7v/Screenshot%202015-12-31%2008.51.26.png?dl=0)

Also, I believe I've isolated this to Picturefill because when I turn off js, everything loads correctly irrespective of pixel density.

I've noticed that this also happens in the iOS Simulator packaged with Xcode, too (iOS 9.2 (13C75), [iPad Air 2](https://www.dropbox.com/s/ddgw7yi0960cx4k/Screenshot%202015-12-31%2009.15.28.png?dl=0)). I don't have an iOS device to test this in reality, though.

Thanks for your work, btw. Aside from this issue (and what seems to FF bug) this works wonderfully in most instances.

**Comment by mike-engel** [comment]
Hey @NathanKleekamp, couple questions for ya:

1. Is this on the same browser on the same machine?
2. When testing, had you turned off/cleared your cache?
3. Does the picturefill demo site work for you?
4. If it does work for you, can you paste the code you're working with?

Thanks!

**Comment by NathanKleekamp** [comment]
Hi @mike-engel, 
1. Yes, same browser on the same machine. My colleague is using Safari 9.0 and could replicate the issue, switching back and forth between non-/HiDPI screens.
2. To test, I used a private browsing window
3. The demo site works. I mean, it's not that Picturefill doesn't work, it's just that it's loading a larger image than intended on HiDPI screens.
4. Here's the relevant markup:
```html
<img srcset="https://climate.america.gov/wp-content/uploads/sites/5/2015/12/AP_683678249046-copy-285x190.jpg 285w, https://climate.america.gov/wp-content/uploads/sites/5/2015/12/AP_683678249046-copy-630x354.jpg 630w, https://climate.america.gov/wp-content/uploads/sites/5/2015/12/AP_683678249046-copy-365x243.jpg 365w" sizes="(min-width:50em) 285px, (min-width:25em) 630px, 365px" alt="People gathering below solar panels installed on the roof of a building (© AP Images)">
```
If it helps, here's an [example page](https://climate.america.gov/category/smart-technology-finance/).

Thanks again,
Nathan

**Comment by aFarkas** [comment]
@NathanKleekamp 
Does your bug go away, if you use the following extension:
https://github.com/scottjehl/picturefill/tree/master/dist/plugins/intrinsic-dimension

I think the following code:
``(min-width:50em) 285px, (min-width:25em) 630px, 365px```

Should be something like:

``(min-width:50em) 285px, (min-width:25em) calc(100vw - 10px), 365px``

You can always set your image width using CSS.

**Comment by NathanKleekamp** [comment]
I had also considered setting the image width using CSS, but I didn't want to scale the images down. This is ultimately what I did, however, because it's fast and offered better cross-browser consistency anyway. It's not totally "fixed", but it works.

Not sure I should close this issue. It still seems like a bug to me, since my markup works as you'd expect with JS turned off. I'm happy either way.

Thanks!

**Comment by Razinsky** [comment]
Having the same issue here with Safari 9.0.2. Works perfectly with Chrome and Firefox.

**Comment by Designscheu** [comment]
I'm experiencing the same with Safari 9.0.2 on a Retina Mac, no issues in Chrome and Firefox.

**Comment by mike-engel** [comment]
@Razinsky have you tried the plugin @aFarkas mentioned?

**Comment by vvilhonen** [comment]
Same issue here, going to try with the plugin

**Comment by vvilhonen** [comment]
Ran out of time and went with 2.3.1 which worked

**Comment by aFarkas** [comment]
@vvilhonen and @Razinsky 

Does the bug go away if you use one of the following picturefill files:

http://cdn.rawgit.com/scottjehl/picturefill/pf-sizes-test/dist/pf-sizes.js
http://cdn.rawgit.com/scottjehl/picturefill/pf-sizes-test-2/dist/pf-sizes.js

Note: you need to remove your old picturefill and only include one of the files above to test it.

**Comment by vvilhonen** [comment]
@aFarkas works with both!

**Comment by strann** [comment]
@aFarkas I confirmed that both files linked to above fixed our related issue, any chance this can get into a patch release soon? Cheers.
