### ISSUE TITLE
iOS downloading double images, but not other browsers

### ISSUE THREAD

**Issue by derekshull** [scottjehl/picturefill#618]
On our test site we are implementing picturefill and every browser except iOS is loading the images as they should.  iOS is downloading the <img> as well as the source and we've not been able to nail down why.  Here is a webpagetest report for Safari desktop and iOS to show what it's doing.

Safari desktop: http://www.webpagetest.org/result/160104_WD_SZM/1/details/

iOS: http://www.webpagetest.org/result/160104_DT_T16/1/details/

Is anyone else seeing this on their implementations?  We put in a workaround for now on the site to make it work but really want picturefill to work.  We are using the latest and we are using the right syntax.

**Comment by aFarkas** [comment]
a) Try to use [newest version of pf](https://github.com/scottjehl/picturefill/tree/3.0/dist)
b) read and apply https://github.com/scottjehl/picturefill/issues/536 (*Mutilated IMG/PICTURE pattern*)

Does it still occur?

**Comment by derekshull** [comment]
Yes we are using v3.0.1 and it's still happening.

**Comment by aFarkas** [comment]
a) I linked to the current dev version, which is 3.0.2.
b) I still don't see the *Mutilated IMG/PICTURE pattern* on your site.

Please follow those links and read carefully.

**Comment by aFarkas** [comment]
@derekshull 

Is this bug still happening?

I see also that you have the following HTML:

```html
<picture>
    <source srcset="/media/1011/aspsf_mp_mainimage_01.webp" type="image/webp" media="(min-width: 1105px)">
    <source srcset="/media/1001/aspsf_m_mp_mainimage_01.webp" type="image/webp" media="(max-width: 1104px)">
    <source srcset="/media/1014/aspsf_mp_mainimage_01.jpg" media="(min-width:1105px)">
    <source srcset="/media/1002/aspsf_m_mp_mainimage_01.jpg" media="(max-width: 1104px)">
    <img srcset="/media/1014/aspsf_mp_mainimage_01.jpg" draggable="false">
</picture>
``` 

If you apply the *Mutilated IMG/PICTURE pattern* you markup would look something like this:

```html

<picture>
    <source srcset="/media/1011/aspsf_mp_mainimage_01.webp" type="image/webp" media="(min-width: 1105px)">
    <source srcset="/media/1001/aspsf_m_mp_mainimage_01.webp" type="image/webp">
    <source srcset="/media/1014/aspsf_mp_mainimage_01.jpg" media="(min-width:1105px)">
    <source srcset="/media/1002/aspsf_m_mp_mainimage_01.jpg">
    <img alt="" draggable="false">
</picture>
```

**Comment by mike-engel** [comment]
@derekshull Any updates on this?

**Comment by derekshull** [comment]
Not yet. I'll see if we can't implement this and see if it stops the double download

**Comment by jegtnes** [comment]
Closing this one for now. @derekshull, if this issue resurfaces even when using the mutilated pattern, please feel free to re-open.
