### ISSUE TITLE
No image displayed in Dolphin Mobile 9.4 on Galaxy S3

### ISSUE THREAD

**Issue by tobireif** [scottjehl/picturefill#620]
I have this in my HTML file:

```<img srcset="images/foo@1x.png 1x, images/foo@2x.png 2x"/>```

When I test the page (using https://app.crossbrowsertesting.com/ ) in Dolphin Mobile 9.4 on Galaxy S3, there's no image shown.

**Comment by tobireif** [comment]
There was an issue in my setup which I fixed, but now now there's another issue:
https://github.com/scottjehl/picturefill/issues/621

**Comment by aFarkas** [comment]
Does this mean, it's not a bug? If yes, please close.

**Comment by tobireif** [comment]
Yep, the right image is shown now, closing.
