### ISSUE TITLE
Large image displayed in Dolphin Mobile 9.4 on Galaxy S3

### ISSUE THREAD

**Issue by tobireif** [scottjehl/picturefill#621]
I have this in my HTML:

```<img srcset="images/foo@1x.png 1x, images/foo@2x.png 2x"/>```

In  in Dolphin Mobile 9.4 on Galaxy S3, the large image is shown, although (as far as I know) it's not a high-res device like eg Retina devices.

This test code loads the correct size, the loaded image fits the layout:

```<img src="images/foo@1x.png"/>```

but the srcset line from above loads the image that has twice the size - that's a problem in the layout :|

**Comment by aFarkas** [comment]
What does `devicePixelRatio` return? According to this, it's either 2 or 1.5 (http://mydevice.io/devices/#sortSmartphones).  If you don't use CSS to add image width/height, you can use the following plugin:
https://github.com/scottjehl/picturefill/tree/master/dist/plugins/intrinsic-dimension

Doesn't look as a bug. Please close if this helps.
