### ISSUE TITLE
IE7 error

### ISSUE THREAD

**Issue by tobireif** [scottjehl/picturefill#622]
The readme states "There are currently no known unsupported browsers".

I'm testing in IE7 (via https://app.crossbrowsertesting.com/ ), and it reports a "runtime error", pointing to picturefill.min.js line 5.

**Comment by tobireif** [comment]
This is my code:

```<img width="278" srcset="images/foo@1x.png 1x, images/foo@2x.png 2x"/>```

(No src attribute on the img tag as recommended in the picturefill readme.)

There's no image shown :|

**Comment by tobireif** [comment]
It's OK in IE8, I guess I'll forget about IE7, it being at version 11, and there's Edge already ..

**Comment by aFarkas** [comment]
See:
https://github.com/scottjehl/picturefill/blob/3.0/index.html#L261
