### ISSUE TITLE
Loaded image dimensions should be resolution-adjusted

### ISSUE THREAD

**Issue by lewisdorigo** [scottjehl/picturefill#625]
The spec notes:
> When an `img` element is available, it provides a paint source whose width is the image's density-corrected intrinsic width (if any), whose height is the image's density-corrected intrinsic height (if any), and whose appearance is the intrinsic appearance of the image.

So the dimensions that the image is displayed at should be adjusted based on the pixel density.

Picturefill, however, does not scale the image, which can cause issues with layout, where the image’s dimensions are/can not be set in CSS.

**Comment by aFarkas** [comment]
As explained in the corresponding PR (https://github.com/scottjehl/picturefill/pull/626). We already have this as an extension:
https://github.com/scottjehl/picturefill/tree/master/dist/plugins/intrinsic-dimension
