### ISSUE TITLE
Inherent width behavior not as described in doc

### ISSUE THREAD

**Issue by gerwitz** [scottjehl/picturefill#628]
#266 appears to have addressed issues of using the inherent size of a 1x to size a 2x. And the site's demonstration describes this behavior:

> The 2x source will be shown at the inherent width of the 1x source—so the two sources will occupy the same space in your layout, but the 2x source will be displayed at double the pixel density

But I am not seeing this on Safari 9.0.3 on OS X 10.11.3, as seen in the attached:

![screen shot 2016-02-02 at 13 32 50](https://cloud.githubusercontent.com/assets/73157/12749674/64b291e4-c9b2-11e5-89f5-dcffe0b1ed31.png)
![screen shot 2016-02-02 at 13 33 06](https://cloud.githubusercontent.com/assets/73157/12749676/66f2c9c4-c9b2-11e5-9525-243800485748.png)

(I wouldn't imagine that requesting the 1x only to determine the inherent size is the intended behavior, but the docs do seem to imply this will happen.)

**Comment by aFarkas** [comment]
Actually Safari has implemented this natively. And it works in your demo the 1x and the 2x image are displayed with the same size in your layout.

Also note: We do not download the 1x image to detect it's size. In fact we know that 2x has to be displayed with it's half size to match the 1x image.

You can try this by changing the example and replace the `2x`  with `1.5x` or `2.5x`. 

Does this answer your question.

**Comment by gerwitz** [comment]
You have a very puzzling interpretation of "displayed with the same size in your layout" considering those two screenshots!

I assume the behavior you described. I file this issue because I believe the documentation is wrong. This is demonstrated by the documentation itself which references a 2x image that is actually 1.6x, and thus occupies less space in the layout.

**Comment by aFarkas** [comment]
lol, you are right.

**Comment by mike-engel** [comment]
Docs improved in #630. Thanks for the info @gerwitz!
