### ISSUE TITLE
Image does not load in IE11 with Picturefill 3.0.1

### ISSUE THREAD

**Issue by saschask** [scottjehl/picturefill#633]
Hello,

I use the following code (simplified variant):

`<img class="logo" srcset="assets/img/header/logo.jpg, assets/img/header/logo_2x.jpg 2x" alt="logo" />`

When I inspect the rendered code in **IE11** on Windows 7 and based on **Picturefill 3.0.1**, I get the following:

`<img class="logo" alt="logo" srcset="assets/img/header/logo.jpg, assets/img/header/logo_2x.jpg 2x">`

 Unfortunately, IE11 is not able to load the correct image (no traffic in dev tools visible), in all other browsers (especially IE9-10) it is working.

When I go back to **Picturefill 2.3.1**, I get the following code which seems to work in IE11:

`<img width="215" class="logo" alt="logo" src="assets/img/header/logo.jpg" srcset="assets/img/header/logo.jpg, assets/img/header/logo_2x.jpg 2x">`

The obvious difference in the second/working variant is the dynamically added `src` attribute. Could this be the only reason or is there something else that makes the difference?

**Comment by aFarkas** [comment]
What does you JS console say in IE11?

**Comment by saschask** [comment]
There's absolutely no output in the console but I just realized that 3.0.1 works properly in IE11 when I resize the viewport after the site loading. In my site the libs are loaded first, afterwards the HTML is rendered dynamically so actually there sould not be any issues regarding the loading order.

Seems like an initial check for the current viewport or something like this is missing...

**Comment by aFarkas** [comment]
> afterwards the HTML is rendered dynamically

You mean you are rendering the HTML with JS (react, handlebars etc.)???

If yes,

You either need to explicity call `picturefill();` or use the [mutation plugin](https://github.com/scottjehl/picturefill/tree/master/dist/plugins/mutation)

**Comment by saschask** [comment]
Yes, I use https://github.com/janl/mustache.js/.

Okay, I will give the plugin a try. Thanks!

**Comment by saschask** [comment]
Well, I'm using the `picturefill();` variant now since I like one single call more than loading some additional KB for another lib.

So... thanks for your (fast) support :-)
