### ISSUE TITLE
Call picturefill in Ajaxify website

### ISSUE THREAD

**Issue by Allmedialab** [scottjehl/picturefill#644]
Hi,
What is the best way to initialize/ call the picturefill script on a Ajaxify driven website like this:
www.responsbuiten.yourweblab.nl

Picturefill works on load, but fails on loading content with Ajaxify. (When you click to a other page after loading the first one).
It works in Edge on windows 10, but not in IE Edge and all others in windows 7 64bits.

I only implemented the picturefill script on the first 3 pages: HOME, MENU and RESERVEREN
The responsive images are only the background image for the moment and on the HOME, MENU and RESERVEREN page you can see the pixel width on the images for testing.

Regards and thanks,
David

**Comment by jegtnes** [comment]
Hey @Allmedialab,

Picturefill exposes a global `picturefill()` function. You can call this after any DOM mutations. For more information, see the Picturefill JavaScript API section [in the docs](http://scottjehl.github.io/picturefill/).

Hope that helps! :bomb:

**Comment by Allmedialab** [comment]
Thanks jegtnes! This is what I did now, but I can't get it working.
[head.zip](https://github.com/scottjehl/picturefill/files/146592/head.zip)

**Comment by jegtnes** [comment]
I'm not sure what's happening with your code nor how it loads in the new content, but most likely you are calling it before the new DOM is fully ready.

I'm not sure how you load in the content, but if at the bottom of your loaded content you add
```
<script type="text/javscript">
if (typeof picturefill == 'function') { 
  picturefill(); 
}
</script>
```
does that work?

Alternatively you can try adding the Picturefill Mutation plugin which detects DOM changes automatically—keep in mind this doesn't work with IE8 and below.
http://scottjehl.github.io/picturefill/dist/plugins/mutation/pf.mutation.min.js

**Comment by Allmedialab** [comment]
Thanks for helping me! Unfortunately it only works now and then. I refreshed browser memory in IE Edge on windows 7 64 and load the Home page then it works when I click to Menu it works, but then it stops working.

**Comment by jegtnes** [comment]
Edge, you say? Which version? In Edge 13 (latest stable) there's full native support for both `<picture>` and `srcset`.

**Comment by Allmedialab** [comment]
Yes I know this is Edge in windows 7. In Windows 10 the real Edge works.

**Comment by jegtnes** [comment]
Are you sure that's Edge? I thought Edge was a Windows 10 only thing.

**Comment by Allmedialab** [comment]
![edge-on-windows-7](https://cloud.githubusercontent.com/assets/2815617/13325993/693a0d34-dbe4-11e5-8b41-cef6f1e0e882.jpg)

**Comment by Allmedialab** [comment]
When I load the site on windows IE 10 it work, but you see the source file loaded first and then suddenly it loads the proper image. (in milliseconds!).

**Comment by aFarkas** [comment]
@Allmedialab 
The image swap is happening because you are using a `src` on your image.

**Comment by Allmedialab** [comment]
Thanks for that!

How do I implement the src in this code example? I cant get it on the proper place.
Of course I looked at the example on the github page, but still don't get it error free!

<picture>
<source
media="(max-width: 1024px)"
sizes="(max-width: 1024px) 100vw, 1024px"
srcset="
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_4_3,c_fill__c_scale,w_1024.jpg 1024w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_4_3,c_fill__c_scale,w_2048.jpg 2048w">
<img
sizes="(max-width: 1920px) 100vw, 1920px"
srcset="
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_200.jpg 200w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_485.jpg 485w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_697.jpg 697w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_879.jpg 879w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1044.jpg 1044w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1195.jpg 1195w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1334.jpg 1334w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1461.jpg 1461w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1586.jpg 1586w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1712.jpg 1712w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1823.jpg 1823w,
header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1920.jpg 1920w"
src="header-gulpen-cat-dog_zfhoch/header-gulpen-cat-dog_zfhoch_ar_16_9,c_fill__c_scale,w_1920.jpg"
alt="cat and dog">
</picture>

Kind regards,

David

**Comment by Allmedialab** [comment]
Solved it by putting fake text in the src. My suggestion is to start the documentation with the known fact that the code suggested doesn't validate w3.org. That will save a lot of people a lot of time!

Kind regards,

David

**Comment by rjgotten** [comment]
> @Allmedialab 
> But Edge is the standard browser like it says.

That's the IE document mode selector. By default the document mode is set to the latest supported version, which will be the browser's actual engine version. The latest supported version is also called the **edge version**.

So it's not referring to Edge as the product name for Microsoft's new browser. That browser is indeed only available on Windows 10, btw.
