### ISSUE TITLE
Download links outdated because RawGit links are cached permanently

### ISSUE THREAD

**Issue by Frenzie** [scottjehl/picturefill#648]
Also that version doesn't seem to be functional (probably on account of some fixed bug), but that's how I noticed. Anyway, cool script. :+1:

**Comment by mike-engel** [comment]
Hey @Frenzie, where are you seeing the download link? The one from https://scottjehl.github.io/picturefill is pointing to 3.0.2.

**Comment by Frenzie** [comment]
Yes, that's the page.

The links in question are
Full:
https://cdn.rawgit.com/scottjehl/picturefill/master/dist/picturefill.js
Minimized:
https://cdn.rawgit.com/scottjehl/picturefill/master/dist/picturefill.min.js

The full starts with

```

/*! picturefill - v3.0.2 - 2016-02-12
 * https://scottjehl.github.io/picturefill/
 * Copyright (c) 2016
https://github.com/scottjehl/picturefill/blob/master/Authors.txt;
Licensed MIT
 */
/*! Gecko-Picture - v1.0
 * https://github.com/scottjehl/picturefill/tree/3.0/src/plugins/gecko-picture
 * Firefox's early picture implementation (prior to FF41) is static and does
 * not react to viewport changes. This tiny module fixes this.
 */

```


while the min starts with
```

/*! Picturefill - v3.0.1 - 2015-09-30
 * http://scottjehl.github.io/picturefill
 * Copyright (c) 2015
https://github.com/scottjehl/picturefill/blob/master/Authors.txt;
Licensed MIT
 */

```

**Comment by Frenzie** [comment]
Maybe point it to
https://raw.githubusercontent.com/scottjehl/picturefill/master/dist/picturefill.min.js
isntead?

**Comment by Frenzie** [comment]
Ah, I see now. RawGit is something else entirely.

https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions

> RawGit is not associated with GitHub in any way. Please don't contact GitHub asking for help with RawGit.

> […]

> Requests to `cdn.rawgit.com` are routed through MaxCDN's super fast content delivery network, and are cached **permanently** at the CDN layer based on the URL. This results in the best performance and reduces load on RawGit and on GitHub, but it means that reloading won't fetch new changes from GitHub.

Note the permanently. That means it'll never change after the first time it's loaded.

> The CDN caches files permanently based on their path. It ignores query strings. This is done to improve performance and to make it possible for the CDN to handle massive amounts of traffic without causing excessive load on RawGit or GitHub's servers.

> To ensure that the CDN always serves the version of the file you want, use a git tag or commit hash in the file's path instead of a branch name, and update the URL if you push a new version of the file.

**Comment by mike-engel** [comment]
Hey @Frenzie. I'm not sure why, but loading those those links result in 3.0.2 for me. Just to make sure, you've cleared your cache?

Either way, it's probably not a good idea for us to be pointing rawgit to master. I'll work on updating the link this week, when I get some time. If you'd like to throw a PR in the meantime that uses a tag instead of a branch, we'd welcome that too.

**Comment by Frenzie** [comment]
Yeah, that, a couple of different browsers, and curl. ;) And like the stuff I quoted said, even if it weren't a problem now, it'd be one soon.

```
$ curl -s https://cdn.rawgit.com/scottjehl/picturefill/master/dist/picturefill.min.js | grep v3
/*! Picturefill - v3.0.1 - 2015-09-30
```

I'll send a PR later to change the links to these

https://cdn.rawgit.com/scottjehl/picturefill/3.0.2/dist/picturefill.js
https://cdn.rawgit.com/scottjehl/picturefill/3.0.2/dist/picturefill.min.js
