### ISSUE TITLE
Set high-res images when the page is zoomed in

### ISSUE THREAD

**Issue by tobireif** [scottjehl/picturefill#650]
I use Picturefill on a site, the high-res images are shown on high-dpi screens.

Would it be possible for Pitcurefill to also show the high-res images when the page is zoomed in?

**Comment by mike-engel** [comment]
Hi @tobireif. Picturefill (and larger, `picture` and `srcset`) work off of media queries. From what I can tell, there's no definitive media query for device zooming, so there would be no way to target a specific image for a specific zoom level. You can see the various types of media queries with this handy [media query test page](http://mediaqueriestest.com/) and see how the values change when you zoom into the page.

I'm going to close this issue. If you have more questions, please let us know. Thanks!
