### ISSUE TITLE
Doesn't work with CSP?

### ISSUE THREAD

**Issue by triblondon** [scottjehl/picturefill#652]
I've been [looking into](https://github.com/Financial-Times/polyfill-service/issues/357#issuecomment-216267691) removing any code that violates default [CSP restrictions](https://developer.chrome.com/extensions/contentSecurityPolicy) from the polyfill service and came across this in Picturefill:

```
/*jshint evil:true */
try{
    cssCache[css] = new Function("e", buildStr(css))(units);
} catch(e) {}
/*jshint evil:false */
```

This will mean that any site using picturefill cannot also impose default CSP rules.  Has this been considered at all?  Any thoughts on whether this is a problem and what a solution might be?

**Comment by mike-engel** [comment]
Hey @triblondon, sorry for the super long delay. I personally haven't considered it, but it seems like something that we should do. I don't, however, have a good alternative. Do you have any other solutions?

**Comment by triblondon** [comment]
I raised this as part of an effort to purge the polyfill service of this pattern, and dug into it quite deeply.  I'd recommend reading https://github.com/Financial-Times/polyfill-service/issues/357.  In your case an alternative does seem achievable, but you'd probably have to change the way your parsing function works to avoid the eval.

**Comment by mike-engel** [comment]
Thanks @triblondon. It seems to me that this could be replaced by a closure that returns an actual function, rather than a function string that needs to be evaluated. I'm also not familiar with tricks like this, so I could be wrong. If you have any thoughts, let me know.

**Comment by triblondon** [comment]
I have no specific suggestions but your line of thinking seems right :-)

**Comment by Mouvedia** [comment]
- [ ] refactor buildStr
- [ ] replace with an IIFE
