### ISSUE TITLE
Is 'picturefill' support for retina ready?

### ISSUE THREAD

**Issue by maheshwaghmare** [scottjehl/picturefill#653]
To use `piturefill` we need to pass the image dimension `500w` / `1024w` etc. as per required. But, 

**1. Can I use this for `Retina Ready Images`?**

I found below media quries to check the devices is retina ready?

```
@media
only screen and (-webkit-min-device-pixel-ratio: 2),
only screen and (   min--moz-device-pixel-ratio: 2),
only screen and (     -o-min-device-pixel-ratio: 2/1),
only screen and (        min-device-pixel-ratio: 2),
only screen and (                min-resolution: 192dpi),
only screen and (                min-resolution: 2dppx) { 
  
  /* Retina-specific stuff here */

}
```

Source: `https://css-tricks.com/snippets/css/retina-display-media-query/#post-17757`

**How Can I use these media quries???**

-----

2. We will also be able to set `1x` or `2x` as below:

```
<picture>
  <source srcset="examples/images/large.jpg, examples/images/extralarge.jpg 2x" media="(min-width: 800px)">
  <img srcset="examples/images/small.jpg, examples/images/medium.jpg 2x" alt="…">
</picture>
```

Reference URL: `https://scottjehl.github.io/picturefill/#using-media-and-srcset`

How it works for WordPress?

**Comment by jegtnes** [comment]
Hey @maheshwaghmare,

Picturefill's job is to make responsive images work in browsers that don't support it. If all you want to do is send high-density images to high-density displays like Retina displays and normal-density images to normal-density displays, the correct responsive image syntax is 
`<img srcset="cat.jpg, cat-hd.jpg 2x, cat-ultra-hd.jpg 3x alt="kitty at my foot and I want to touch it">`
[as per the docs](http://scottjehl.github.io/picturefill/#img-srcset).

If you want to do art direction [cropping the image differently at different screen widths](http://scottjehl.github.io/picturefill/#using-picture) it would be easier to just use the media query for the widths and leave the density detection to srcset:

```
<picture>
  <source srcset="cat-head.jpg, cat-head-hd.jpg 2x, cat-head-ultra-hd.jpg 3x" media="(min-width: 500px)">
  <source srcset="full-cat.jpg, full-cat-hd.jpg 2x, full-cat-ultra-hd.jpg 3x" media="(min-width: 800px)">
  <img srcset="cat-head-small.jpg" alt="kitty at my foot and I want to touch it">
</picture>
```

I'm afraid I don't know enough about the WordPress plugin to help you out here. I know if you're on WP 4.4 or above and your theme supports it, [it will generate automatic responsive images using `srcset`](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) for you.

Does that answer your question? 😺

**Comment by jegtnes** [comment]
Hey @maheshwaghmare, did you get anywhere with this?

**Comment by jegtnes** [comment]
Going to close this for now, feel free to re-open it later if you need further clarification, @maheshwaghmare.
