### ISSUE TITLE
Picturefill is no longer showing up in Bower search

### ISSUE THREAD

**Issue by chrisshattuck** [scottjehl/picturefill#655]
Did Picturefill get withdrawn from Bower? It doesn't appear to show up on http://bower.io/search/?q=picturefill.

**Comment by jegtnes** [comment]
Hey there @chrisshattuck – thanks for letting us know, but nobody's unpublished Picturefill to the best of my knowledge. Possibly a temporary Bower hiccup? Looks like it's back:
<img width="1025" alt="" src="https://cloud.githubusercontent.com/assets/1315463/15299015/bc3b1214-1ba2-11e6-997c-83af28bf4456.png">

If it disappears again let us know!

**Comment by chrisshattuck** [comment]
Indeed! Thank you!
