### ISSUE TITLE
how to "avoid loading broken images" via picturefill.

### ISSUE THREAD

**Issue by Femina** [scottjehl/picturefill#658]
I attempted building up directive , on image load error need to display default image. But, it works well with normal <img> tag not with picturefill's <span> element (dynamic <img> ) case. Kindly check on it.

**Comment by jegtnes** [comment]
Hey @Femina,

I'm not 100% sure what you mean here. Could you elaborate a bit more? What's the expected behaviour, what is the actual behaviour, and which browsers are you seeing it happen on? If you could provide a reduced test case in a JSBin/CodePen that'd be very helpful :)

**Comment by jegtnes** [comment]
Going to close this for now – feel free to re-open this later with more details if you're still having problems, @Femina.
