### ISSUE TITLE
Image won't scale in Safari

### ISSUE THREAD

**Issue by 123ndy** [scottjehl/picturefill#662]
When running the code below in Safari 9.0.3, the image changes in the breakpoints, but it won't scale to the viewport size. The 1920px wide image stays 1920px wide even if I make the screen narrower (and I want it to scale with the viewport). It works in Chrome.

I am using Picturefill 3.0.2 with React 15.1.0

What am I doing wrong here?

```
import 'picturefill'
<picture>
   <source srcSet="/images/big-1920.png 1920w" media="(min-width: 1441px)" />
   <source srcSet="/images/medium-1440.png 1440w" media="(min-width: 1025px)" />
   <img srcSet="/images/small-1024.png 1024w" draggable="false"  alt="product image"/>
</picture>
```

**Comment by mike-engel** [comment]
The `media` attribute only specifies which image to select. You'll need to use CSS to actually scale the image to the size you want. Hope that helps, let me know if there's something I didn't catch in your question.

**Comment by 123ndy** [comment]
Thanks @mike-engel, but why does it work in Chrome, but not Safari (the CSS is the same on both)?

**Comment by mike-engel** [comment]
@123ndy If you're talking about the latest versions of each, then `picture` is natively supported in each, and picturefill isn't actually doing anything at that point. Are you testing with the latest browsers, or something earlier?
