### ISSUE TITLE
Touch Support on mobile devices - Zoom Option

### ISSUE THREAD

**Issue by mod667** [scottjehl/picturefill#663]
The script work well to the most mobile devices, swipe it's ok, but when some one try to zoom the image the script recognizes the action as a swipe and not as a zoom....
Some one has any idea to implement this issue ?
cheers !

**Comment by mike-engel** [comment]
Hey @mod667, picturefill doesn't concern itself with gestures of any kind. Are you using another library that may be causing the issue?
