### ISSUE TITLE
Safari calculating `em` media queries oddly

### ISSUE THREAD

**Issue by aaronbushnell** [scottjehl/picturefill#666]
This might be a known issue, but I didn't see anything about it. Excuse me if it is! 😃 

When using the following code in Safari:
```html
<picture>
  <source srcset="large.jpg" media="(min-width: 40em)">
  <source srcset="medium.jpg" media="(min-width: 20em)">
  <img src="small.jpg" alt="Sample">
</picture>
```

```css
html {
    font-size: 20px;
}
```

I noticed Safari is miscalculating the image breakpoints. Chrome and Firefox are using the standard `[em]*16=[px value]`. However, Safari is calculating the `em`s based on the `font-size` declared on the `html` element.

Chrome and Firefox appear to interpret this block as:
```html
<picture>
  <source srcset="large.jpg" media="(min-width: 640px)">
  <source srcset="medium.jpg" media="(min-width: 320px)">
  <img src="small.jpg" alt="Sample">
</picture>
```

But Safari appears to be multiplying the `em` by the `20px` and interpreting this as:
```html
<picture>
  <source srcset="large.jpg" media="(min-width: 800px)">
  <source srcset="medium.jpg" media="(min-width: 400px)">
  <img src="small.jpg" alt="Sample">
</picture>
```

Here's a Codepen of this issue: http://codepen.io/aaronbushnell/full/kXKJbm

Is this intentional? Is Safari the buggy one or is Chrome/Firefox misinterpreting the breakpoints?

**Comment by mike-engel** [comment]
Hey @aaronbushnell, which version of safari is this?

**Comment by aaronbushnell** [comment]
Hey @mike-engel, I'm seeing this in the current version of Safari for El Capitan — 9.1.2 (11601.7.7). I also see this in Safari on iOS 9.3.

**Comment by aaronbushnell** [comment]
Here's a screenshot of the issue in iOS 9.3
![iOS screenshot](https://cl.ly/011w0M1e1H0R/Screen%20Shot%202016-08-25%20at%201.26.13%20PM.png)

**Comment by aFarkas** [comment]
This is a webkit bug. It also produces double downloads, the preload parser starts the large image and after CSS is loaded the medium image is also loaded (Note: Safari doesn't even abort the other request.).

This seems to be a known issue:
https://bugs.webkit.org/show_bug.cgi?id=159635

**Comment by aaronbushnell** [comment]
Ah, thanks for the heads up @aFarkas! I think I'm good here. I'll use `px` going forward for better precision.
