### ISSUE TITLE
How picturefill works with IE9

### ISSUE THREAD

**Issue by sanketj14** [scottjehl/picturefill#667]
Hi,

I see that picturefill needs video tag workaround to work with IE 9, but then how it picks up the srcset? I am really confused as when I inspected on IE 9, I am seeing the src attribute different from srcset I've set, it is picking up src from source tags that are already hidden in IE 9. can you please clarify how it works for IE 9. Thanks in advance!

**Comment by mike-engel** [comment]
Hi @sanketj14, can you provide a code sample?

**Comment by sanketj14** [comment]
Thanks for replying @mike-engel , here's the code sample I'm using.

`<picture>

<source srcset="//cdn.optcentral.com/optportal/catalog/{{meta.companyId}}/large/{{value.image}}" media="(min-width: 768px) and (max-width: 991px)">
<source srcset="//cdn.optcentral.com/optportal/catalog/{{meta.companyId}}/large/{{value.image}}" media="(min-width: 768px) and (max-width: 1200px)">
<source srcset="//cdn.optcentral.com/optportal/catalog/{{meta.companyId}}/large/{{value.image}}" media="(min-width: 768px)">
<source srcset="//cdn.optcentral.com/optportal/catalog/{{meta.companyId}}/large/{{value.image}}" media="(max-width: 768px)">




<![if !IE 9]>
<img style='width:100%;' srcset="//cdn.optcentral.com/optportal/illustrations/{{meta.companyId}}/large/notavailable.jpg">
<![endif]>
</picture>`

I made two conditional browser tags, one is specifically for IE9 and second is for other browsers.
this works fine for all the other browsers, except IE9. In case of IE9, `data-fallback` property in IE9 conditional tag is supposed to replace the `srcset` url if the image is broken.
but it shows broken image even though `srcset` is being replaced with fallback. and I see `src` attribute in inspector with the broken image url, which I couldn't change despite all my efforts.
am I missing something here? how the `src` is set to broken image even though `srcset` is changed to fallback?

**Comment by mike-engel** [comment]
@sanketj14 if you're modifying the source after picturefill has run, you'll want to run `picturefill()` so that it re-evaluates the sources.

**Comment by sanketj14** [comment]
@mike-engel Nice catch! since I'm working in SPA, picturefill runs before I modify source. I thought it has to do something with IE cause it worked fine on all other browsers.  thanks a lot, you saved the day, sir! just one more thing, picturefill will evaluate only the srcset in img tag in case of IE9,  it won't look for the source tags above, right?

**Comment by mike-engel** [comment]
I believe it will, but you can check functionality on the picturefill demo site. Glad things worked out for you!
