### ISSUE TITLE
Typo in recommended usage section

### ISSUE THREAD

**Issue by aparajita** [scottjehl/picturefill#668]
Reference: [Getting Started](http://scottjehl.github.io/picturefill/#getting-started)

In the "Recommended Usage" section, the word "shiv" is used in the code sample and in the note below the code sample.

I think you mean "shim". "shiv" is a knife or razor used as a weapon. "shim" fills up a space to make parts fit.

**Comment by mike-engel** [comment]
@aparajita: Would you mind making a PR to fix this?

**Comment by albell** [comment]
@aparajita You're correct that the word "shiv" was originally a typo. John Resig made a funny all the way back in, um... <a href="http://ejohn.org/blog/html5-shiv/">2002</a>. Nowadays "shiv" is commonly used interchangeably with "shim", partly as a joke about sticking a knife in old browsers. See:

https://www.paulirish.com/2011/the-history-of-the-html5-shiv/

In other words, it passes the 'Google Search Test' with flying colors.
