### ISSUE TITLE
JSPM support

### ISSUE THREAD

**Issue by davidpronk** [scottjehl/picturefill#670]
I just noticed when installing picturefill as a dependency using JSPM I end up with a 17,9 MB of code + examples. This can be prevented by adding some JSPM config to the `package.json` so JSPM only retrieves the contents of `dist`. Setting `jspm.directories` to `"lib": "dist"` does the trick.
@scottjehl: should I make a PR for this change?

**Comment by mike-engel** [comment]
Yes, please make a PR. Thanks!
