### ISSUE TITLE
Render-Blocking CSS because of Picturefill?

### ISSUE THREAD

**Issue by martiniert** [scottjehl/picturefill#672]
I'm using picturefill together with lazysizes.js and everything works great, the only problem I run into is a "render-blocking CSS" penalty by PageSpeed. 

I tried to break the problem down to find out where exactly the problem happens, so I created the 3 basic example webpages to illustrate my problem (with picturefill 3.0.2):

Page with images, no srcset attribute, only regular src and picturefill:
http://pagespeed-nosrcset.slople.com/
PageSpeed result: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpagespeed-nosrcset.slople.com%2F 
**-> No problem**

Page with images with srcset attribute and picturefill:
http://pagespeed-srcset.slople.com/ 
PageSpeed result: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpagespeed-srcset.slople.com%2F 
**-> Penalty for render-blocking CSS**

Page with images with srcset attribute, without picturefill:
http://pagespeed-srcset-nopicturefill.slople.com/
PageSpeed result: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpagespeed-srcset-nopicturefill.slople.com%2F 
**-> No problem**

So what happens is that if I use srcset-attributes together with Picturefill, I get a PageSpeed penalty for render-blocking CSS. Is that actually a problem within Picturefill or am I just missing something?

**Comment by aFarkas** [comment]
you can put the picturefill script above the stylesheet to remove this. 

This has nothing to do with picturefill itself.

**Comment by martiniert** [comment]
Thanks for your response, I just tried that here:
http://pagespeed-srcset-picturefillbeforecss.slople.com/

Seems to be the same result, although the picturefill script is now above the stylesheet?

**Comment by aFarkas** [comment]
@martiniert 
Then I'm overasked. The stylesheet itself is actually always blocking and always delays the DOMContentReady event. IE, FF and newer versions of Chrome do in fact render the content above the stylesheet before it is loaded.

But this doesn't explain why sometimes this is detected as blocking and on other situation it isn't. Maybe ask some pagespeed guy?

**Comment by martiniert** [comment]
@aFarkas for pagespeed, render-blocking means there's an element above the fold (as in the top 800px of the page) which needs css to be displayed, therefore the rendering is blocked because the browser needs to load the css before it can display the first 800px correctly.

In this case, the css file doesn't contain anything useful, therefore it also can't be render-blocking for pagespeed and how you see, it only appears with using picturefill. I tried asking some pagespeed guys, but they also couldn't help me that's why I hoped to find someone with similar problems on here.

I also tried to use a different script, e.g. jquery, to see if the problem is bound to picturefill or just to load an additional script in general. The error doesn't appear with loading jquery the same as picturefill:

http://pagespeed-srcset-nopicturefill-jquery.slople.com/
PageSpeed result: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpagespeed-srcset-nopicturefill-jquery.slople.com%2F

**Comment by aFarkas** [comment]
@martiniert 
Could you please change your the picturefill/jquery test script with a script with the following content:

```js
document.querySelector('img').src = '//placehold.it/680x680';
```

And test again.

**Comment by martiniert** [comment]
@aFarkas nice idea! Looks like we're getting closer, I put together a test site with your code:
URL: http://pagespeed-srcset-scripttest.slople.com/
PageSpeed result: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpagespeed-srcset-scripttest.slople.com%2F&tab=mobile

The css is now shown as render-blocking. I guess that's what picturefill does too, changing the src of the images, right? For some reason this gives us a render-blocking css, although there's only one line it which does not apply to any elements..

**Comment by albell** [comment]
> In this case, the css file doesn't contain anything useful,

Whether CSS in a `<link>` is render-blocking or not doesn't have anything to do with its "usefulness". Historically, **all** link tags blocked render, regardless of where they appeared in markup. Now it's location dependent in some modern browsers, and `<link>`ed stylesheets only block render of markup underneath them. See:

https://jakearchibald.com/2016/link-in-body/

So then this is a PageSpeed bug. File a bug with them? Your CSS at the bottom of the body shouldn't be render blocking in latest Chrome. Seems like you're in some weird corner case of the PageSpeed algorithm. Or just try to wiggle around it? Try putting a `<link>` in the head with a selector that actually matches something above the fold? This also might be an issue with how PageSpeed is internally defining "above the fold", so experiment with layout?

**Comment by aFarkas** [comment]
@albell 
Pretty sure, that pagespeed uses an old webkit or blink engine to do its tests (similar to phantomjs).

This means, that the stylesheet is hoisted and blocks the JS which changes layout above the fold by changing the `src`.

At the end it doesn't matter, it only makes sense with old browsers without `srcset`/`picture` support.

**Comment by martiniert** [comment]
thanks @albell and @aFarkas for your responses.

On the real site, we already use above-the-fold css that is loaded inline and everything works like a charm, we only run into problems with using said srcset/picturefill-combination, so it really seems to be a PageSpeed bug with interpreting this case.

Shall I close this issue now, as it isn't directly linked to picturefill?

Thanks for your help anyway!
