### ISSUE TITLE
Error in IE 11 when lazy loading images

### ISSUE THREAD

**Issue by tedw** [scottjehl/picturefill#675]
It appears that omitting the `srcset` attribute in favor of `data-srcset` (for lazy loading purposes) causes an error in IE 11.

Details here http://stackoverflow.com/questions/39953594/picturefull-lazysizes-unable-to-get-property-push-in-ie

Will try to work on a PR.

**Comment by aFarkas** [comment]
This bug is not a `picturefill` bug. It is provoked by bad markup:

The `source` elements have a lazyload/lazypreload class which shouldn't be added and the `img` has the following class:

```html
<img class="picturefill__image class="lazyload lazypreload" />
```

**Comment by tedw** [comment]
I still noticed the same issue using valid markup. Will provide a test case when I have time.

**Comment by aFarkas** [comment]
Please provide a test case.
