### ISSUE TITLE
Idea: reduced version without support for oldest browsers

### ISSUE THREAD

**Issue by brendanfalkowski** [scottjehl/picturefill#677]
Wondering if there's any chatter about bumping Picturefill browser support to slim it down for the browsers we actually see in wild these days.

On a few projects the lowest we're supporting is IE 11+, Android 5+, and iOS 9+ because older browsers add up to < 1%. This lines up sort of close to native support for `<picture>` and `srcset`:

http://caniuse.com/#search=picture
http://caniuse.com/#search=srcset

Realistically we still need Picturefill for IE11 and some Android today, but the vast majority of our users come from browsers that don't need the polyfill.

Alternatively, is there an acknowledged feature test we can use to conditionally load the full version so we're still providing baseline support?

**Comment by aFarkas** [comment]
Reducing the browser compatibility doesn't give us much size improvements. Also I don't know where you want to split/reduce the functionality. Do you want it to split between `picture`/`srcset`?

Maybe you should simply load the full polyfill always conditionally and you are done.

**Comment by scottjehl** [comment]
Good question, @brendanfalkowski. The timing's right to keep considering this. 

@aFarkas would know best how much of the script is catering to browsers that could increasingly just get a fallback. We have certainly been doing that more and more in our projects anyway. I find `picture` is most often the feature that causes us to bring in the polyfill, since it tends to be more tightly integrated with a site's layout than srcset. If a polyfill for `picture` alone was dramatically lighter, that could be worth splitting out.

**Comment by brendanfalkowski** [comment]
@aFarkas @scottjehl — Thanks for considering, I figured slimming it wouldn't save much but I care about the performance side of loading a polyfill users may not need.

I tried to find the feature test for `picture` + `srcset` + `sizes` but I wasn't sure how to take the code around `pf.supPicture` and use that to write a cuts-the-mustard function. My JS skills are holding me back here. I know Modernizr has a test for this too but that's another script.

I was thinking we could improve the docs by providing that mustard test in plain JS, so the recommendation would be to conditionally load the polyfill going forward.

The other day I noticed an old old project is still using https://github.com/scottjehl/Respond and it'd be nice if people adding PictureFill today had that feature test built in so it would stop applying on its own.

**Comment by albell** [comment]
@brendanfalkowski The feature detects in 3.x are the result of a lot of painstaking refinement over the years. Take a look at:

https://github.com/scottjehl/picturefill/blob/master/src/picturefill.js#L890-L937

There's no one-liner that captures all of the nuances here, but if you are hypsensitive to file size and want something quick and dirty you could just combine the basic checks for srcset, sizes and picture, e.g.

````
var image = document.createElement( "img" );
if (!("srcset" in image) || !("sizes" in image) || !(window.HTMLPictureElement) {
// load the polyfill here
}
````

**Comment by brendanfalkowski** [comment]
@albell — Thanks, I saw the edge cases around the basic checks. I'll try out the micro mustard test tonight.

Would a PR to add this into the docs be accepted? Or am I on the fringe with this line of thinking?

**Comment by aFarkas** [comment]
> I figured slimming it wouldn't save much but I care about the performance side of loading a polyfill users may not need.

Yes, for this you don't need to change picturefill. In general if `window.HTMLPictureElement` and `sizes` is supported everything is supported. For polyfilling we need to do more fine grained test.

In general the best way to load picturefill is to include the following script before any other blocking includes (This means even before your stylesheet.).

```js
<script>
function loadJS(u){var r=document.getElementsByTagName("script")[0],s=document.createElement("script");s.src=u;r.parentNode.insertBefore(s,r);}

if(!window.HTMLPictureElement || !("sizes" in document.createElement('img'))){
	document.createElement('picture');
	loadJS("picturefill.min.js");
}
</script>
```

> Would a PR to add this into the docs be accepted? Or am I on the fringe with this line of thinking?

Would be great.

**Comment by JohnPennington** [comment]
Here's a version that loads asynchronously that seems to be working well for me.  
`
<script type="text/javascript">
	(function() {
		// Only installs picturefill polyfill script for browsers where picture element is not supported.
		if(!window.HTMLPictureElement || !("sizes" in document.createElement('img'))){
			document.createElement('picture');
	                var s = document.createElement("script"); 
	                s.type = "text/javascript";
	                s.async = true;
	                s.src = document.location.protocol + "//www.domain.com/js/picturefill.min.js')}";
			var r=document.getElementsByTagName("script")[0];
			r.parentNode.insertBefore(s,r);
		}
	})();
</script>

`

**Comment by aFarkas** [comment]
@JohnPennington 
How is this better than the script that I posted before. I just see more unnecessary clutter.

@scottjehl 
I wrote [this](https://gist.github.com/aFarkas/dcc87311232987591a16) some time ago. If you like this I can change the src selection algorithm to do exactly this.
