### ISSUE TITLE
Publish picturefill 3.0.3 to NPM

### ISSUE THREAD

**Issue by kgcreative** [scottjehl/picturefill#678]
https://www.npmjs.com/package/picturefill

I see the latest release is 3.0.2, not the current 3.0.3 release. Is there a plan to publish 3.0.3 to NPM?

**Comment by thasmo** [comment]
Why isn't it available via npm?

**Comment by thasmo** [comment]
:(

**Comment by kgcreative** [comment]
💥

**Comment by daviddelusenet** [comment]
+1

**Comment by intastella** [comment]
+1

**Comment by benurb** [comment]
Any news on this? @scottjehl @jegtnes

**Comment by jegtnes** [comment]
Apologies for this, folks; a while back we bumped a version without checking that the people with the appropriate npm publishing privileges were available to flick the switch. I think @wilto and @scottjehl are able to do this.

**Comment by glukki** [comment]
up!

**Comment by alaz** [comment]
+1

**Comment by thasmo** [comment]
Seems like there haven't been any code-changes anyway afaik.

**Comment by alaz** [comment]
I was just checking out of curiosity if anyone is still alive here 😄 
(my [previous test](https://github.com/scottjehl/picturefill/pull/686) failed)

**Comment by branneman** [comment]
This issue is almost a year old now 😡

Why hasn't 3.0.3 been published to npm yet? Everybody lands on the readme, which clearly states 3.0.3 is the current version. But it's only installable like this:
```
$ npm i https://github.com/scottjehl/picturefill.git#3.0.3 --save
```

cc @Wilto @scottjehl @jegtnes

**Comment by mrienstra** [comment]
If @Wilto and @scottjehl are not available, maybe it's time to move to a new NPM module, and add a notice to the `README.md` directing people to it.

More generally, if this project needs a new lead maintainer, maybe it's time to set that process in motion.

As it stands now, I'd imagine many would be leery of making fixes / sending pull requests to this project, given the lack of recent activity.

This project is the highest-profile `<picture>` polyfill by far, it seems like a shame to let it slowly stagnate.

https://github.com/pickhardt/maintainers-wanted

https://openhatch.org/

**Comment by DanielRuf** [comment]
Bump.

**Comment by tbsvttr** [comment]
Same problem here. Please fix.

**Comment by daviddelusenet** [comment]
@scottjehl @Wilto

**Comment by fender** [comment]
+1

**Comment by DanielRuf** [comment]
Another friendly bump.

Please let me know if you need any maintainers.

**Comment by Wilto** [comment]
I’ll see about getting it published today.

**Comment by scottjehl** [comment]
I jumped in and grabbed this one today. Thanks for the nudge, folks. 

https://www.npmjs.com/package/picturefill
