### ISSUE TITLE
same image different breakpoints in the same page

### ISSUE THREAD

**Issue by vlrprbttst** [scottjehl/picturefill#680]
i'm testing out picturefill for the first time and i came across this weird behaviour. you can see it in action here: https://codepen.io/vlrprbttst/pen/MmPeey

what happens is:

i start with one responsive image set that has 2 breakpoints and two source images. it works as expected (i guess.. i'm still a bit confused). When i add another responsive image, with 3 breakpoints and 3 different image sources it's like these rules are overridden by the first responsive image and it doesn't work as expected. if i now comment out the first 2-breakpoint responsive image, the 3-breakpoint image works as expected.

is this supposed to happen or is it a bug? maybe this happens because the share the same urls?

**Comment by jegtnes** [comment]
Hey @vlrprbttst,

Could you describe what you expect to happen and what is actually happening instead, and let us know which browser you're seeing this behaviour in?

It's worth considering browsers who support responsive images, and Picturefill, are smart about srcset. If you've already got a larger version of an image and then for some reason trigger a point where you'd _think_ the browser would request another image (e.g. shrinking your browser), it doesn't initiate _another_ download for the smaller version of the image when it can scale the larger version of the image down instead.

If you need _exact_ control of what images appear at certain media query conditions, I'd recommend you use `<picture>` instead, which does grant you this granularity.

**Comment by vlrprbttst** [comment]
this answers my question! thank you
