### ISSUE TITLE
lazyloading + picturefill?

### ISSUE THREAD

**Issue by vlrprbttst** [scottjehl/picturefill#682]
i've been browsing and browsing for a solution to this but i can't seem to find anything reliable. is this something you are willing to address in the future? is there something you could suggest to make lazyloading happen with picturefill 3?

thanks

**Comment by christopherdarling** [comment]
Take a look at https://github.com/aFarkas/lazysizes/

**Comment by jegtnes** [comment]
Hey @vlrprbttst — this is not something Picturefill aims to do. It's just a polyfill. I can, indeed, second @christopherdarling's recommendation, Lazysizes is great. I've used this in production for several projects and it has been working wonderfully. :)

**Comment by vlrprbttst** [comment]
thanks a lot!
