### ISSUE TITLE
No image is being displayed on Chrome

### ISSUE THREAD

**Issue by dekkofilms** [scottjehl/picturefill#684]
I feel like I might be completely missing a step, so I apologize for that. I'm just looking for some guidance on serving WebP images when they are allowed, and pngs as fallbacks. I'm using ReactJS to build an SPA, and I've brought in the picturefill.js version 3.0.2. In my HTML I'm just simply doing:

```
<picture>
  <source
    srcset={require("../../../src/assets/images/banner1.webp")}
    type="image/webp"
  />
  <img
    srcset={require("../../../src/assets/images/banner1.png")}
    alt="Sandbox Commerce helps your marketing team engage with your customers"/>
</picture>
```

And on my page, I just get a black blank where the image is suppose to be. Wondering what I am missing here. I have both the .webp and .png image in my assets folder. 

![screen shot 2017-07-06 at 1 13 30 pm](https://user-images.githubusercontent.com/14862852/27926129-f7384d90-624c-11e7-873b-35d19745fd56.png)

**Comment by tito433** [comment]
@dekkofilms ,
I'm not familiar with ReactJS, but I know HTML and JS.
In you code you are suppose to print the webp image path in srcset, make sure you've the following html output in the browser:
`<picture>
  <source
    srcset="domain or path/assets/images/banner1.webp"
    type="image/webp"
  />
  <img
    srcset="domain or path/assets/images/banner1.png"
    alt="Sandbox Commerce helps your marketing team engage with your customers"/>
</picture>`

If I use following code what will be the output in the browser?
`<h1>{require("../../../src/assets/images/banner1.webp")}</h1>`
