### ISSUE TITLE
images included with source contain non-free licensed ICC profiles

### ISSUE THREAD

**Issue by jonassmedegaard** [scottjehl/picturefill#691]
Hi,

Some of the images included with the source of this project contain embedded ICC profiles which are copyright-protected and lack a Free license.

Specifically, these images are currently not legally free to redistribute:

 examples/images/art-large.jpg
 examples/images/art-medium.jpg
 examples/images/art-small.jpg
 examples/images/extralarge.jpg
 examples/images/extralarge.psd
 examples/images/image-384.psd
 examples/images/image-768.psd
 examples/images/large.psd
 examples/images/medium.jpg
 examples/images/medium.psd
 examples/images/small.jpg
 examples/images/small.psd
 logos/bocoup-lg.png
 logos/ricg-seal.png

 examples/images/pic-large.png
 examples/images/pic-medium.png
 examples/images/pic-small.png

 logos/bocoup-sm.png

The first group above contains an ICC profile owned by Hewlett Packard, and the latter two groups contain ICC profiles owned by Apple.

Most likely (I didn't check more detailed) those ICC profiles are all sRGB profiles which can simply be stripped, since for web use sRGB is the default color profile.

One way to inspect image files for embedded ICC profiles and its metadata is by use of the commandline tool exiftool, installed as part of the Perl distribution Image::ExifTool - i.e. on Debian-based systems by installing the package libimage-exiftool-perl, and on (Debian and) other systems by running "cpanm Image::ExifTool".

**Comment by jegtnes** [comment]
Thanks for letting us know, Jonas. I'm not an expert in colour profiling, so PRs are heartily welcome if you can spare the time!

**Comment by jonassmedegaard** [comment]
Sorry if unclear: You do *not* need to fumble with Exiftool to fix this issue.  I only mentioned that because when reporting to other projects, the authors got curious how they might do similar examinations on their own to identify the _problem_.

Fix: For each of the listed images (and may be beneficial for other images as well) run them through an "optimizer" which strips excess metadata - e.g. jpegoptim or pngcrush or optipng - or to use a simple tool for multiple types of images use trimage.

Sorry, I will not obey the licensing tricks of Github so it is too cumbersome for me to run those tools. I don't mind guiding further if you need that.

**Comment by jonassmedegaard** [comment]
In case of interest, here is a nice summary of the concerns I have with pushing code to Github: http://www.lieberbiber.de/2017/03/02/confusion-over-githubs-new-tos-open-source-projects-remove-repositories/
