### ISSUE TITLE
Works on Chrome mobile view, but not on iOS Safari

### ISSUE THREAD

**Issue by MikesBarto2002** [scottjehl/picturefill#692]
http://www-uat.al.com/oap_testing_blog/2017/09/testing_images.html

It seems that when I render this page on the mobile view on Chrome, the first image in the article loads correctly, taking up the full width of the screen. But when I load this in iOS Safari, it is not loading full width.

On desktop mobile view, it is loading in a 480px width image, where on mobile, it is loading in a 960px width image. Here is my image tag:

`<img srcset="http://image.com/width328/img/image.jpg 328w, http://image.com/width480/img/image.jpg 480w, http://image.com/width600/img/image.jpg 600w, http://image.com/width960/img/image.jpg 960w" alt="EPCOT(<cite>M. Mouse</cite>)">`

As a comparison to that first image, if you scroll down to the second article, you will find an image in the same position that is responding correctly.

**Comment by mike-engel** [comment]
@MikesBarto2002 Thanks for submitting this issue. This doesn't seem, however, to be an issue with picturefill, as iOS Safari natively supports responsive images. When that happens, picturefill doesn't even run. So this is most likely an issue with your markup, or a bug with Safari. Thanks!
