### ISSUE TITLE
Is it possible to make the package work with SSR?

### ISSUE THREAD

**Issue by aviramga** [scottjehl/picturefill#697]
Hi,

I am using NextJS (react ssr) and tried to use your package.
There is an issue when trying to use it as it uses the window object.

How can I make it work in SSR?

Thanks!

**Comment by Aziz-JH** [comment]
Hi,
I had the same problem and i fixed with `process.browser`.

_polyfills.js_
```
if (process.browser) {
  require('picturefill');
}
```
Best,
Julian
