### ISSUE TITLE
Chrome 71 exitFullscreen Bug

### ISSUE THREAD

**Issue by FrediBach** [scottjehl/picturefill#709]
In Chrome 71 I get this error: `Uncaught (in promise) TypeError: Document not active`

It's this part that throws the error: `document.exitFullscreen?document.exitFullscreen()`

In Chrome 71 (and probably other recent browsers), you are not allowed to call exitFullscreen if you're not already in fullscreen mode.

**Comment by aFarkas** [comment]
https://github.com/scottjehl/picturefill/search?q=document.exitFullscreen&type=Code
