### ISSUE TITLE
pf.mutations plugin throws error in IE11

### ISSUE THREAD

**Issue by TylerBarnes** [scottjehl/picturefill#710]
Adding just picturefill doesn't seem to work for my case. I'm using picturefill with react and Gatsbyjs.
I see that using pf.mutations should make it work. 
If I include this file in my site though I get an error in IE

`Unhandled promise rejection TypeError: Assignment to read-only properties is not allowed in strict mode`

Is there something else I need to do to make it work in IE11?

**Comment by aFarkas** [comment]
> Is there something else I need to do to make it work in IE11?

No it should work then.

Can you please provide a test case or at least a link to your project (you can also mail it to me). Without being able to reproduce this bug it is for us impossible to fix it.

**Comment by TylerBarnes** [comment]
Hey @aFarkas !
I can't reproduce this issue anymore but I also still can't get picturefill working in IE11.
I'm not sure if it's related to gatsby or react or if I'm loading it wrong.
I tried to create a repro for this issue but ended up opening an issue at the gatsby github https://github.com/gatsbyjs/gatsby/issues/11558. 

If the initial picture elements don't get polyfilled, is there a way for me to check if images that are then dynamically added afterwards are polyfilled via the pf.mutations plugin? Is there some way I could check in the DOM?
