### ISSUE TITLE
How to use in nuxt project ?

### ISSUE THREAD

**Issue by golubvladimir** [scottjehl/picturefill#716]
How to use polyfill in nuxt project ?

**Comment by hbanham** [comment]
I just started using Nuxt so had the same question. Picturefill has a "Mutation plugin" that works well.
My solution was to create a plugin file called picturefill.js in /plugins/ and import picturefill and it's plugin here.

/plugins/picturefill.js
```
import 'picturefill';
import 'picturefill/dist/plugins/mutation/pf.mutation';
```

nuxt.config.js
```
plugins: [{ src: "~/plugins/picturefill.js", mode: "client" }]
```
