### ISSUE TITLE
Static Page is down

### ISSUE THREAD

**Issue by tomleo** [scottjehl/picturefill#719]
Going to https://scottjehl.github.com/picturefill/ 404s currently.

**Comment by chalkygames123** [comment]
GitHub Pages will stop redirecting Pages sites from *.github.com after April 15, 2021 | GitHub Changelog https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/

**Comment by michaeljaltamirano** [comment]
https://scottjehl.github.io/picturefill/

**Comment by scottjehl** [comment]
fixed
